//! `.env.example` and `docs/CONFIG.md`, generated from the key table (`scacelith-server
//! gen-config-docs`; `--check` fails when a committed file is out of date).
//!
//! `.env.example`: one block per section; each key is preceded by its description, its type and
//! bounds. Keys with a default are commented out with that default (uncomment to change it, so
//! that a later release's better default is not pinned by accident); required keys are
//! uncommented and empty; secrets never carry a value.

use std::fs;
use std::io::Write;
use std::path::Path;

use super::keys::{KEYS, KeySpec, Kind, OBSOLETE, Section};
use crate::util::js;

const GENERATED_BY: &str = "Generated by `scacelith-server gen-config-docs` from crates/server/src/config/keys.rs: do not edit by hand.";

/// The files written by [`gen_config_docs`], relative to the server directory.
pub const GENERATED_FILES: [&str; 2] = [".env.example", "docs/CONFIG.md"];

/// Keys grouped by section, in table order.
fn sections() -> Vec<(Section, Vec<&'static KeySpec>)> {
    let mut out: Vec<(Section, Vec<&'static KeySpec>)> = Vec::new();
    for k in KEYS {
        match out.iter_mut().find(|(s, _)| *s == k.section) {
            Some((_, list)) => list.push(k),
            None => out.push((k.section, vec![k])),
        }
    }
    out
}

/// Words of `text` in lines of at most `width` characters, each starting with `prefix`.
fn wrap(text: &str, width: usize, prefix: &str) -> Vec<String> {
    let mut lines = Vec::new();
    let mut line = String::new();
    for word in text.split(js::is_whitespace).filter(|w| !w.is_empty()) {
        if !line.is_empty() && js::utf16_len(prefix) + js::utf16_len(&line) + 1 + js::utf16_len(word) > width
        {
            lines.push(format!("{prefix}{line}"));
            line = word.to_string();
        } else {
            if !line.is_empty() {
                line.push(' ');
            }
            line.push_str(word);
        }
    }
    if !line.is_empty() {
        lines.push(format!("{prefix}{line}"));
    }
    lines
}

fn bounds_text(what: &str, k: &KeySpec) -> String {
    match (k.min, k.max) {
        (Some(min), Some(max)) => format!("{what} ({min}-{max})"),
        (Some(min), None) => format!("{what} (>= {min})"),
        (None, Some(max)) => format!("{what} (<= {max})"),
        (None, None) => what.to_string(),
    }
}

/// The type of a key as the generated files describe it.
pub fn type_text(k: &KeySpec) -> String {
    match k.kind {
        Kind::Enum(values) => format!("one of {}", values.join(", ")),
        Kind::Bool => "boolean (true/false, 1/0, yes/no, on/off)".to_string(),
        Kind::Port => "port (0-65535)".to_string(),
        Kind::List => "comma-separated list".to_string(),
        Kind::Secret => match k.min_bytes {
            Some(n) => format!("secret (at least {n} bytes, hex or base64)"),
            None => "secret".to_string(),
        },
        Kind::SecretText => "secret text (used as written)".to_string(),
        Kind::Int => bounds_text("integer", k),
        Kind::Number => bounds_text("number", k),
        Kind::Text => match (k.max_bytes, k.max_chars) {
            (Some(n), _) => format!("text (at most {n} bytes in UTF-8)"),
            (None, Some(n)) => format!("text (at most {n} characters)"),
            (None, None) => "text".to_string(),
        },
        Kind::Path => "path (relative to the working directory)".to_string(),
    }
}

/// The `.env.example` text.
pub fn render_env_example() -> String {
    let mut out: Vec<String> = [
        "# Scacelith dedicated server configuration.",
        "#",
        "# Generated by `scacelith-server gen-config-docs` from crates/server/src/config/keys.rs: do not",
        "# edit by hand. Copy this file to .env (in the server's working directory, or point",
        "# SCACELITH_ENV_FILE at it) and adjust it; real environment variables take precedence over the",
        "# file. Check the result with `scacelith-server check-config`.",
        "#",
        "# Commented-out lines show the default. Lines marked REQUIRED must be set. Secrets may also be",
        "# given as a file: FOO_FILE=/run/secrets/foo (keeps them out of the environment listing; with",
        "# systemd, LoadCredential= and FOO_FILE=%d/foo). Generate a secret with",
        "# `scacelith-server gen-secret`.",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect();
    let rule = format!("# {}", "=".repeat(96));
    for (section, list) in sections() {
        out.push(String::new());
        out.push(rule.clone());
        out.push(format!("# {}", section.title()));
        out.push(rule.clone());
        for k in list {
            out.push(String::new());
            out.extend(wrap(k.desc, 100, "# "));
            let mut facts = Vec::new();
            if k.required {
                facts.push("REQUIRED.".to_string());
            }
            facts.push(format!("Type: {}.", type_text(k)));
            if k.kind.is_secret() {
                facts.push(format!("Or {}_FILE=<path>.", k.name));
            }
            out.extend(wrap(&facts.join(" "), 100, "# "));
            if k.required {
                out.push(format!("{}=", k.name));
            } else if k.kind == Kind::Secret {
                out.push(format!("# {}=", k.name));
            } else {
                out.push(format!("# {}={}", k.name, k.default.unwrap_or("")));
            }
        }
    }
    out.push(String::new());
    out.join("\n")
}

/// Markdown table cell text.
fn md(s: &str) -> String {
    s.replace('|', "\\|").replace('<', "&lt;").replace('>', "&gt;")
}

fn anchor(title: &str) -> String {
    title
        .to_lowercase()
        .chars()
        .filter(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || *c == ' ' || *c == '-')
        .map(|c| if c == ' ' { '-' } else { c })
        .collect()
}

/// The `docs/CONFIG.md` text.
pub fn render_config_doc() -> String {
    let obsolete: Vec<String> = OBSOLETE.iter().map(|(k, _)| format!("`{k}`")).collect();
    let intro = format!(
        "The server reads its settings from environment variables and from an optional `.env` file (`KEY=value` \
         lines; `.env` in the working directory, or the file named by `SCACELITH_ENV_FILE`). Environment \
         variables take precedence over the file. A secret can also be given as a file with the `_FILE` suffix \
         (`SERVER_SECRET_FILE=/run/secrets/scacelith`, or `%d/scacelith` with the `LoadCredential=` of systemd), \
         which keeps it out of the process environment. `scacelith-server check-config` validates the \
         configuration and prints the effective values (secrets masked, derived defaults computed); \
         `scacelith-server gen-secret` prints a fresh random secret. `.env.example` lists every key with its \
         default.\n\nSettings described as \"whole server\" apply to the one server process. Where the former \
         Node.js server counted per worker process, the defaults now scale with `WORKERS`, so that a server keeps \
         its capacity. Keys of the former server that no longer apply ({}) are ignored with a warning.",
        obsolete.join(", ")
    );
    let mut out =
        vec!["# Server configuration".to_string(), String::new(), format!("<!-- {GENERATED_BY} -->")];
    for paragraph in intro.split("\n\n") {
        out.push(String::new());
        out.extend(wrap(paragraph, 100, ""));
    }
    out.push(String::new());
    out.push("Sections:".to_string());
    out.push(String::new());
    let all = sections();
    for (section, _) in &all {
        out.push(format!("- [{}](#{})", section.title(), anchor(section.title())));
    }
    for (section, list) in all {
        out.push(String::new());
        out.push(format!("## {}", section.title()));
        out.push(String::new());
        out.push("| Variable | Type | Default | Description |".to_string());
        out.push("| --- | --- | --- | --- |".to_string());
        for k in list {
            let default = if k.required {
                "**required**".to_string()
            } else if k.kind == Kind::Secret {
                "(unset)".to_string()
            } else {
                match k.default.unwrap_or("") {
                    "" => "(empty)".to_string(),
                    d => format!("`{}`", md(d)),
                }
            };
            let name = if k.kind.is_secret() {
                format!("`{0}`<br>`{0}_FILE`", k.name)
            } else {
                format!("`{}`", k.name)
            };
            out.push(format!("| {name} | {} | {default} | {} |", md(&type_text(k)), md(k.desc)));
        }
    }
    out.push(String::new());
    out.join("\n")
}

/// The generated files and their expected contents.
fn expected() -> [(&'static str, String); 2] {
    [(GENERATED_FILES[0], render_env_example()), (GENERATED_FILES[1], render_config_doc())]
}

/// The generated files under `root` whose content is not current.
pub fn stale_files(root: &Path) -> Vec<&'static str> {
    expected()
        .into_iter()
        .filter(|(file, text)| fs::read_to_string(root.join(file)).ok().as_deref() != Some(text.as_str()))
        .map(|(file, _)| file)
        .collect()
}

/// `scacelith-server gen-config-docs [--check]`, run from the server directory (`root`): writes the
/// generated files, or with `check` reports the stale ones. Messages go to `out` and `err`; returns
/// the exit code.
pub fn gen_config_docs(root: &Path, check: bool, out: &mut dyn Write, err: &mut dyn Write) -> i32 {
    if !root.join("crates/server/Cargo.toml").is_file() {
        let _ = writeln!(
            err,
            "gen-config-docs: run it from the dedicated-server directory (the one that holds crates/ and docs/)."
        );
        return 1;
    }
    let mut code = 0;
    for (file, text) in expected() {
        let path = root.join(file);
        if fs::read_to_string(&path).ok().as_deref() == Some(text.as_str()) {
            continue;
        }
        if check {
            let _ = writeln!(err, "{file} is out of date: run scacelith-server gen-config-docs");
            code = 1;
            continue;
        }
        let written = path.parent().map_or(Ok(()), fs::create_dir_all).and_then(|()| fs::write(&path, &text));
        match written {
            Ok(()) => {
                let _ = writeln!(out, "wrote {file}");
            }
            Err(e) => {
                let _ = writeln!(err, "gen-config-docs: cannot write {file} ({e})");
                code = 1;
            }
        }
    }
    code
}
