// Chess rules of the dedicated server (DESIGN.md section 5.2): an exact mirror of the game's
// chess::Position / chess::Game (src/chess/position.cpp, game.cpp): same legal moves, same FEN
// normalisation (castling rights without king/rook on their squares dropped, en passant square
// only when an en passant capture is legal), same automatic endings (checkmate, stalemate, dead
// position, fivefold repetition, 75-move rule), same claims (threefold, fifty moves), same flag
// fall rule (draw when the opponent cannot mate: canColorMate), same SAN/UCI/FEN text.
// test/unit/chess.crosscheck.test.js replays test/fixtures/chess-crosscheck.json, generated by
// the game's own C++ code (tools/gen-chess-crosscheck.sh), and requires every FEN, digest, legal
// move list, SAN, flag and result to match.
//
// Moves are the protocol u16: from | to << 6 | promo << 12 (squares a1 = 0 .. h8 = 63; promo 0,
// or 2 N, 3 B, 4 R, 5 Q). Castling is the king's move (e1g1).
//
// Notes and deviations from the DESIGN.md contract (all additive or stricter):
//  * The enums (GameStatus, EndReason, MoveFlag) are defined in ./constants.js with the values
//    of src/protocol/schema.js so this module has no import outside src/chess; a unit test
//    compares them with the schema.
//  * isLegal()/play() are strict about the u16: a non-promotion move must have promo = 0 and a
//    promotion must carry 2..5. (chess::Position::findLegal ignores the promotion field of a
//    non-promotion move; the game client always sends 0 there, so honest clients are unaffected.)
//  * repetitionKey() is the 64-bit Zobrist key in 16 hex digits, bit-identical to the game's
//    chess::Position::hash() (same keys, same seed). ChessGame compares these keys (two int32
//    halves, no allocation) instead of whole boards: a false repetition needs a 64-bit collision
//    among the <= 75 same-side positions of the current irreversible window.
//  * resign/agreeDraw/flagFall/claimDraw/end return a boolean: true when the call ended the game
//    (false when it was already over or, for claimDraw, when there is nothing to claim).
//    end(status, reason) validates its arguments (RangeError).
//  * Additions: Position.pieceAt/kingSquare/isAttacked/keyLo/keyHi, ChessGame.fromMoves (journal
//    replay), startFen/ply/isOver getters, resultString(), uciMoves(), endReasonText(),
//    squareName()/parseSquare(). pgn(tags) takes the player names as tags.white / tags.black,
//    and, for the server's PGN export (GET /api/v1/games/:id/pgn), tags.afterResult (tags written
//    after Result) and tags.comments (a comment per ply, e.g. [%clk] / [%emt]; a Black move after
//    a comment repeats its number). Its Termination tag covers the online endings: an aborted
//    game (Result "*") is "unterminated", an abandonment "abandoned", a fair-play forfeit a
//    "rules infraction".
//
// Performance (Node 22.22, one core; tools/bench-chess.js): Position isLegal + play ~0.5 us per
// move, ChessGame isLegal + play (with the automatic endings) ~1.1 us, digest() ~0.4 us, no
// allocation on that path besides the small result object of ChessGame.play; perft 12-30 M
// leaf nodes/s (bulk counting).

import { SQ_NAMES } from './tables.js';
import { _parseSquare } from './position.js';

export { WHITE, BLACK, PieceType, GameStatus, EndReason, MoveFlag, CastlingRight } from './constants.js';
export { Position } from './position.js';
export { ChessGame, endReasonText } from './game.js';
export { readPgn, PgnError, PGN_LIMITS } from './pgn.js';

/**
 * @param {number} sq 0..63
 * @returns {string} "e4", "-" when out of range.
 */
export function squareName(sq) {
    return (sq | 0) === sq && sq >= 0 && sq < 64 ? SQ_NAMES[sq] : '-';
}

/**
 * @param {string} s "e4" (file letter may be upper case)
 * @returns {number} 0..63, or -1.
 */
export function parseSquare(s) {
    return typeof s === 'string' ? _parseSquare(s) : -1;
}
