// @generated by protogen from protocol/scacelith-v1.json: do not edit. Regenerate with
// `cargo run -p scacelith-protocol --features gen --bin protogen`.

//! JSON form of the messages, as in the golden vectors (tests only).

use serde_json::{Map, Value};

use crate::r#gen::*;

fn int<T: TryFrom<i64>>(v: &Value, key: &str) -> Option<T> {
    T::try_from(v.get(key)?.as_i64()?).ok()
}

fn uint<T: TryFrom<u64>>(v: &Value, key: &str) -> Option<T> {
    T::try_from(v.get(key)?.as_u64()?).ok()
}

fn color_from(v: &Value) -> Option<Color> {
    Color::from_u8(u8::try_from(v.as_u64()?).ok()?)
}

fn color_pref_from(v: &Value) -> Option<ColorPref> {
    ColorPref::from_u8(u8::try_from(v.as_u64()?).ok()?)
}

fn game_status_from(v: &Value) -> Option<GameStatus> {
    GameStatus::from_u8(u8::try_from(v.as_u64()?).ok()?)
}

fn end_reason_from(v: &Value) -> Option<EndReason> {
    Some(EndReason::from_u8(u8::try_from(v.as_u64()?).ok()?))
}

fn game_event_kind_from(v: &Value) -> Option<GameEventKind> {
    Some(GameEventKind::from_u8(u8::try_from(v.as_u64()?).ok()?))
}

fn queue_state_from(v: &Value) -> Option<QueueState> {
    Some(QueueState::from_u8(u8::try_from(v.as_u64()?).ok()?))
}

fn challenge_state_from(v: &Value) -> Option<ChallengeState> {
    Some(ChallengeState::from_u8(u8::try_from(v.as_u64()?).ok()?))
}

fn notice_code_from(v: &Value) -> Option<NoticeCode> {
    Some(NoticeCode::from_u8(u8::try_from(v.as_u64()?).ok()?))
}

fn error_code_from(v: &Value) -> Option<ErrorCode> {
    Some(ErrorCode::from_u8(u8::try_from(v.as_u64()?).ok()?))
}

fn player_info_to_json(m: &PlayerInfo) -> Value {
    let mut o = Map::new();
    o.insert("userId".into(), m.user_id.into());
    o.insert("name".into(), m.name.clone().into());
    o.insert("rating".into(), m.rating.into());
    o.insert("provisional".into(), m.provisional.into());
    Value::Object(o)
}

fn player_info_from_json(v: &Value) -> Option<PlayerInfo> {
    Some(PlayerInfo {
        user_id: uint(v, "userId")?,
        name: v.get("name")?.as_str()?.to_owned(),
        rating: uint(v, "rating")?,
        provisional: v.get("provisional")?.as_bool()?,
    })
}

fn move_rec_to_json(m: &MoveRec) -> Value {
    let mut o = Map::new();
    o.insert("move".into(), m.r#move.into());
    o.insert("spentMs".into(), m.spent_ms.into());
    o.insert("clockMs".into(), m.clock_ms.into());
    Value::Object(o)
}

fn move_rec_from_json(v: &Value) -> Option<MoveRec> {
    Some(MoveRec {
        r#move: uint(v, "move")?,
        spent_ms: uint(v, "spentMs")?,
        clock_ms: uint(v, "clockMs")?,
    })
}

fn rating_change_to_json(m: &RatingChange) -> Value {
    let mut o = Map::new();
    o.insert("before".into(), m.before.into());
    o.insert("after".into(), m.after.into());
    o.insert("games".into(), m.games.into());
    o.insert("provisional".into(), m.provisional.into());
    Value::Object(o)
}

fn rating_change_from_json(v: &Value) -> Option<RatingChange> {
    Some(RatingChange {
        before: uint(v, "before")?,
        after: uint(v, "after")?,
        games: uint(v, "games")?,
        provisional: v.get("provisional")?.as_bool()?,
    })
}

fn hello_to_json(m: &Hello) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("proto".into(), m.proto.into());
    o.insert("minor".into(), m.minor.into());
    o.insert("caps".into(), m.caps.into());
    o.insert("client".into(), m.client.clone().into());
    o.insert("token".into(), m.token.clone().into());
    Value::Object(o)
}

fn hello_from_json(v: &Value) -> Option<Hello> {
    Some(Hello {
        seq: uint(v, "seq")?,
        proto: uint(v, "proto")?,
        minor: uint(v, "minor")?,
        caps: uint(v, "caps")?,
        client: v.get("client")?.as_str()?.to_owned(),
        token: v.get("token")?.as_str()?.to_owned(),
    })
}

fn client_ping_to_json(m: &ClientPing) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("nonce".into(), m.nonce.into());
    Value::Object(o)
}

fn client_ping_from_json(v: &Value) -> Option<ClientPing> {
    Some(ClientPing {
        seq: uint(v, "seq")?,
        nonce: uint(v, "nonce")?,
    })
}

fn client_pong_to_json(m: &ClientPong) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("nonce".into(), m.nonce.into());
    Value::Object(o)
}

fn client_pong_from_json(v: &Value) -> Option<ClientPong> {
    Some(ClientPong {
        seq: uint(v, "seq")?,
        nonce: uint(v, "nonce")?,
    })
}

fn queue_join_to_json(m: &QueueJoin) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("category".into(), m.category.clone().into());
    o.insert("rated".into(), m.rated.into());
    Value::Object(o)
}

fn queue_join_from_json(v: &Value) -> Option<QueueJoin> {
    Some(QueueJoin {
        seq: uint(v, "seq")?,
        category: v.get("category")?.as_str()?.to_owned(),
        rated: v.get("rated")?.as_bool()?,
    })
}

fn queue_leave_to_json(m: &QueueLeave) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    Value::Object(o)
}

fn queue_leave_from_json(v: &Value) -> Option<QueueLeave> {
    Some(QueueLeave {
        seq: uint(v, "seq")?,
    })
}

fn challenge_create_to_json(m: &ChallengeCreate) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("target".into(), m.target.clone().into());
    o.insert("baseSec".into(), m.base_sec.into());
    o.insert("incSec".into(), m.inc_sec.into());
    o.insert("rated".into(), m.rated.into());
    o.insert("color".into(), m.color.to_u8().into());
    Value::Object(o)
}

fn challenge_create_from_json(v: &Value) -> Option<ChallengeCreate> {
    Some(ChallengeCreate {
        seq: uint(v, "seq")?,
        target: v.get("target")?.as_str()?.to_owned(),
        base_sec: uint(v, "baseSec")?,
        inc_sec: uint(v, "incSec")?,
        rated: v.get("rated")?.as_bool()?,
        color: color_pref_from(v.get("color")?)?,
    })
}

fn challenge_accept_to_json(m: &ChallengeAccept) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("id".into(), m.id.into());
    Value::Object(o)
}

fn challenge_accept_from_json(v: &Value) -> Option<ChallengeAccept> {
    Some(ChallengeAccept {
        seq: uint(v, "seq")?,
        id: uint(v, "id")?,
    })
}

fn challenge_decline_to_json(m: &ChallengeDecline) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("id".into(), m.id.into());
    Value::Object(o)
}

fn challenge_decline_from_json(v: &Value) -> Option<ChallengeDecline> {
    Some(ChallengeDecline {
        seq: uint(v, "seq")?,
        id: uint(v, "id")?,
    })
}

fn challenge_cancel_to_json(m: &ChallengeCancel) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("id".into(), m.id.into());
    Value::Object(o)
}

fn challenge_cancel_from_json(v: &Value) -> Option<ChallengeCancel> {
    Some(ChallengeCancel {
        seq: uint(v, "seq")?,
        id: uint(v, "id")?,
    })
}

fn challenge_join_code_to_json(m: &ChallengeJoinCode) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("code".into(), m.code.clone().into());
    Value::Object(o)
}

fn challenge_join_code_from_json(v: &Value) -> Option<ChallengeJoinCode> {
    Some(ChallengeJoinCode {
        seq: uint(v, "seq")?,
        code: v.get("code")?.as_str()?.to_owned(),
    })
}

fn move_to_json(m: &Move) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    o.insert("ply".into(), m.ply.into());
    o.insert("move".into(), m.r#move.into());
    o.insert("posHash".into(), m.pos_hash.into());
    o.insert("thinkMs".into(), m.think_ms.into());
    o.insert("drawOffer".into(), m.draw_offer.into());
    Value::Object(o)
}

fn move_from_json(v: &Value) -> Option<Move> {
    Some(Move {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
        ply: uint(v, "ply")?,
        r#move: uint(v, "move")?,
        pos_hash: uint(v, "posHash")?,
        think_ms: uint(v, "thinkMs")?,
        draw_offer: v.get("drawOffer")?.as_bool()?,
    })
}

fn resign_to_json(m: &Resign) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    Value::Object(o)
}

fn resign_from_json(v: &Value) -> Option<Resign> {
    Some(Resign {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
    })
}

fn draw_offer_to_json(m: &DrawOffer) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    Value::Object(o)
}

fn draw_offer_from_json(v: &Value) -> Option<DrawOffer> {
    Some(DrawOffer {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
    })
}

fn draw_answer_to_json(m: &DrawAnswer) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    o.insert("accept".into(), m.accept.into());
    Value::Object(o)
}

fn draw_answer_from_json(v: &Value) -> Option<DrawAnswer> {
    Some(DrawAnswer {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
        accept: v.get("accept")?.as_bool()?,
    })
}

fn draw_claim_to_json(m: &DrawClaim) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    Value::Object(o)
}

fn draw_claim_from_json(v: &Value) -> Option<DrawClaim> {
    Some(DrawClaim {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
    })
}

fn abort_to_json(m: &Abort) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    Value::Object(o)
}

fn abort_from_json(v: &Value) -> Option<Abort> {
    Some(Abort {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
    })
}

fn resync_to_json(m: &Resync) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    Value::Object(o)
}

fn resync_from_json(v: &Value) -> Option<Resync> {
    Some(Resync {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
    })
}

fn rematch_to_json(m: &Rematch) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    o.insert("accept".into(), m.accept.into());
    Value::Object(o)
}

fn rematch_from_json(v: &Value) -> Option<Rematch> {
    Some(Rematch {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
        accept: v.get("accept")?.as_bool()?,
    })
}

fn client_gesture_to_json(m: &ClientGesture) -> Value {
    let mut o = Map::new();
    o.insert("seq".into(), m.seq.into());
    o.insert("game".into(), m.game.into());
    o.insert("ply".into(), m.ply.into());
    o.insert("touch".into(), m.touch.into());
    o.insert("aim".into(), m.aim.into());
    o.insert("placed".into(), m.placed.into());
    o.insert("flags".into(), m.flags.into());
    o.insert("yaw".into(), m.yaw.into());
    o.insert("pitch".into(), m.pitch.into());
    o.insert("lean".into(), m.lean.into());
    Value::Object(o)
}

fn client_gesture_from_json(v: &Value) -> Option<ClientGesture> {
    Some(ClientGesture {
        seq: uint(v, "seq")?,
        game: uint(v, "game")?,
        ply: uint(v, "ply")?,
        touch: uint(v, "touch")?,
        aim: uint(v, "aim")?,
        placed: uint(v, "placed")?,
        flags: uint(v, "flags")?,
        yaw: int(v, "yaw")?,
        pitch: int(v, "pitch")?,
        lean: uint(v, "lean")?,
    })
}

fn welcome_to_json(m: &Welcome) -> Value {
    let mut o = Map::new();
    o.insert("proto".into(), m.proto.into());
    o.insert("minor".into(), m.minor.into());
    o.insert("caps".into(), m.caps.into());
    o.insert("serverTime".into(), m.server_time.into());
    o.insert("userId".into(), m.user_id.into());
    o.insert("username".into(), m.username.clone().into());
    o.insert("serverName".into(), m.server_name.clone().into());
    o.insert("heartbeatMs".into(), m.heartbeat_ms.into());
    o.insert("clientPingMs".into(), m.client_ping_ms.into());
    o.insert("maxMsgPerSec".into(), m.max_msg_per_sec.into());
    o.insert("msgBurst".into(), m.msg_burst.into());
    o.insert("activeGame".into(), m.active_game.into());
    o.insert("gestureRate".into(), m.gesture_rate.into());
    o.insert("gestureBurst".into(), m.gesture_burst.into());
    o.insert("gestureIdleMs".into(), m.gesture_idle_ms.into());
    Value::Object(o)
}

fn welcome_from_json(v: &Value) -> Option<Welcome> {
    Some(Welcome {
        proto: uint(v, "proto")?,
        minor: uint(v, "minor")?,
        caps: uint(v, "caps")?,
        server_time: v.get("serverTime")?.as_f64()?,
        user_id: uint(v, "userId")?,
        username: v.get("username")?.as_str()?.to_owned(),
        server_name: v.get("serverName")?.as_str()?.to_owned(),
        heartbeat_ms: uint(v, "heartbeatMs")?,
        client_ping_ms: uint(v, "clientPingMs")?,
        max_msg_per_sec: uint(v, "maxMsgPerSec")?,
        msg_burst: uint(v, "msgBurst")?,
        active_game: uint(v, "activeGame")?,
        gesture_rate: uint(v, "gestureRate")?,
        gesture_burst: uint(v, "gestureBurst")?,
        gesture_idle_ms: uint(v, "gestureIdleMs")?,
    })
}

fn error_to_json(m: &Error) -> Value {
    let mut o = Map::new();
    o.insert("ref".into(), m.r#ref.into());
    o.insert("code".into(), m.code.to_u8().into());
    o.insert("fatal".into(), m.fatal.into());
    o.insert("game".into(), m.game.into());
    Value::Object(o)
}

fn error_from_json(v: &Value) -> Option<Error> {
    Some(Error {
        r#ref: uint(v, "ref")?,
        code: error_code_from(v.get("code")?)?,
        fatal: v.get("fatal")?.as_bool()?,
        game: uint(v, "game")?,
    })
}

fn server_ping_to_json(m: &ServerPing) -> Value {
    let mut o = Map::new();
    o.insert("nonce".into(), m.nonce.into());
    o.insert("serverTime".into(), m.server_time.into());
    Value::Object(o)
}

fn server_ping_from_json(v: &Value) -> Option<ServerPing> {
    Some(ServerPing {
        nonce: uint(v, "nonce")?,
        server_time: v.get("serverTime")?.as_f64()?,
    })
}

fn server_pong_to_json(m: &ServerPong) -> Value {
    let mut o = Map::new();
    o.insert("nonce".into(), m.nonce.into());
    o.insert("serverTime".into(), m.server_time.into());
    Value::Object(o)
}

fn server_pong_from_json(v: &Value) -> Option<ServerPong> {
    Some(ServerPong {
        nonce: uint(v, "nonce")?,
        server_time: v.get("serverTime")?.as_f64()?,
    })
}

fn ack_to_json(m: &Ack) -> Value {
    let mut o = Map::new();
    o.insert("ref".into(), m.r#ref.into());
    Value::Object(o)
}

fn ack_from_json(v: &Value) -> Option<Ack> {
    Some(Ack {
        r#ref: uint(v, "ref")?,
    })
}

fn notice_to_json(m: &Notice) -> Value {
    let mut o = Map::new();
    o.insert("code".into(), m.code.to_u8().into());
    o.insert("arg".into(), m.arg.into());
    Value::Object(o)
}

fn notice_from_json(v: &Value) -> Option<Notice> {
    Some(Notice {
        code: notice_code_from(v.get("code")?)?,
        arg: v.get("arg")?.as_f64()?,
    })
}

fn queue_status_to_json(m: &QueueStatus) -> Value {
    let mut o = Map::new();
    o.insert("category".into(), m.category.clone().into());
    o.insert("rated".into(), m.rated.into());
    o.insert("state".into(), m.state.to_u8().into());
    o.insert("waitMs".into(), m.wait_ms.into());
    o.insert("window".into(), m.window.into());
    o.insert("queued".into(), m.queued.into());
    Value::Object(o)
}

fn queue_status_from_json(v: &Value) -> Option<QueueStatus> {
    Some(QueueStatus {
        category: v.get("category")?.as_str()?.to_owned(),
        rated: v.get("rated")?.as_bool()?,
        state: queue_state_from(v.get("state")?)?,
        wait_ms: uint(v, "waitMs")?,
        window: uint(v, "window")?,
        queued: uint(v, "queued")?,
    })
}

fn challenge_received_to_json(m: &ChallengeReceived) -> Value {
    let mut o = Map::new();
    o.insert("id".into(), m.id.into());
    o.insert("from".into(), player_info_to_json(&m.from));
    o.insert("baseSec".into(), m.base_sec.into());
    o.insert("incSec".into(), m.inc_sec.into());
    o.insert("rated".into(), m.rated.into());
    o.insert("yourColor".into(), m.your_color.to_u8().into());
    o.insert("expiresMs".into(), m.expires_ms.into());
    Value::Object(o)
}

fn challenge_received_from_json(v: &Value) -> Option<ChallengeReceived> {
    Some(ChallengeReceived {
        id: uint(v, "id")?,
        from: player_info_from_json(v.get("from")?)?,
        base_sec: uint(v, "baseSec")?,
        inc_sec: uint(v, "incSec")?,
        rated: v.get("rated")?.as_bool()?,
        your_color: color_pref_from(v.get("yourColor")?)?,
        expires_ms: uint(v, "expiresMs")?,
    })
}

fn challenge_status_to_json(m: &ChallengeStatus) -> Value {
    let mut o = Map::new();
    o.insert("id".into(), m.id.into());
    o.insert("state".into(), m.state.to_u8().into());
    o.insert("target".into(), m.target.clone().into());
    o.insert("code".into(), m.code.clone().into());
    o.insert("baseSec".into(), m.base_sec.into());
    o.insert("incSec".into(), m.inc_sec.into());
    o.insert("rated".into(), m.rated.into());
    Value::Object(o)
}

fn challenge_status_from_json(v: &Value) -> Option<ChallengeStatus> {
    Some(ChallengeStatus {
        id: uint(v, "id")?,
        state: challenge_state_from(v.get("state")?)?,
        target: v.get("target")?.as_str()?.to_owned(),
        code: v.get("code")?.as_str()?.to_owned(),
        base_sec: uint(v, "baseSec")?,
        inc_sec: uint(v, "incSec")?,
        rated: v.get("rated")?.as_bool()?,
    })
}

fn game_snapshot_to_json(m: &GameSnapshot) -> Value {
    let mut o = Map::new();
    o.insert("game".into(), m.game.into());
    o.insert("gseq".into(), m.gseq.into());
    o.insert("category".into(), m.category.clone().into());
    o.insert("baseMs".into(), m.base_ms.into());
    o.insert("incMs".into(), m.inc_ms.into());
    o.insert("rated".into(), m.rated.into());
    o.insert("white".into(), player_info_to_json(&m.white));
    o.insert("black".into(), player_info_to_json(&m.black));
    o.insert("you".into(), m.you.to_u8().into());
    o.insert("moves".into(), Value::Array(m.moves.iter().map(move_rec_to_json).collect()));
    o.insert("running".into(), m.running.to_u8().into());
    o.insert("whiteMs".into(), m.white_ms.into());
    o.insert("blackMs".into(), m.black_ms.into());
    o.insert("serverTime".into(), m.server_time.into());
    o.insert("drawOffer".into(), m.draw_offer.to_u8().into());
    o.insert("status".into(), m.status.to_u8().into());
    o.insert("reason".into(), m.reason.to_u8().into());
    o.insert("whiteConnected".into(), m.white_connected.into());
    o.insert("blackConnected".into(), m.black_connected.into());
    o.insert("graceMs".into(), m.grace_ms.into());
    o.insert("firstMoveMs".into(), m.first_move_ms.into());
    o.insert("startedAt".into(), m.started_at.into());
    o.insert("rematch".into(), m.rematch.to_u8().into());
    o.insert("autoPress".into(), m.auto_press.into());
    Value::Object(o)
}

fn game_snapshot_from_json(v: &Value) -> Option<GameSnapshot> {
    Some(GameSnapshot {
        game: uint(v, "game")?,
        gseq: uint(v, "gseq")?,
        category: v.get("category")?.as_str()?.to_owned(),
        base_ms: uint(v, "baseMs")?,
        inc_ms: uint(v, "incMs")?,
        rated: v.get("rated")?.as_bool()?,
        white: player_info_from_json(v.get("white")?)?,
        black: player_info_from_json(v.get("black")?)?,
        you: color_from(v.get("you")?)?,
        moves: v.get("moves")?.as_array()?.iter().map(move_rec_from_json).collect::<Option<Vec<_>>>()?,
        running: color_from(v.get("running")?)?,
        white_ms: uint(v, "whiteMs")?,
        black_ms: uint(v, "blackMs")?,
        server_time: v.get("serverTime")?.as_f64()?,
        draw_offer: color_from(v.get("drawOffer")?)?,
        status: game_status_from(v.get("status")?)?,
        reason: end_reason_from(v.get("reason")?)?,
        white_connected: v.get("whiteConnected")?.as_bool()?,
        black_connected: v.get("blackConnected")?.as_bool()?,
        grace_ms: uint(v, "graceMs")?,
        first_move_ms: uint(v, "firstMoveMs")?,
        started_at: v.get("startedAt")?.as_f64()?,
        rematch: color_from(v.get("rematch")?)?,
        auto_press: v.get("autoPress")?.as_bool()?,
    })
}

fn move_made_to_json(m: &MoveMade) -> Value {
    let mut o = Map::new();
    o.insert("game".into(), m.game.into());
    o.insert("gseq".into(), m.gseq.into());
    o.insert("ply".into(), m.ply.into());
    o.insert("move".into(), m.r#move.into());
    o.insert("flags".into(), m.flags.into());
    o.insert("spentMs".into(), m.spent_ms.into());
    o.insert("whiteMs".into(), m.white_ms.into());
    o.insert("blackMs".into(), m.black_ms.into());
    o.insert("serverTime".into(), m.server_time.into());
    o.insert("drawOffer".into(), m.draw_offer.into());
    o.insert("firstMoveMs".into(), m.first_move_ms.into());
    Value::Object(o)
}

fn move_made_from_json(v: &Value) -> Option<MoveMade> {
    Some(MoveMade {
        game: uint(v, "game")?,
        gseq: uint(v, "gseq")?,
        ply: uint(v, "ply")?,
        r#move: uint(v, "move")?,
        flags: uint(v, "flags")?,
        spent_ms: uint(v, "spentMs")?,
        white_ms: uint(v, "whiteMs")?,
        black_ms: uint(v, "blackMs")?,
        server_time: v.get("serverTime")?.as_f64()?,
        draw_offer: v.get("drawOffer")?.as_bool()?,
        first_move_ms: uint(v, "firstMoveMs")?,
    })
}

fn move_rejected_to_json(m: &MoveRejected) -> Value {
    let mut o = Map::new();
    o.insert("game".into(), m.game.into());
    o.insert("ply".into(), m.ply.into());
    o.insert("move".into(), m.r#move.into());
    o.insert("code".into(), m.code.to_u8().into());
    Value::Object(o)
}

fn move_rejected_from_json(v: &Value) -> Option<MoveRejected> {
    Some(MoveRejected {
        game: uint(v, "game")?,
        ply: uint(v, "ply")?,
        r#move: uint(v, "move")?,
        code: error_code_from(v.get("code")?)?,
    })
}

fn game_event_to_json(m: &GameEvent) -> Value {
    let mut o = Map::new();
    o.insert("game".into(), m.game.into());
    o.insert("gseq".into(), m.gseq.into());
    o.insert("kind".into(), m.kind.to_u8().into());
    o.insert("color".into(), m.color.to_u8().into());
    o.insert("arg".into(), m.arg.into());
    Value::Object(o)
}

fn game_event_from_json(v: &Value) -> Option<GameEvent> {
    Some(GameEvent {
        game: uint(v, "game")?,
        gseq: uint(v, "gseq")?,
        kind: game_event_kind_from(v.get("kind")?)?,
        color: color_from(v.get("color")?)?,
        arg: uint(v, "arg")?,
    })
}

fn game_end_to_json(m: &GameEnd) -> Value {
    let mut o = Map::new();
    o.insert("game".into(), m.game.into());
    o.insert("gseq".into(), m.gseq.into());
    o.insert("status".into(), m.status.to_u8().into());
    o.insert("reason".into(), m.reason.to_u8().into());
    o.insert("whiteMs".into(), m.white_ms.into());
    o.insert("blackMs".into(), m.black_ms.into());
    o.insert("serverTime".into(), m.server_time.into());
    Value::Object(o)
}

fn game_end_from_json(v: &Value) -> Option<GameEnd> {
    Some(GameEnd {
        game: uint(v, "game")?,
        gseq: uint(v, "gseq")?,
        status: game_status_from(v.get("status")?)?,
        reason: end_reason_from(v.get("reason")?)?,
        white_ms: uint(v, "whiteMs")?,
        black_ms: uint(v, "blackMs")?,
        server_time: v.get("serverTime")?.as_f64()?,
    })
}

fn rating_update_to_json(m: &RatingUpdate) -> Value {
    let mut o = Map::new();
    o.insert("game".into(), m.game.into());
    o.insert("category".into(), m.category.clone().into());
    o.insert("white".into(), rating_change_to_json(&m.white));
    o.insert("black".into(), rating_change_to_json(&m.black));
    Value::Object(o)
}

fn rating_update_from_json(v: &Value) -> Option<RatingUpdate> {
    Some(RatingUpdate {
        game: uint(v, "game")?,
        category: v.get("category")?.as_str()?.to_owned(),
        white: rating_change_from_json(v.get("white")?)?,
        black: rating_change_from_json(v.get("black")?)?,
    })
}

fn server_gesture_to_json(m: &ServerGesture) -> Value {
    let mut o = Map::new();
    o.insert("game".into(), m.game.into());
    o.insert("ply".into(), m.ply.into());
    o.insert("touch".into(), m.touch.into());
    o.insert("aim".into(), m.aim.into());
    o.insert("placed".into(), m.placed.into());
    o.insert("flags".into(), m.flags.into());
    o.insert("yaw".into(), m.yaw.into());
    o.insert("pitch".into(), m.pitch.into());
    o.insert("lean".into(), m.lean.into());
    Value::Object(o)
}

fn server_gesture_from_json(v: &Value) -> Option<ServerGesture> {
    Some(ServerGesture {
        game: uint(v, "game")?,
        ply: uint(v, "ply")?,
        touch: uint(v, "touch")?,
        aim: uint(v, "aim")?,
        placed: uint(v, "placed")?,
        flags: uint(v, "flags")?,
        yaw: int(v, "yaw")?,
        pitch: int(v, "pitch")?,
        lean: uint(v, "lean")?,
    })
}

/// The vector name and the JSON fields of a client message.
pub fn client_to_json(m: &ClientMsg) -> (&'static str, Value) {
    match m {
        ClientMsg::Hello(m) => ("Hello", hello_to_json(m)),
        ClientMsg::Ping(m) => ("C_Ping", client_ping_to_json(m)),
        ClientMsg::Pong(m) => ("C_Pong", client_pong_to_json(m)),
        ClientMsg::QueueJoin(m) => ("QueueJoin", queue_join_to_json(m)),
        ClientMsg::QueueLeave(m) => ("QueueLeave", queue_leave_to_json(m)),
        ClientMsg::ChallengeCreate(m) => ("ChallengeCreate", challenge_create_to_json(m)),
        ClientMsg::ChallengeAccept(m) => ("ChallengeAccept", challenge_accept_to_json(m)),
        ClientMsg::ChallengeDecline(m) => ("ChallengeDecline", challenge_decline_to_json(m)),
        ClientMsg::ChallengeCancel(m) => ("ChallengeCancel", challenge_cancel_to_json(m)),
        ClientMsg::ChallengeJoinCode(m) => ("ChallengeJoinCode", challenge_join_code_to_json(m)),
        ClientMsg::Move(m) => ("Move", move_to_json(m)),
        ClientMsg::Resign(m) => ("Resign", resign_to_json(m)),
        ClientMsg::DrawOffer(m) => ("DrawOffer", draw_offer_to_json(m)),
        ClientMsg::DrawAnswer(m) => ("DrawAnswer", draw_answer_to_json(m)),
        ClientMsg::DrawClaim(m) => ("DrawClaim", draw_claim_to_json(m)),
        ClientMsg::Abort(m) => ("Abort", abort_to_json(m)),
        ClientMsg::Resync(m) => ("Resync", resync_to_json(m)),
        ClientMsg::Rematch(m) => ("Rematch", rematch_to_json(m)),
        ClientMsg::Gesture(m) => ("C_Gesture", client_gesture_to_json(m)),
    }
}

/// The client message of a vector name and JSON fields.
pub fn client_from_json(key: &str, v: &Value) -> Option<ClientMsg> {
    Some(match key {
        "Hello" => ClientMsg::Hello(hello_from_json(v)?),
        "C_Ping" => ClientMsg::Ping(client_ping_from_json(v)?),
        "C_Pong" => ClientMsg::Pong(client_pong_from_json(v)?),
        "QueueJoin" => ClientMsg::QueueJoin(queue_join_from_json(v)?),
        "QueueLeave" => ClientMsg::QueueLeave(queue_leave_from_json(v)?),
        "ChallengeCreate" => ClientMsg::ChallengeCreate(challenge_create_from_json(v)?),
        "ChallengeAccept" => ClientMsg::ChallengeAccept(challenge_accept_from_json(v)?),
        "ChallengeDecline" => ClientMsg::ChallengeDecline(challenge_decline_from_json(v)?),
        "ChallengeCancel" => ClientMsg::ChallengeCancel(challenge_cancel_from_json(v)?),
        "ChallengeJoinCode" => ClientMsg::ChallengeJoinCode(challenge_join_code_from_json(v)?),
        "Move" => ClientMsg::Move(move_from_json(v)?),
        "Resign" => ClientMsg::Resign(resign_from_json(v)?),
        "DrawOffer" => ClientMsg::DrawOffer(draw_offer_from_json(v)?),
        "DrawAnswer" => ClientMsg::DrawAnswer(draw_answer_from_json(v)?),
        "DrawClaim" => ClientMsg::DrawClaim(draw_claim_from_json(v)?),
        "Abort" => ClientMsg::Abort(abort_from_json(v)?),
        "Resync" => ClientMsg::Resync(resync_from_json(v)?),
        "Rematch" => ClientMsg::Rematch(rematch_from_json(v)?),
        "C_Gesture" => ClientMsg::Gesture(client_gesture_from_json(v)?),
        _ => return None,
    })
}

/// The vector name and the JSON fields of a server message.
pub fn server_to_json(m: &ServerMsg) -> (&'static str, Value) {
    match m {
        ServerMsg::Welcome(m) => ("Welcome", welcome_to_json(m)),
        ServerMsg::Error(m) => ("Error", error_to_json(m)),
        ServerMsg::Ping(m) => ("S_Ping", server_ping_to_json(m)),
        ServerMsg::Pong(m) => ("S_Pong", server_pong_to_json(m)),
        ServerMsg::Ack(m) => ("Ack", ack_to_json(m)),
        ServerMsg::Notice(m) => ("Notice", notice_to_json(m)),
        ServerMsg::QueueStatus(m) => ("QueueStatus", queue_status_to_json(m)),
        ServerMsg::ChallengeReceived(m) => ("ChallengeReceived", challenge_received_to_json(m)),
        ServerMsg::ChallengeStatus(m) => ("ChallengeStatus", challenge_status_to_json(m)),
        ServerMsg::GameSnapshot(m) => ("GameSnapshot", game_snapshot_to_json(m)),
        ServerMsg::MoveMade(m) => ("MoveMade", move_made_to_json(m)),
        ServerMsg::MoveRejected(m) => ("MoveRejected", move_rejected_to_json(m)),
        ServerMsg::GameEvent(m) => ("GameEvent", game_event_to_json(m)),
        ServerMsg::GameEnd(m) => ("GameEnd", game_end_to_json(m)),
        ServerMsg::RatingUpdate(m) => ("RatingUpdate", rating_update_to_json(m)),
        ServerMsg::Gesture(m) => ("S_Gesture", server_gesture_to_json(m)),
    }
}

/// The server message of a vector name and JSON fields.
pub fn server_from_json(key: &str, v: &Value) -> Option<ServerMsg> {
    Some(match key {
        "Welcome" => ServerMsg::Welcome(welcome_from_json(v)?),
        "Error" => ServerMsg::Error(error_from_json(v)?),
        "S_Ping" => ServerMsg::Ping(server_ping_from_json(v)?),
        "S_Pong" => ServerMsg::Pong(server_pong_from_json(v)?),
        "Ack" => ServerMsg::Ack(ack_from_json(v)?),
        "Notice" => ServerMsg::Notice(notice_from_json(v)?),
        "QueueStatus" => ServerMsg::QueueStatus(queue_status_from_json(v)?),
        "ChallengeReceived" => ServerMsg::ChallengeReceived(challenge_received_from_json(v)?),
        "ChallengeStatus" => ServerMsg::ChallengeStatus(challenge_status_from_json(v)?),
        "GameSnapshot" => ServerMsg::GameSnapshot(game_snapshot_from_json(v)?),
        "MoveMade" => ServerMsg::MoveMade(move_made_from_json(v)?),
        "MoveRejected" => ServerMsg::MoveRejected(move_rejected_from_json(v)?),
        "GameEvent" => ServerMsg::GameEvent(game_event_from_json(v)?),
        "GameEnd" => ServerMsg::GameEnd(game_end_from_json(v)?),
        "RatingUpdate" => ServerMsg::RatingUpdate(rating_update_from_json(v)?),
        "S_Gesture" => ServerMsg::Gesture(server_gesture_from_json(v)?),
        _ => return None,
    })
}

