// Scacelith realtime protocol codec: GENERATED by tools/gen-protocol.js from src/protocol/schema.js,
// do not edit. Change schema.js and run `npm run gen:protocol` (CI runs it with --check).
//
// API (docs/DESIGN.md section 5.1): MSG, encode.<Name>(fields) -> Buffer, decode(buf, { dir }),
// ProtocolError{reason}, PROTOCOL_VERSION, PROTOCOL_MIN, WS_SUBPROTOCOL, SCHEMA_HASH, enums,
// MoveFlag, CloseCode, isClientType, messageName. Wire format and validation rules:
// docs/PROTOCOL.md. Every function below is straight-line code specialised for one message:
// fixed parts at constant offsets, one bounds check per run of fixed-size fields, exact-size
// allocation on encode. Encoding validates like decoding, so the server cannot emit a frame
// that a client refuses.
/* eslint-disable */

export const PROTOCOL_VERSION = 2;
export const PROTOCOL_MIN = 2;
export const WS_SUBPROTOCOL = 'scacelith.v1';
export const SCHEMA_HASH = 0x77977684;

export const enums = Object.freeze({
    Color: Object.freeze({ White: 0, Black: 1, None: 2 }),
    ColorPref: Object.freeze({ Random: 0, White: 1, Black: 2 }),
    GameStatus: Object.freeze({ Ongoing: 0, WhiteWins: 1, BlackWins: 2, Draw: 3, Aborted: 4 }),
    EndReason: Object.freeze({
        None: 0, Checkmate: 1, Resignation: 2, Timeout: 3, IllegalMoves: 4, Stalemate: 5,
        InsufficientMaterial: 6, TimeoutVsInsufficient: 7, FivefoldRepetition: 8, SeventyFiveMoves: 9,
        ThreefoldClaim: 10, FiftyMoveClaim: 11, Agreement: 12, IllegalMovesVsInsufficient: 13,
        Abandonment: 20, AbandonmentVsInsufficient: 21, Aborted: 22, NoShow: 23, Forfeit: 24,
        ServerAborted: 25, BothDisconnected: 26,
    }),
    GameEventKind: Object.freeze({
        DrawOffered: 1, DrawDeclined: 2, PlayerDisconnected: 3, PlayerReconnected: 4, RematchOffered: 5,
        RematchDeclined: 6, AbortAvailable: 7,
    }),
    QueueState: Object.freeze({ Left: 0, Searching: 1, Matched: 2 }),
    ChallengeState: Object.freeze({ Pending: 0, Accepted: 1, Declined: 2, Cancelled: 3, Expired: 4, Unavailable: 5 }),
    NoticeCode: Object.freeze({
        ServerShutdown: 1, Banned: 2, SessionRevoked: 3, MatchmakingCooldown: 4, ReplacedByNewConnection: 5,
        Motd: 6, RatingRestored: 7,
    }),
    ErrorCode: Object.freeze({
        Malformed: 1, UnsupportedProtocol: 2, Unauthorized: 3, Banned: 4, RateLimited: 5, ServerFull: 6,
        Replaced: 7, ShuttingDown: 8, Internal: 9, HelloRequired: 10, EmailUnverified: 11, NotInGame: 100,
        NotYourTurn: 101, IllegalMove: 102, StalePly: 103, Desync: 104, GameOver: 105, AlreadyInGame: 106,
        InvalidCategory: 107, DrawOfferLimit: 108, NothingToClaim: 109, AbortNotAllowed: 110,
        NoPendingOffer: 111, FlagFell: 112, QueueNotAllowed: 200, ChallengeNotFound: 201,
        UserUnavailable: 202, ChallengeLimit: 203, CannotChallengeSelf: 204, CodeInvalid: 205,
        RatedRequiresOfficialTc: 206, MatchmakingCooldown: 207, InvalidTimeControl: 208,
        RematchUnavailable: 209, ProtocolViolation: 240, Flood: 241, CheatDetected: 242, SlowConsumer: 243,
    }),
});
export const MoveFlag = Object.freeze({
    Capture: 1, EnPassant: 2, CastleKing: 4, CastleQueen: 8, DoublePush: 16, Promotion: 32, Check: 64,
    Mate: 128,
});
export const GestureFlag = Object.freeze({ Glance: 1, Promoting: 2, Side: 4 });
export const CloseCode = Object.freeze({
    Normal: 1000, GoingAway: 1001, ProtocolError: 1002, Unsupported: 1003, Policy: 1008, TooBig: 1009,
    Internal: 1011, UnsupportedProtocol: 4002, Unauthorized: 4003, Banned: 4004, Replaced: 4007,
    ShuttingDown: 4008, HelloTimeout: 4010, ProtocolViolation: 4300, Flood: 4301, CheatDetected: 4302,
    SlowConsumer: 4303,
});

export const MSG = Object.freeze({
    Hello: 0x01,
    C_Ping: 0x02,
    C_Pong: 0x03,
    QueueJoin: 0x10,
    QueueLeave: 0x11,
    ChallengeCreate: 0x12,
    ChallengeAccept: 0x13,
    ChallengeDecline: 0x14,
    ChallengeCancel: 0x15,
    ChallengeJoinCode: 0x16,
    Move: 0x20,
    Resign: 0x21,
    DrawOffer: 0x22,
    DrawAnswer: 0x23,
    DrawClaim: 0x24,
    Abort: 0x25,
    Resync: 0x26,
    Rematch: 0x27,
    C_Gesture: 0x28,
    Welcome: 0x80,
    Error: 0x81,
    S_Ping: 0x82,
    S_Pong: 0x83,
    Ack: 0x84,
    Notice: 0x85,
    QueueStatus: 0x90,
    ChallengeReceived: 0x91,
    ChallengeStatus: 0x92,
    GameSnapshot: 0xA0,
    MoveMade: 0xA1,
    MoveRejected: 0xA2,
    GameEvent: 0xA3,
    GameEnd: 0xA4,
    RatingUpdate: 0xA5,
    S_Gesture: 0xA6,
});

// ---- run-time helpers ----

/** Malformed message or value that cannot be encoded; `reason` says which rule failed. */
export class ProtocolError extends Error {
    constructor(reason) { super(`protocol: ${reason}`); this.reason = reason; }
}
ProtocolError.prototype.name = 'ProtocolError';

// Decoding errors carry no stack trace (the reason says everything, and capturing a stack costs
// more than decoding the message); encoding errors keep theirs (they are server bugs).
const TRIM_STACK = (() => {
    const d = Object.getOwnPropertyDescriptor(Error, 'stackTraceLimit');
    return !!d && d.writable === true && !Object.isFrozen(Error);
})();
function fail(reason) {
    if (TRIM_STACK) {
        const keep = Error.stackTraceLimit;
        Error.stackTraceLimit = 0;
        const e = new ProtocolError(reason);
        Error.stackTraceLimit = keep;
        throw e;
    }
    throw new ProtocolError(reason);
}
function efail(reason) { throw new ProtocolError(reason); }

const NO_OBJ = Object.freeze({});
const NO_ARR = Object.freeze([]);
const utf8 = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true });
const F64 = new Float64Array(1);
const F8 = new Uint8Array(F64.buffer);
const LE = new Uint8Array(new Uint16Array([1]).buffer)[0] === 1;

function rf64(b, o) {
    if (LE) { F8[0] = b[o]; F8[1] = b[o + 1]; F8[2] = b[o + 2]; F8[3] = b[o + 3]; F8[4] = b[o + 4]; F8[5] = b[o + 5]; F8[6] = b[o + 6]; F8[7] = b[o + 7]; }
    else { F8[7] = b[o]; F8[6] = b[o + 1]; F8[5] = b[o + 2]; F8[4] = b[o + 3]; F8[3] = b[o + 4]; F8[2] = b[o + 5]; F8[1] = b[o + 6]; F8[0] = b[o + 7]; }
    return F64[0];
}
function wf64(b, o, v) {
    F64[0] = v;
    if (LE) { b[o] = F8[0]; b[o + 1] = F8[1]; b[o + 2] = F8[2]; b[o + 3] = F8[3]; b[o + 4] = F8[4]; b[o + 5] = F8[5]; b[o + 6] = F8[6]; b[o + 7] = F8[7]; }
    else { b[o] = F8[7]; b[o + 1] = F8[6]; b[o + 2] = F8[5]; b[o + 3] = F8[4]; b[o + 4] = F8[3]; b[o + 5] = F8[2]; b[o + 6] = F8[1]; b[o + 7] = F8[0]; }
}

// str8 payload b[s..e): no NUL, valid UTF-8 (fatal; a BOM is kept). ASCII takes the fast path.
function rstr(b, s, e, name) {
    let acc = 0;
    for (let i = s; i < e; i++) {
        const c = b[i];
        if (c === 0) fail(name + ' contains NUL');
        acc |= c;
    }
    if (acc < 0x80) return b.latin1Slice(s, e);
    try { return utf8.decode(b.subarray(s, e)); } catch { return fail(name + ' not UTF-8'); }
}

// UTF-8 byte length of a string as Buffer writes it (lone surrogates: 3 bytes), -1 if it has a NUL.
function slen(s) {
    const n = s.length;
    let len = n;
    for (let i = 0; i < n; i++) {
        const c = s.charCodeAt(i);
        if (c < 0x80) { if (c === 0) return -1; continue; }
        if (c < 0x800) len += 1;
        else if ((c & 0xfc00) === 0xd800 && i + 1 < n && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) { len += 2; i++; }
        else len += 2;
    }
    return len;
}
function wstr(b, o, s, len) {
    if (len === s.length) { for (let i = 0; i < len; i++) b[o + i] = s.charCodeAt(i); }
    else b.write(s, o, len, 'utf8');
}

function toBuffer(x) {
    if (!x) fail('empty');
    if (x instanceof Uint8Array) return Buffer.from(x.buffer, x.byteOffset, x.byteLength);
    if (x instanceof ArrayBuffer) return Buffer.from(x);
    return fail('not a buffer');
}

// Membership tables of the enums whose values are not contiguous.
function set8(values) { const t = new Uint8Array(256); for (const v of values) t[v] = 1; return t; }
const EN_EndReason = set8([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 20, 21, 22, 23, 24, 25, 26]);
const EN_ErrorCode = set8([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 240, 241, 242, 243]);

// Direction of each type byte: 0 unknown, 1 client->server, 2 server->client.
const DIR = new Uint8Array(256);
const NAMES = new Array(256).fill(null);
DIR[0x01] = 1; NAMES[0x01] = 'Hello';
DIR[0x02] = 1; NAMES[0x02] = 'C_Ping';
DIR[0x03] = 1; NAMES[0x03] = 'C_Pong';
DIR[0x10] = 1; NAMES[0x10] = 'QueueJoin';
DIR[0x11] = 1; NAMES[0x11] = 'QueueLeave';
DIR[0x12] = 1; NAMES[0x12] = 'ChallengeCreate';
DIR[0x13] = 1; NAMES[0x13] = 'ChallengeAccept';
DIR[0x14] = 1; NAMES[0x14] = 'ChallengeDecline';
DIR[0x15] = 1; NAMES[0x15] = 'ChallengeCancel';
DIR[0x16] = 1; NAMES[0x16] = 'ChallengeJoinCode';
DIR[0x20] = 1; NAMES[0x20] = 'Move';
DIR[0x21] = 1; NAMES[0x21] = 'Resign';
DIR[0x22] = 1; NAMES[0x22] = 'DrawOffer';
DIR[0x23] = 1; NAMES[0x23] = 'DrawAnswer';
DIR[0x24] = 1; NAMES[0x24] = 'DrawClaim';
DIR[0x25] = 1; NAMES[0x25] = 'Abort';
DIR[0x26] = 1; NAMES[0x26] = 'Resync';
DIR[0x27] = 1; NAMES[0x27] = 'Rematch';
DIR[0x28] = 1; NAMES[0x28] = 'C_Gesture';
DIR[0x80] = 2; NAMES[0x80] = 'Welcome';
DIR[0x81] = 2; NAMES[0x81] = 'Error';
DIR[0x82] = 2; NAMES[0x82] = 'S_Ping';
DIR[0x83] = 2; NAMES[0x83] = 'S_Pong';
DIR[0x84] = 2; NAMES[0x84] = 'Ack';
DIR[0x85] = 2; NAMES[0x85] = 'Notice';
DIR[0x90] = 2; NAMES[0x90] = 'QueueStatus';
DIR[0x91] = 2; NAMES[0x91] = 'ChallengeReceived';
DIR[0x92] = 2; NAMES[0x92] = 'ChallengeStatus';
DIR[0xA0] = 2; NAMES[0xA0] = 'GameSnapshot';
DIR[0xA1] = 2; NAMES[0xA1] = 'MoveMade';
DIR[0xA2] = 2; NAMES[0xA2] = 'MoveRejected';
DIR[0xA3] = 2; NAMES[0xA3] = 'GameEvent';
DIR[0xA4] = 2; NAMES[0xA4] = 'GameEnd';
DIR[0xA5] = 2; NAMES[0xA5] = 'RatingUpdate';
DIR[0xA6] = 2; NAMES[0xA6] = 'S_Gesture';

/** True for client->server type bytes (0x01-0x7F). */
export function isClientType(t) { return t >= 0x01 && t <= 0x7f; }

/** Name of a message type as used in MSG and encode (C_/S_ prefixes for shared names), or null. */
export function messageName(type) { return typeof type === 'number' ? NAMES[type] ?? null : null; }

// ---- encoders ----

// 0x01 Hello (c2s)
function e_Hello(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.proto;
    const v3 = m.schema;
    const v4 = m.client ?? '';
    if (typeof v4 !== 'string') efail('client not a string');
    const L5 = slen(v4);
    if (L5 < 0) efail('client contains NUL');
    if (L5 > 48) efail('client bad length');
    const v6 = m.token ?? '';
    if (typeof v6 !== 'string') efail('token not a string');
    const L7 = slen(v6);
    if (L7 < 0) efail('token contains NUL');
    if (L7 > 160 || L7 < 16) efail('token bad length');
    const b = Buffer.allocUnsafe(13 + L5 + L7);
    b[0] = 0x01;
    let o = 0;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v2 & 65535) !== v2) efail('proto out of range');
    b[5] = v2; b[6] = v2 >>> 8;
    if ((v3 >>> 0) !== v3) efail('schema out of range');
    b[7] = v3; b[8] = v3 >>> 8; b[9] = v3 >>> 16; b[10] = v3 >>> 24;
    b[11] = L5;
    o = 12;
    if (L5 !== 0) { wstr(b, o, v4, L5); o += L5; }
    b[o] = L7;
    o += 1;
    if (L7 !== 0) { wstr(b, o, v6, L7); o += L7; }
    return b;
}

// 0x02 C_Ping (c2s)
function e_C_Ping(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.nonce;
    const b = Buffer.allocUnsafe(9);
    b[0] = 0x02;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v2 >>> 0) !== v2) efail('nonce out of range');
    b[5] = v2; b[6] = v2 >>> 8; b[7] = v2 >>> 16; b[8] = v2 >>> 24;
    return b;
}

// 0x03 C_Pong (c2s)
function e_C_Pong(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.nonce;
    const b = Buffer.allocUnsafe(9);
    b[0] = 0x03;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v2 >>> 0) !== v2) efail('nonce out of range');
    b[5] = v2; b[6] = v2 >>> 8; b[7] = v2 >>> 16; b[8] = v2 >>> 24;
    return b;
}

// 0x10 QueueJoin (c2s)
function e_QueueJoin(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.category ?? '';
    if (typeof v2 !== 'string') efail('category not a string');
    const L3 = slen(v2);
    if (L3 < 0) efail('category contains NUL');
    if (L3 > 7 || L3 < 3) efail('category bad length');
    const v4 = m.rated;
    const b = Buffer.allocUnsafe(7 + L3);
    b[0] = 0x10;
    let o = 0;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    b[5] = L3;
    o = 6;
    if (L3 !== 0) { wstr(b, o, v2, L3); o += L3; }
    b[o] = v4 ? 1 : 0;
    return b;
}

// 0x11 QueueLeave (c2s)
function e_QueueLeave(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const b = Buffer.allocUnsafe(5);
    b[0] = 0x11;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    return b;
}

// 0x12 ChallengeCreate (c2s)
function e_ChallengeCreate(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.target ?? '';
    if (typeof v2 !== 'string') efail('target not a string');
    const L3 = slen(v2);
    if (L3 < 0) efail('target contains NUL');
    if (L3 > 24) efail('target bad length');
    const v4 = m.baseSec;
    const v5 = m.incSec;
    const v6 = m.rated;
    const v7 = m.color;
    const b = Buffer.allocUnsafe(11 + L3);
    b[0] = 0x12;
    let o = 0;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    b[5] = L3;
    o = 6;
    if (L3 !== 0) { wstr(b, o, v2, L3); o += L3; }
    if ((v4 & 65535) !== v4) efail('baseSec out of range');
    if (v4 < 15) efail('baseSec below min');
    if (v4 > 10800) efail('baseSec above max');
    b[o] = v4; b[o + 1] = v4 >>> 8;
    if ((v5 & 255) !== v5) efail('incSec out of range');
    if (v5 > 180) efail('incSec above max');
    b[o + 2] = v5;
    b[o + 3] = v6 ? 1 : 0;
    if ((v7 & 255) !== v7 || v7 > 2) efail('color not a ColorPref');
    b[o + 4] = v7;
    return b;
}

// 0x13 ChallengeAccept (c2s)
function e_ChallengeAccept(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.id;
    const b = Buffer.allocUnsafe(9);
    b[0] = 0x13;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v2 >>> 0) !== v2) efail('id out of range');
    b[5] = v2; b[6] = v2 >>> 8; b[7] = v2 >>> 16; b[8] = v2 >>> 24;
    return b;
}

// 0x14 ChallengeDecline (c2s)
function e_ChallengeDecline(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.id;
    const b = Buffer.allocUnsafe(9);
    b[0] = 0x14;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v2 >>> 0) !== v2) efail('id out of range');
    b[5] = v2; b[6] = v2 >>> 8; b[7] = v2 >>> 16; b[8] = v2 >>> 24;
    return b;
}

// 0x15 ChallengeCancel (c2s)
function e_ChallengeCancel(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.id;
    const b = Buffer.allocUnsafe(9);
    b[0] = 0x15;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v2 >>> 0) !== v2) efail('id out of range');
    b[5] = v2; b[6] = v2 >>> 8; b[7] = v2 >>> 16; b[8] = v2 >>> 24;
    return b;
}

// 0x16 ChallengeJoinCode (c2s)
function e_ChallengeJoinCode(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.code ?? '';
    if (typeof v2 !== 'string') efail('code not a string');
    const L3 = slen(v2);
    if (L3 < 0) efail('code contains NUL');
    if (L3 > 12 || L3 < 4) efail('code bad length');
    const b = Buffer.allocUnsafe(6 + L3);
    b[0] = 0x16;
    let o = 0;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    b[5] = L3;
    o = 6;
    if (L3 !== 0) { wstr(b, o, v2, L3); o += L3; }
    return b;
}

// 0x20 Move (c2s)
function e_Move(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const v3 = m.ply;
    const v4 = m.move;
    const v5 = m.posHash;
    const v6 = m.thinkMs;
    const v7 = m.drawOffer;
    const b = Buffer.allocUnsafe(26);
    b[0] = 0x20;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g8 = v2 || 0;
    if (!Number.isSafeInteger(g8) || g8 < 0) efail('game not an id53');
    const lo9 = g8 >>> 0, hi10 = (g8 - lo9) / 4294967296;
    b[5] = lo9; b[6] = lo9 >>> 8; b[7] = lo9 >>> 16; b[8] = lo9 >>> 24;
    b[9] = hi10; b[10] = hi10 >>> 8; b[11] = hi10 >>> 16; b[12] = hi10 >>> 24;
    if ((v3 & 65535) !== v3) efail('ply out of range');
    if (v3 > 1199) efail('ply above max');
    b[13] = v3; b[14] = v3 >>> 8;
    if ((v4 & 65535) !== v4) efail('move out of range');
    if (v4 > 32767) efail('move above max');
    b[15] = v4; b[16] = v4 >>> 8;
    if ((v5 >>> 0) !== v5) efail('posHash out of range');
    b[17] = v5; b[18] = v5 >>> 8; b[19] = v5 >>> 16; b[20] = v5 >>> 24;
    if ((v6 >>> 0) !== v6) efail('thinkMs out of range');
    b[21] = v6; b[22] = v6 >>> 8; b[23] = v6 >>> 16; b[24] = v6 >>> 24;
    b[25] = v7 ? 1 : 0;
    return b;
}

// 0x21 Resign (c2s)
function e_Resign(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const b = Buffer.allocUnsafe(13);
    b[0] = 0x21;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g3 = v2 || 0;
    if (!Number.isSafeInteger(g3) || g3 < 0) efail('game not an id53');
    const lo4 = g3 >>> 0, hi5 = (g3 - lo4) / 4294967296;
    b[5] = lo4; b[6] = lo4 >>> 8; b[7] = lo4 >>> 16; b[8] = lo4 >>> 24;
    b[9] = hi5; b[10] = hi5 >>> 8; b[11] = hi5 >>> 16; b[12] = hi5 >>> 24;
    return b;
}

// 0x22 DrawOffer (c2s)
function e_DrawOffer(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const b = Buffer.allocUnsafe(13);
    b[0] = 0x22;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g3 = v2 || 0;
    if (!Number.isSafeInteger(g3) || g3 < 0) efail('game not an id53');
    const lo4 = g3 >>> 0, hi5 = (g3 - lo4) / 4294967296;
    b[5] = lo4; b[6] = lo4 >>> 8; b[7] = lo4 >>> 16; b[8] = lo4 >>> 24;
    b[9] = hi5; b[10] = hi5 >>> 8; b[11] = hi5 >>> 16; b[12] = hi5 >>> 24;
    return b;
}

// 0x23 DrawAnswer (c2s)
function e_DrawAnswer(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const v3 = m.accept;
    const b = Buffer.allocUnsafe(14);
    b[0] = 0x23;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g4 = v2 || 0;
    if (!Number.isSafeInteger(g4) || g4 < 0) efail('game not an id53');
    const lo5 = g4 >>> 0, hi6 = (g4 - lo5) / 4294967296;
    b[5] = lo5; b[6] = lo5 >>> 8; b[7] = lo5 >>> 16; b[8] = lo5 >>> 24;
    b[9] = hi6; b[10] = hi6 >>> 8; b[11] = hi6 >>> 16; b[12] = hi6 >>> 24;
    b[13] = v3 ? 1 : 0;
    return b;
}

// 0x24 DrawClaim (c2s)
function e_DrawClaim(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const b = Buffer.allocUnsafe(13);
    b[0] = 0x24;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g3 = v2 || 0;
    if (!Number.isSafeInteger(g3) || g3 < 0) efail('game not an id53');
    const lo4 = g3 >>> 0, hi5 = (g3 - lo4) / 4294967296;
    b[5] = lo4; b[6] = lo4 >>> 8; b[7] = lo4 >>> 16; b[8] = lo4 >>> 24;
    b[9] = hi5; b[10] = hi5 >>> 8; b[11] = hi5 >>> 16; b[12] = hi5 >>> 24;
    return b;
}

// 0x25 Abort (c2s)
function e_Abort(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const b = Buffer.allocUnsafe(13);
    b[0] = 0x25;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g3 = v2 || 0;
    if (!Number.isSafeInteger(g3) || g3 < 0) efail('game not an id53');
    const lo4 = g3 >>> 0, hi5 = (g3 - lo4) / 4294967296;
    b[5] = lo4; b[6] = lo4 >>> 8; b[7] = lo4 >>> 16; b[8] = lo4 >>> 24;
    b[9] = hi5; b[10] = hi5 >>> 8; b[11] = hi5 >>> 16; b[12] = hi5 >>> 24;
    return b;
}

// 0x26 Resync (c2s)
function e_Resync(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const b = Buffer.allocUnsafe(13);
    b[0] = 0x26;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g3 = v2 || 0;
    if (!Number.isSafeInteger(g3) || g3 < 0) efail('game not an id53');
    const lo4 = g3 >>> 0, hi5 = (g3 - lo4) / 4294967296;
    b[5] = lo4; b[6] = lo4 >>> 8; b[7] = lo4 >>> 16; b[8] = lo4 >>> 24;
    b[9] = hi5; b[10] = hi5 >>> 8; b[11] = hi5 >>> 16; b[12] = hi5 >>> 24;
    return b;
}

// 0x27 Rematch (c2s)
function e_Rematch(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const v3 = m.accept;
    const b = Buffer.allocUnsafe(14);
    b[0] = 0x27;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g4 = v2 || 0;
    if (!Number.isSafeInteger(g4) || g4 < 0) efail('game not an id53');
    const lo5 = g4 >>> 0, hi6 = (g4 - lo5) / 4294967296;
    b[5] = lo5; b[6] = lo5 >>> 8; b[7] = lo5 >>> 16; b[8] = lo5 >>> 24;
    b[9] = hi6; b[10] = hi6 >>> 8; b[11] = hi6 >>> 16; b[12] = hi6 >>> 24;
    b[13] = v3 ? 1 : 0;
    return b;
}

// 0x28 C_Gesture (c2s)
function e_C_Gesture(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.seq;
    const v2 = m.game;
    const v3 = m.ply;
    const v4 = m.touch;
    const v5 = m.aim;
    const v6 = m.placed;
    const v7 = m.flags;
    const v8 = m.yaw;
    const v9 = m.pitch;
    const v10 = m.lean;
    const b = Buffer.allocUnsafe(29);
    b[0] = 0x28;
    if ((v1 >>> 0) !== v1) efail('seq out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const g11 = v2 || 0;
    if (!Number.isSafeInteger(g11) || g11 < 0) efail('game not an id53');
    const lo12 = g11 >>> 0, hi13 = (g11 - lo12) / 4294967296;
    b[5] = lo12; b[6] = lo12 >>> 8; b[7] = lo12 >>> 16; b[8] = lo12 >>> 24;
    b[9] = hi13; b[10] = hi13 >>> 8; b[11] = hi13 >>> 16; b[12] = hi13 >>> 24;
    if ((v3 & 65535) !== v3) efail('ply out of range');
    if (v3 > 1199) efail('ply above max');
    b[13] = v3; b[14] = v3 >>> 8;
    if ((v4 & 255) !== v4) efail('touch out of range');
    if (v4 > 64) efail('touch above max');
    b[15] = v4;
    if ((v5 & 255) !== v5) efail('aim out of range');
    if (v5 > 64) efail('aim above max');
    b[16] = v5;
    if ((v6 & 65535) !== v6) efail('placed out of range');
    if (v6 > 32767) efail('placed above max');
    b[17] = v6; b[18] = v6 >>> 8;
    if ((v7 & 255) !== v7) efail('flags out of range');
    if (v7 > 7) efail('flags above max');
    b[19] = v7;
    if ((v8 | 0) !== v8) efail('yaw out of range');
    if (v8 < -3142) efail('yaw below min');
    if (v8 > 3142) efail('yaw above max');
    b[20] = v8; b[21] = v8 >>> 8; b[22] = v8 >>> 16; b[23] = v8 >>> 24;
    if ((v9 | 0) !== v9) efail('pitch out of range');
    if (v9 < -1571) efail('pitch below min');
    if (v9 > 1571) efail('pitch above max');
    b[24] = v9; b[25] = v9 >>> 8; b[26] = v9 >>> 16; b[27] = v9 >>> 24;
    if ((v10 & 255) !== v10) efail('lean out of range');
    if (v10 > 100) efail('lean above max');
    b[28] = v10;
    return b;
}

// 0x80 Welcome (s2c)
function e_Welcome(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.proto;
    const v2 = m.serverTime;
    const v3 = m.userId;
    const v4 = m.username ?? '';
    if (typeof v4 !== 'string') efail('username not a string');
    const L5 = slen(v4);
    if (L5 < 0) efail('username contains NUL');
    if (L5 > 24) efail('username bad length');
    const v6 = m.serverName ?? '';
    if (typeof v6 !== 'string') efail('serverName not a string');
    const L7 = slen(v6);
    if (L7 < 0) efail('serverName contains NUL');
    if (L7 > 64) efail('serverName bad length');
    const v8 = m.heartbeatMs;
    const v9 = m.clientPingMs;
    const v10 = m.maxMsgPerSec;
    const v11 = m.activeGame;
    const v12 = m.gestureRate;
    const v13 = m.gestureBurst;
    const b = Buffer.allocUnsafe(39 + L5 + L7);
    b[0] = 0x80;
    let o = 0;
    if ((v1 & 65535) !== v1) efail('proto out of range');
    b[1] = v1; b[2] = v1 >>> 8;
    const d14 = Number(v2) || 0;
    if (d14 - d14 !== 0) efail('serverTime not finite');
    wf64(b, 3, d14);
    if ((v3 >>> 0) !== v3) efail('userId out of range');
    b[11] = v3; b[12] = v3 >>> 8; b[13] = v3 >>> 16; b[14] = v3 >>> 24;
    b[15] = L5;
    o = 16;
    if (L5 !== 0) { wstr(b, o, v4, L5); o += L5; }
    b[o] = L7;
    o += 1;
    if (L7 !== 0) { wstr(b, o, v6, L7); o += L7; }
    if ((v8 >>> 0) !== v8) efail('heartbeatMs out of range');
    b[o] = v8; b[o + 1] = v8 >>> 8; b[o + 2] = v8 >>> 16; b[o + 3] = v8 >>> 24;
    if ((v9 >>> 0) !== v9) efail('clientPingMs out of range');
    b[o + 4] = v9; b[o + 5] = v9 >>> 8; b[o + 6] = v9 >>> 16; b[o + 7] = v9 >>> 24;
    if ((v10 & 65535) !== v10) efail('maxMsgPerSec out of range');
    b[o + 8] = v10; b[o + 9] = v10 >>> 8;
    const g15 = v11 || 0;
    if (!Number.isSafeInteger(g15) || g15 < 0) efail('activeGame not an id53');
    const lo16 = g15 >>> 0, hi17 = (g15 - lo16) / 4294967296;
    b[o + 10] = lo16; b[o + 11] = lo16 >>> 8; b[o + 12] = lo16 >>> 16; b[o + 13] = lo16 >>> 24;
    b[o + 14] = hi17; b[o + 15] = hi17 >>> 8; b[o + 16] = hi17 >>> 16; b[o + 17] = hi17 >>> 24;
    if ((v12 & 65535) !== v12) efail('gestureRate out of range');
    if (v12 > 60) efail('gestureRate above max');
    b[o + 18] = v12; b[o + 19] = v12 >>> 8;
    if ((v13 & 65535) !== v13) efail('gestureBurst out of range');
    if (v13 > 120) efail('gestureBurst above max');
    b[o + 20] = v13; b[o + 21] = v13 >>> 8;
    return b;
}

// 0x81 Error (s2c)
function e_Error(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.ref;
    const v2 = m.code;
    const v3 = m.fatal;
    const v4 = m.game;
    const b = Buffer.allocUnsafe(15);
    b[0] = 0x81;
    if ((v1 >>> 0) !== v1) efail('ref out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v2 & 255) !== v2 || EN_ErrorCode[v2] === 0) efail('code not a ErrorCode');
    b[5] = v2;
    b[6] = v3 ? 1 : 0;
    const g5 = v4 || 0;
    if (!Number.isSafeInteger(g5) || g5 < 0) efail('game not an id53');
    const lo6 = g5 >>> 0, hi7 = (g5 - lo6) / 4294967296;
    b[7] = lo6; b[8] = lo6 >>> 8; b[9] = lo6 >>> 16; b[10] = lo6 >>> 24;
    b[11] = hi7; b[12] = hi7 >>> 8; b[13] = hi7 >>> 16; b[14] = hi7 >>> 24;
    return b;
}

// 0x82 S_Ping (s2c)
function e_S_Ping(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.nonce;
    const v2 = m.serverTime;
    const b = Buffer.allocUnsafe(13);
    b[0] = 0x82;
    if ((v1 >>> 0) !== v1) efail('nonce out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const d3 = Number(v2) || 0;
    if (d3 - d3 !== 0) efail('serverTime not finite');
    wf64(b, 5, d3);
    return b;
}

// 0x83 S_Pong (s2c)
function e_S_Pong(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.nonce;
    const v2 = m.serverTime;
    const b = Buffer.allocUnsafe(13);
    b[0] = 0x83;
    if ((v1 >>> 0) !== v1) efail('nonce out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    const d3 = Number(v2) || 0;
    if (d3 - d3 !== 0) efail('serverTime not finite');
    wf64(b, 5, d3);
    return b;
}

// 0x84 Ack (s2c)
function e_Ack(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.ref;
    const b = Buffer.allocUnsafe(5);
    b[0] = 0x84;
    if ((v1 >>> 0) !== v1) efail('ref out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    return b;
}

// 0x85 Notice (s2c)
function e_Notice(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.code;
    const v2 = m.arg;
    const b = Buffer.allocUnsafe(10);
    b[0] = 0x85;
    if ((v1 & 255) !== v1 || v1 < 1 || v1 > 7) efail('code not a NoticeCode');
    b[1] = v1;
    const d3 = Number(v2) || 0;
    if (d3 - d3 !== 0) efail('arg not finite');
    wf64(b, 2, d3);
    return b;
}

// 0x90 QueueStatus (s2c)
function e_QueueStatus(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.category ?? '';
    if (typeof v1 !== 'string') efail('category not a string');
    const L2 = slen(v1);
    if (L2 < 0) efail('category contains NUL');
    if (L2 > 7) efail('category bad length');
    const v3 = m.rated;
    const v4 = m.state;
    const v5 = m.waitMs;
    const v6 = m.window;
    const v7 = m.queued;
    const b = Buffer.allocUnsafe(14 + L2);
    b[0] = 0x90;
    let o = 0;
    b[1] = L2;
    o = 2;
    if (L2 !== 0) { wstr(b, o, v1, L2); o += L2; }
    b[o] = v3 ? 1 : 0;
    if ((v4 & 255) !== v4 || v4 > 2) efail('state not a QueueState');
    b[o + 1] = v4;
    if ((v5 >>> 0) !== v5) efail('waitMs out of range');
    b[o + 2] = v5; b[o + 3] = v5 >>> 8; b[o + 4] = v5 >>> 16; b[o + 5] = v5 >>> 24;
    if ((v6 & 65535) !== v6) efail('window out of range');
    b[o + 6] = v6; b[o + 7] = v6 >>> 8;
    if ((v7 >>> 0) !== v7) efail('queued out of range');
    b[o + 8] = v7; b[o + 9] = v7 >>> 8; b[o + 10] = v7 >>> 16; b[o + 11] = v7 >>> 24;
    return b;
}

// 0x91 ChallengeReceived (s2c)
function e_ChallengeReceived(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.id;
    const s2 = m.from ?? NO_OBJ;
    const v3 = s2.userId;
    const v4 = s2.name ?? '';
    if (typeof v4 !== 'string') efail('from.name not a string');
    const L5 = slen(v4);
    if (L5 < 0) efail('from.name contains NUL');
    if (L5 > 24 || L5 < 1) efail('from.name bad length');
    const v6 = s2.rating;
    const v7 = s2.provisional;
    const v8 = m.baseSec;
    const v9 = m.incSec;
    const v10 = m.rated;
    const v11 = m.yourColor;
    const v12 = m.expiresMs;
    const b = Buffer.allocUnsafe(22 + L5);
    b[0] = 0x91;
    let o = 0;
    if ((v1 >>> 0) !== v1) efail('id out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v3 >>> 0) !== v3) efail('from.userId out of range');
    b[5] = v3; b[6] = v3 >>> 8; b[7] = v3 >>> 16; b[8] = v3 >>> 24;
    b[9] = L5;
    o = 10;
    if (L5 !== 0) { wstr(b, o, v4, L5); o += L5; }
    if ((v6 & 65535) !== v6) efail('from.rating out of range');
    b[o] = v6; b[o + 1] = v6 >>> 8;
    b[o + 2] = v7 ? 1 : 0;
    if ((v8 & 65535) !== v8) efail('baseSec out of range');
    b[o + 3] = v8; b[o + 4] = v8 >>> 8;
    if ((v9 & 255) !== v9) efail('incSec out of range');
    b[o + 5] = v9;
    b[o + 6] = v10 ? 1 : 0;
    if ((v11 & 255) !== v11 || v11 > 2) efail('yourColor not a ColorPref');
    b[o + 7] = v11;
    if ((v12 >>> 0) !== v12) efail('expiresMs out of range');
    b[o + 8] = v12; b[o + 9] = v12 >>> 8; b[o + 10] = v12 >>> 16; b[o + 11] = v12 >>> 24;
    return b;
}

// 0x92 ChallengeStatus (s2c)
function e_ChallengeStatus(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.id;
    const v2 = m.state;
    const v3 = m.target ?? '';
    if (typeof v3 !== 'string') efail('target not a string');
    const L4 = slen(v3);
    if (L4 < 0) efail('target contains NUL');
    if (L4 > 24) efail('target bad length');
    const v5 = m.code ?? '';
    if (typeof v5 !== 'string') efail('code not a string');
    const L6 = slen(v5);
    if (L6 < 0) efail('code contains NUL');
    if (L6 > 12) efail('code bad length');
    const v7 = m.baseSec;
    const v8 = m.incSec;
    const v9 = m.rated;
    const b = Buffer.allocUnsafe(12 + L4 + L6);
    b[0] = 0x92;
    let o = 0;
    if ((v1 >>> 0) !== v1) efail('id out of range');
    b[1] = v1; b[2] = v1 >>> 8; b[3] = v1 >>> 16; b[4] = v1 >>> 24;
    if ((v2 & 255) !== v2 || v2 > 5) efail('state not a ChallengeState');
    b[5] = v2;
    b[6] = L4;
    o = 7;
    if (L4 !== 0) { wstr(b, o, v3, L4); o += L4; }
    b[o] = L6;
    o += 1;
    if (L6 !== 0) { wstr(b, o, v5, L6); o += L6; }
    if ((v7 & 65535) !== v7) efail('baseSec out of range');
    b[o] = v7; b[o + 1] = v7 >>> 8;
    if ((v8 & 255) !== v8) efail('incSec out of range');
    b[o + 2] = v8;
    b[o + 3] = v9 ? 1 : 0;
    return b;
}

// 0xA0 GameSnapshot (s2c)
function e_GameSnapshot(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.game;
    const v2 = m.gseq;
    const v3 = m.category ?? '';
    if (typeof v3 !== 'string') efail('category not a string');
    const L4 = slen(v3);
    if (L4 < 0) efail('category contains NUL');
    if (L4 > 7) efail('category bad length');
    const v5 = m.baseMs;
    const v6 = m.incMs;
    const v7 = m.rated;
    const s8 = m.white ?? NO_OBJ;
    const v9 = s8.userId;
    const v10 = s8.name ?? '';
    if (typeof v10 !== 'string') efail('white.name not a string');
    const L11 = slen(v10);
    if (L11 < 0) efail('white.name contains NUL');
    if (L11 > 24 || L11 < 1) efail('white.name bad length');
    const v12 = s8.rating;
    const v13 = s8.provisional;
    const s14 = m.black ?? NO_OBJ;
    const v15 = s14.userId;
    const v16 = s14.name ?? '';
    if (typeof v16 !== 'string') efail('black.name not a string');
    const L17 = slen(v16);
    if (L17 < 0) efail('black.name contains NUL');
    if (L17 > 24 || L17 < 1) efail('black.name bad length');
    const v18 = s14.rating;
    const v19 = s14.provisional;
    const v20 = m.you;
    const v21 = m.moves ?? NO_ARR;
    if (!Array.isArray(v21)) efail('moves not an array');
    if (v21.length > 1200) efail('moves too long');
    const v22 = m.running;
    const v23 = m.whiteMs;
    const v24 = m.blackMs;
    const v25 = m.serverTime;
    const v26 = m.drawOffer;
    const v27 = m.status;
    const v28 = m.reason;
    const v29 = m.whiteConnected;
    const v30 = m.blackConnected;
    const v31 = m.graceMs;
    const v32 = m.firstMoveMs;
    const v33 = m.startedAt;
    const v34 = m.rematch;
    const v35 = m.autoPress;
    const b = Buffer.allocUnsafe(82 + L4 + L11 + L17 + v21.length * 10);
    b[0] = 0xA0;
    let o = 0;
    const g36 = v1 || 0;
    if (!Number.isSafeInteger(g36) || g36 < 0) efail('game not an id53');
    const lo37 = g36 >>> 0, hi38 = (g36 - lo37) / 4294967296;
    b[1] = lo37; b[2] = lo37 >>> 8; b[3] = lo37 >>> 16; b[4] = lo37 >>> 24;
    b[5] = hi38; b[6] = hi38 >>> 8; b[7] = hi38 >>> 16; b[8] = hi38 >>> 24;
    if ((v2 >>> 0) !== v2) efail('gseq out of range');
    b[9] = v2; b[10] = v2 >>> 8; b[11] = v2 >>> 16; b[12] = v2 >>> 24;
    b[13] = L4;
    o = 14;
    if (L4 !== 0) { wstr(b, o, v3, L4); o += L4; }
    if ((v5 >>> 0) !== v5) efail('baseMs out of range');
    b[o] = v5; b[o + 1] = v5 >>> 8; b[o + 2] = v5 >>> 16; b[o + 3] = v5 >>> 24;
    if ((v6 >>> 0) !== v6) efail('incMs out of range');
    b[o + 4] = v6; b[o + 5] = v6 >>> 8; b[o + 6] = v6 >>> 16; b[o + 7] = v6 >>> 24;
    b[o + 8] = v7 ? 1 : 0;
    if ((v9 >>> 0) !== v9) efail('white.userId out of range');
    b[o + 9] = v9; b[o + 10] = v9 >>> 8; b[o + 11] = v9 >>> 16; b[o + 12] = v9 >>> 24;
    b[o + 13] = L11;
    o += 14;
    if (L11 !== 0) { wstr(b, o, v10, L11); o += L11; }
    if ((v12 & 65535) !== v12) efail('white.rating out of range');
    b[o] = v12; b[o + 1] = v12 >>> 8;
    b[o + 2] = v13 ? 1 : 0;
    if ((v15 >>> 0) !== v15) efail('black.userId out of range');
    b[o + 3] = v15; b[o + 4] = v15 >>> 8; b[o + 5] = v15 >>> 16; b[o + 6] = v15 >>> 24;
    b[o + 7] = L17;
    o += 8;
    if (L17 !== 0) { wstr(b, o, v16, L17); o += L17; }
    if ((v18 & 65535) !== v18) efail('black.rating out of range');
    b[o] = v18; b[o + 1] = v18 >>> 8;
    b[o + 2] = v19 ? 1 : 0;
    if ((v20 & 255) !== v20 || v20 > 2) efail('you not a Color');
    b[o + 3] = v20;
    const c39 = v21.length;
    b[o + 4] = c39; b[o + 5] = c39 >>> 8;
    o += 6;
    for (let i40 = 0; i40 < c39; i40++) {
        const s41 = v21[i40] ?? NO_OBJ;
        const v42 = s41.move;
        if ((v42 & 65535) !== v42) efail('moves.move out of range');
        if (v42 > 32767) efail('moves.move above max');
        b[o] = v42; b[o + 1] = v42 >>> 8;
        const v43 = s41.spentMs;
        if ((v43 >>> 0) !== v43) efail('moves.spentMs out of range');
        b[o + 2] = v43; b[o + 3] = v43 >>> 8; b[o + 4] = v43 >>> 16; b[o + 5] = v43 >>> 24;
        const v44 = s41.clockMs;
        if ((v44 >>> 0) !== v44) efail('moves.clockMs out of range');
        b[o + 6] = v44; b[o + 7] = v44 >>> 8; b[o + 8] = v44 >>> 16; b[o + 9] = v44 >>> 24;
        o += 10;
    }
    if ((v22 & 255) !== v22 || v22 > 2) efail('running not a Color');
    b[o] = v22;
    if ((v23 >>> 0) !== v23) efail('whiteMs out of range');
    b[o + 1] = v23; b[o + 2] = v23 >>> 8; b[o + 3] = v23 >>> 16; b[o + 4] = v23 >>> 24;
    if ((v24 >>> 0) !== v24) efail('blackMs out of range');
    b[o + 5] = v24; b[o + 6] = v24 >>> 8; b[o + 7] = v24 >>> 16; b[o + 8] = v24 >>> 24;
    const d45 = Number(v25) || 0;
    if (d45 - d45 !== 0) efail('serverTime not finite');
    wf64(b, o + 9, d45);
    if ((v26 & 255) !== v26 || v26 > 2) efail('drawOffer not a Color');
    b[o + 17] = v26;
    if ((v27 & 255) !== v27 || v27 > 4) efail('status not a GameStatus');
    b[o + 18] = v27;
    if ((v28 & 255) !== v28 || EN_EndReason[v28] === 0) efail('reason not a EndReason');
    b[o + 19] = v28;
    b[o + 20] = v29 ? 1 : 0;
    b[o + 21] = v30 ? 1 : 0;
    if ((v31 >>> 0) !== v31) efail('graceMs out of range');
    b[o + 22] = v31; b[o + 23] = v31 >>> 8; b[o + 24] = v31 >>> 16; b[o + 25] = v31 >>> 24;
    if ((v32 >>> 0) !== v32) efail('firstMoveMs out of range');
    b[o + 26] = v32; b[o + 27] = v32 >>> 8; b[o + 28] = v32 >>> 16; b[o + 29] = v32 >>> 24;
    const d46 = Number(v33) || 0;
    if (d46 - d46 !== 0) efail('startedAt not finite');
    wf64(b, o + 30, d46);
    if ((v34 & 255) !== v34 || v34 > 2) efail('rematch not a Color');
    b[o + 38] = v34;
    b[o + 39] = v35 ? 1 : 0;
    return b;
}

// 0xA1 MoveMade (s2c)
function e_MoveMade(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.game;
    const v2 = m.gseq;
    const v3 = m.ply;
    const v4 = m.move;
    const v5 = m.flags;
    const v6 = m.spentMs;
    const v7 = m.whiteMs;
    const v8 = m.blackMs;
    const v9 = m.serverTime;
    const v10 = m.drawOffer;
    const v11 = m.firstMoveMs;
    const b = Buffer.allocUnsafe(43);
    b[0] = 0xA1;
    const g12 = v1 || 0;
    if (!Number.isSafeInteger(g12) || g12 < 0) efail('game not an id53');
    const lo13 = g12 >>> 0, hi14 = (g12 - lo13) / 4294967296;
    b[1] = lo13; b[2] = lo13 >>> 8; b[3] = lo13 >>> 16; b[4] = lo13 >>> 24;
    b[5] = hi14; b[6] = hi14 >>> 8; b[7] = hi14 >>> 16; b[8] = hi14 >>> 24;
    if ((v2 >>> 0) !== v2) efail('gseq out of range');
    b[9] = v2; b[10] = v2 >>> 8; b[11] = v2 >>> 16; b[12] = v2 >>> 24;
    if ((v3 & 65535) !== v3) efail('ply out of range');
    b[13] = v3; b[14] = v3 >>> 8;
    if ((v4 & 65535) !== v4) efail('move out of range');
    b[15] = v4; b[16] = v4 >>> 8;
    if ((v5 & 255) !== v5) efail('flags out of range');
    b[17] = v5;
    if ((v6 >>> 0) !== v6) efail('spentMs out of range');
    b[18] = v6; b[19] = v6 >>> 8; b[20] = v6 >>> 16; b[21] = v6 >>> 24;
    if ((v7 >>> 0) !== v7) efail('whiteMs out of range');
    b[22] = v7; b[23] = v7 >>> 8; b[24] = v7 >>> 16; b[25] = v7 >>> 24;
    if ((v8 >>> 0) !== v8) efail('blackMs out of range');
    b[26] = v8; b[27] = v8 >>> 8; b[28] = v8 >>> 16; b[29] = v8 >>> 24;
    const d15 = Number(v9) || 0;
    if (d15 - d15 !== 0) efail('serverTime not finite');
    wf64(b, 30, d15);
    b[38] = v10 ? 1 : 0;
    if ((v11 >>> 0) !== v11) efail('firstMoveMs out of range');
    b[39] = v11; b[40] = v11 >>> 8; b[41] = v11 >>> 16; b[42] = v11 >>> 24;
    return b;
}

// 0xA2 MoveRejected (s2c)
function e_MoveRejected(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.game;
    const v2 = m.ply;
    const v3 = m.move;
    const v4 = m.code;
    const b = Buffer.allocUnsafe(14);
    b[0] = 0xA2;
    const g5 = v1 || 0;
    if (!Number.isSafeInteger(g5) || g5 < 0) efail('game not an id53');
    const lo6 = g5 >>> 0, hi7 = (g5 - lo6) / 4294967296;
    b[1] = lo6; b[2] = lo6 >>> 8; b[3] = lo6 >>> 16; b[4] = lo6 >>> 24;
    b[5] = hi7; b[6] = hi7 >>> 8; b[7] = hi7 >>> 16; b[8] = hi7 >>> 24;
    if ((v2 & 65535) !== v2) efail('ply out of range');
    b[9] = v2; b[10] = v2 >>> 8;
    if ((v3 & 65535) !== v3) efail('move out of range');
    b[11] = v3; b[12] = v3 >>> 8;
    if ((v4 & 255) !== v4 || EN_ErrorCode[v4] === 0) efail('code not a ErrorCode');
    b[13] = v4;
    return b;
}

// 0xA3 GameEvent (s2c)
function e_GameEvent(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.game;
    const v2 = m.gseq;
    const v3 = m.kind;
    const v4 = m.color;
    const v5 = m.arg;
    const b = Buffer.allocUnsafe(19);
    b[0] = 0xA3;
    const g6 = v1 || 0;
    if (!Number.isSafeInteger(g6) || g6 < 0) efail('game not an id53');
    const lo7 = g6 >>> 0, hi8 = (g6 - lo7) / 4294967296;
    b[1] = lo7; b[2] = lo7 >>> 8; b[3] = lo7 >>> 16; b[4] = lo7 >>> 24;
    b[5] = hi8; b[6] = hi8 >>> 8; b[7] = hi8 >>> 16; b[8] = hi8 >>> 24;
    if ((v2 >>> 0) !== v2) efail('gseq out of range');
    b[9] = v2; b[10] = v2 >>> 8; b[11] = v2 >>> 16; b[12] = v2 >>> 24;
    if ((v3 & 255) !== v3 || v3 < 1 || v3 > 7) efail('kind not a GameEventKind');
    b[13] = v3;
    if ((v4 & 255) !== v4 || v4 > 2) efail('color not a Color');
    b[14] = v4;
    if ((v5 >>> 0) !== v5) efail('arg out of range');
    b[15] = v5; b[16] = v5 >>> 8; b[17] = v5 >>> 16; b[18] = v5 >>> 24;
    return b;
}

// 0xA4 GameEnd (s2c)
function e_GameEnd(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.game;
    const v2 = m.gseq;
    const v3 = m.status;
    const v4 = m.reason;
    const v5 = m.whiteMs;
    const v6 = m.blackMs;
    const v7 = m.serverTime;
    const b = Buffer.allocUnsafe(31);
    b[0] = 0xA4;
    const g8 = v1 || 0;
    if (!Number.isSafeInteger(g8) || g8 < 0) efail('game not an id53');
    const lo9 = g8 >>> 0, hi10 = (g8 - lo9) / 4294967296;
    b[1] = lo9; b[2] = lo9 >>> 8; b[3] = lo9 >>> 16; b[4] = lo9 >>> 24;
    b[5] = hi10; b[6] = hi10 >>> 8; b[7] = hi10 >>> 16; b[8] = hi10 >>> 24;
    if ((v2 >>> 0) !== v2) efail('gseq out of range');
    b[9] = v2; b[10] = v2 >>> 8; b[11] = v2 >>> 16; b[12] = v2 >>> 24;
    if ((v3 & 255) !== v3 || v3 > 4) efail('status not a GameStatus');
    b[13] = v3;
    if ((v4 & 255) !== v4 || EN_EndReason[v4] === 0) efail('reason not a EndReason');
    b[14] = v4;
    if ((v5 >>> 0) !== v5) efail('whiteMs out of range');
    b[15] = v5; b[16] = v5 >>> 8; b[17] = v5 >>> 16; b[18] = v5 >>> 24;
    if ((v6 >>> 0) !== v6) efail('blackMs out of range');
    b[19] = v6; b[20] = v6 >>> 8; b[21] = v6 >>> 16; b[22] = v6 >>> 24;
    const d11 = Number(v7) || 0;
    if (d11 - d11 !== 0) efail('serverTime not finite');
    wf64(b, 23, d11);
    return b;
}

// 0xA5 RatingUpdate (s2c)
function e_RatingUpdate(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.game;
    const v2 = m.category ?? '';
    if (typeof v2 !== 'string') efail('category not a string');
    const L3 = slen(v2);
    if (L3 < 0) efail('category contains NUL');
    if (L3 > 7) efail('category bad length');
    const s4 = m.white ?? NO_OBJ;
    const v5 = s4.before;
    const v6 = s4.after;
    const v7 = s4.games;
    const v8 = s4.provisional;
    const s9 = m.black ?? NO_OBJ;
    const v10 = s9.before;
    const v11 = s9.after;
    const v12 = s9.games;
    const v13 = s9.provisional;
    const b = Buffer.allocUnsafe(28 + L3);
    b[0] = 0xA5;
    let o = 0;
    const g14 = v1 || 0;
    if (!Number.isSafeInteger(g14) || g14 < 0) efail('game not an id53');
    const lo15 = g14 >>> 0, hi16 = (g14 - lo15) / 4294967296;
    b[1] = lo15; b[2] = lo15 >>> 8; b[3] = lo15 >>> 16; b[4] = lo15 >>> 24;
    b[5] = hi16; b[6] = hi16 >>> 8; b[7] = hi16 >>> 16; b[8] = hi16 >>> 24;
    b[9] = L3;
    o = 10;
    if (L3 !== 0) { wstr(b, o, v2, L3); o += L3; }
    if ((v5 & 65535) !== v5) efail('white.before out of range');
    b[o] = v5; b[o + 1] = v5 >>> 8;
    if ((v6 & 65535) !== v6) efail('white.after out of range');
    b[o + 2] = v6; b[o + 3] = v6 >>> 8;
    if ((v7 >>> 0) !== v7) efail('white.games out of range');
    b[o + 4] = v7; b[o + 5] = v7 >>> 8; b[o + 6] = v7 >>> 16; b[o + 7] = v7 >>> 24;
    b[o + 8] = v8 ? 1 : 0;
    if ((v10 & 65535) !== v10) efail('black.before out of range');
    b[o + 9] = v10; b[o + 10] = v10 >>> 8;
    if ((v11 & 65535) !== v11) efail('black.after out of range');
    b[o + 11] = v11; b[o + 12] = v11 >>> 8;
    if ((v12 >>> 0) !== v12) efail('black.games out of range');
    b[o + 13] = v12; b[o + 14] = v12 >>> 8; b[o + 15] = v12 >>> 16; b[o + 16] = v12 >>> 24;
    b[o + 17] = v13 ? 1 : 0;
    return b;
}

// 0xA6 S_Gesture (s2c)
function e_S_Gesture(m) {
    if (m === null || typeof m !== 'object') efail('message not an object');
    const v1 = m.game;
    const v2 = m.ply;
    const v3 = m.touch;
    const v4 = m.aim;
    const v5 = m.placed;
    const v6 = m.flags;
    const v7 = m.yaw;
    const v8 = m.pitch;
    const v9 = m.lean;
    const b = Buffer.allocUnsafe(25);
    b[0] = 0xA6;
    const g10 = v1 || 0;
    if (!Number.isSafeInteger(g10) || g10 < 0) efail('game not an id53');
    const lo11 = g10 >>> 0, hi12 = (g10 - lo11) / 4294967296;
    b[1] = lo11; b[2] = lo11 >>> 8; b[3] = lo11 >>> 16; b[4] = lo11 >>> 24;
    b[5] = hi12; b[6] = hi12 >>> 8; b[7] = hi12 >>> 16; b[8] = hi12 >>> 24;
    if ((v2 & 65535) !== v2) efail('ply out of range');
    if (v2 > 1199) efail('ply above max');
    b[9] = v2; b[10] = v2 >>> 8;
    if ((v3 & 255) !== v3) efail('touch out of range');
    if (v3 > 64) efail('touch above max');
    b[11] = v3;
    if ((v4 & 255) !== v4) efail('aim out of range');
    if (v4 > 64) efail('aim above max');
    b[12] = v4;
    if ((v5 & 65535) !== v5) efail('placed out of range');
    if (v5 > 32767) efail('placed above max');
    b[13] = v5; b[14] = v5 >>> 8;
    if ((v6 & 255) !== v6) efail('flags out of range');
    if (v6 > 7) efail('flags above max');
    b[15] = v6;
    if ((v7 | 0) !== v7) efail('yaw out of range');
    if (v7 < -3142) efail('yaw below min');
    if (v7 > 3142) efail('yaw above max');
    b[16] = v7; b[17] = v7 >>> 8; b[18] = v7 >>> 16; b[19] = v7 >>> 24;
    if ((v8 | 0) !== v8) efail('pitch out of range');
    if (v8 < -1571) efail('pitch below min');
    if (v8 > 1571) efail('pitch above max');
    b[20] = v8; b[21] = v8 >>> 8; b[22] = v8 >>> 16; b[23] = v8 >>> 24;
    if ((v9 & 255) !== v9) efail('lean out of range');
    if (v9 > 100) efail('lean above max');
    b[24] = v9;
    return b;
}

/** encode.<Name>(fields) -> Buffer of the exact size; throws ProtocolError when a value is invalid. */
export const encode = Object.freeze({
    Hello: e_Hello,
    C_Ping: e_C_Ping,
    C_Pong: e_C_Pong,
    QueueJoin: e_QueueJoin,
    QueueLeave: e_QueueLeave,
    ChallengeCreate: e_ChallengeCreate,
    ChallengeAccept: e_ChallengeAccept,
    ChallengeDecline: e_ChallengeDecline,
    ChallengeCancel: e_ChallengeCancel,
    ChallengeJoinCode: e_ChallengeJoinCode,
    Move: e_Move,
    Resign: e_Resign,
    DrawOffer: e_DrawOffer,
    DrawAnswer: e_DrawAnswer,
    DrawClaim: e_DrawClaim,
    Abort: e_Abort,
    Resync: e_Resync,
    Rematch: e_Rematch,
    C_Gesture: e_C_Gesture,
    Welcome: e_Welcome,
    Error: e_Error,
    S_Ping: e_S_Ping,
    S_Pong: e_S_Pong,
    Ack: e_Ack,
    Notice: e_Notice,
    QueueStatus: e_QueueStatus,
    ChallengeReceived: e_ChallengeReceived,
    ChallengeStatus: e_ChallengeStatus,
    GameSnapshot: e_GameSnapshot,
    MoveMade: e_MoveMade,
    MoveRejected: e_MoveRejected,
    GameEvent: e_GameEvent,
    GameEnd: e_GameEnd,
    RatingUpdate: e_RatingUpdate,
    S_Gesture: e_S_Gesture,
});

// ---- decoders ----

// 0x01 Hello (c2s)
function d_Hello(b, n) {
    let o = 0;
    if (12 > n) fail('truncated');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = b[5] | b[6] << 8;
    const v3 = (b[7] | b[8] << 8 | b[9] << 16 | b[10] << 24) >>> 0;
    const l4 = b[11];
    if (l4 > 48) fail('client bad length');
    o = 12;
    if (o + l4 > n) fail('truncated');
    const v5 = l4 === 0 ? '' : rstr(b, o, o + l4, 'client');
    o += l4;
    if (o + 1 > n) fail('truncated');
    const l6 = b[o];
    if (l6 > 160 || l6 < 16) fail('token bad length');
    o += 1;
    if (o + l6 > n) fail('truncated');
    const v7 = l6 === 0 ? '' : rstr(b, o, o + l6, 'token');
    o += l6;
    if (o !== n) fail('trailing bytes');
    return { type: 0x01, seq: v1, proto: v2, schema: v3, client: v5, token: v7 };
}

// 0x02 C_Ping (c2s)
function d_C_Ping(b, n) {
    if (n !== 9) fail(n < 9 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    return { type: 0x02, seq: v1, nonce: v2 };
}

// 0x03 C_Pong (c2s)
function d_C_Pong(b, n) {
    if (n !== 9) fail(n < 9 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    return { type: 0x03, seq: v1, nonce: v2 };
}

// 0x10 QueueJoin (c2s)
function d_QueueJoin(b, n) {
    let o = 0;
    if (6 > n) fail('truncated');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const l2 = b[5];
    if (l2 > 7 || l2 < 3) fail('category bad length');
    o = 6;
    if (o + l2 > n) fail('truncated');
    const v3 = l2 === 0 ? '' : rstr(b, o, o + l2, 'category');
    o += l2;
    if (o + 1 > n) fail('truncated');
    const v4 = b[o];
    if (v4 > 1) fail('rated not a bool');
    if (o + 1 !== n) fail('trailing bytes');
    return { type: 0x10, seq: v1, category: v3, rated: v4 === 1 };
}

// 0x11 QueueLeave (c2s)
function d_QueueLeave(b, n) {
    if (n !== 5) fail(n < 5 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    return { type: 0x11, seq: v1 };
}

// 0x12 ChallengeCreate (c2s)
function d_ChallengeCreate(b, n) {
    let o = 0;
    if (6 > n) fail('truncated');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const l2 = b[5];
    if (l2 > 24) fail('target bad length');
    o = 6;
    if (o + l2 > n) fail('truncated');
    const v3 = l2 === 0 ? '' : rstr(b, o, o + l2, 'target');
    o += l2;
    if (o + 5 > n) fail('truncated');
    const v4 = b[o] | b[o + 1] << 8;
    if (v4 < 15) fail('baseSec below min');
    if (v4 > 10800) fail('baseSec above max');
    const v5 = b[o + 2];
    if (v5 > 180) fail('incSec above max');
    const v6 = b[o + 3];
    if (v6 > 1) fail('rated not a bool');
    const v7 = b[o + 4];
    if (v7 > 2) fail('color not a ColorPref');
    if (o + 5 !== n) fail('trailing bytes');
    return { type: 0x12, seq: v1, target: v3, baseSec: v4, incSec: v5, rated: v6 === 1, color: v7 };
}

// 0x13 ChallengeAccept (c2s)
function d_ChallengeAccept(b, n) {
    if (n !== 9) fail(n < 9 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    return { type: 0x13, seq: v1, id: v2 };
}

// 0x14 ChallengeDecline (c2s)
function d_ChallengeDecline(b, n) {
    if (n !== 9) fail(n < 9 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    return { type: 0x14, seq: v1, id: v2 };
}

// 0x15 ChallengeCancel (c2s)
function d_ChallengeCancel(b, n) {
    if (n !== 9) fail(n < 9 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    return { type: 0x15, seq: v1, id: v2 };
}

// 0x16 ChallengeJoinCode (c2s)
function d_ChallengeJoinCode(b, n) {
    let o = 0;
    if (6 > n) fail('truncated');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const l2 = b[5];
    if (l2 > 12 || l2 < 4) fail('code bad length');
    o = 6;
    if (o + l2 > n) fail('truncated');
    const v3 = l2 === 0 ? '' : rstr(b, o, o + l2, 'code');
    o += l2;
    if (o !== n) fail('trailing bytes');
    return { type: 0x16, seq: v1, code: v3 };
}

// 0x20 Move (c2s)
function d_Move(b, n) {
    if (n !== 26) fail(n < 26 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    const v4 = b[13] | b[14] << 8;
    if (v4 > 1199) fail('ply above max');
    const v5 = b[15] | b[16] << 8;
    if (v5 > 32767) fail('move above max');
    const v6 = (b[17] | b[18] << 8 | b[19] << 16 | b[20] << 24) >>> 0;
    const v7 = (b[21] | b[22] << 8 | b[23] << 16 | b[24] << 24) >>> 0;
    const v8 = b[25];
    if (v8 > 1) fail('drawOffer not a bool');
    return { type: 0x20, seq: v1, game: v2, ply: v4, move: v5, posHash: v6, thinkMs: v7, drawOffer: v8 === 1 };
}

// 0x21 Resign (c2s)
function d_Resign(b, n) {
    if (n !== 13) fail(n < 13 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    return { type: 0x21, seq: v1, game: v2 };
}

// 0x22 DrawOffer (c2s)
function d_DrawOffer(b, n) {
    if (n !== 13) fail(n < 13 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    return { type: 0x22, seq: v1, game: v2 };
}

// 0x23 DrawAnswer (c2s)
function d_DrawAnswer(b, n) {
    if (n !== 14) fail(n < 14 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    const v4 = b[13];
    if (v4 > 1) fail('accept not a bool');
    return { type: 0x23, seq: v1, game: v2, accept: v4 === 1 };
}

// 0x24 DrawClaim (c2s)
function d_DrawClaim(b, n) {
    if (n !== 13) fail(n < 13 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    return { type: 0x24, seq: v1, game: v2 };
}

// 0x25 Abort (c2s)
function d_Abort(b, n) {
    if (n !== 13) fail(n < 13 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    return { type: 0x25, seq: v1, game: v2 };
}

// 0x26 Resync (c2s)
function d_Resync(b, n) {
    if (n !== 13) fail(n < 13 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    return { type: 0x26, seq: v1, game: v2 };
}

// 0x27 Rematch (c2s)
function d_Rematch(b, n) {
    if (n !== 14) fail(n < 14 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    const v4 = b[13];
    if (v4 > 1) fail('accept not a bool');
    return { type: 0x27, seq: v1, game: v2, accept: v4 === 1 };
}

// 0x28 C_Gesture (c2s)
function d_C_Gesture(b, n) {
    if (n !== 29) fail(n < 29 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const h3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    if (h3 >= 0x200000) fail('game above 2^53');
    const v2 = h3 * 4294967296 + ((b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0);
    const v4 = b[13] | b[14] << 8;
    if (v4 > 1199) fail('ply above max');
    const v5 = b[15];
    if (v5 > 64) fail('touch above max');
    const v6 = b[16];
    if (v6 > 64) fail('aim above max');
    const v7 = b[17] | b[18] << 8;
    if (v7 > 32767) fail('placed above max');
    const v8 = b[19];
    if (v8 > 7) fail('flags above max');
    const v9 = b[20] | b[21] << 8 | b[22] << 16 | b[23] << 24;
    if (v9 < -3142) fail('yaw below min');
    if (v9 > 3142) fail('yaw above max');
    const v10 = b[24] | b[25] << 8 | b[26] << 16 | b[27] << 24;
    if (v10 < -1571) fail('pitch below min');
    if (v10 > 1571) fail('pitch above max');
    const v11 = b[28];
    if (v11 > 100) fail('lean above max');
    return { type: 0x28, seq: v1, game: v2, ply: v4, touch: v5, aim: v6, placed: v7, flags: v8, yaw: v9, pitch: v10, lean: v11 };
}

// 0x80 Welcome (s2c)
function d_Welcome(b, n) {
    let o = 0;
    if (16 > n) fail('truncated');
    const v1 = b[1] | b[2] << 8;
    const v2 = rf64(b, 3);
    if (v2 - v2 !== 0) fail('serverTime not finite');
    const v3 = (b[11] | b[12] << 8 | b[13] << 16 | b[14] << 24) >>> 0;
    const l4 = b[15];
    if (l4 > 24) fail('username bad length');
    o = 16;
    if (o + l4 > n) fail('truncated');
    const v5 = l4 === 0 ? '' : rstr(b, o, o + l4, 'username');
    o += l4;
    if (o + 1 > n) fail('truncated');
    const l6 = b[o];
    if (l6 > 64) fail('serverName bad length');
    o += 1;
    if (o + l6 > n) fail('truncated');
    const v7 = l6 === 0 ? '' : rstr(b, o, o + l6, 'serverName');
    o += l6;
    if (o + 22 > n) fail('truncated');
    const v8 = (b[o] | b[o + 1] << 8 | b[o + 2] << 16 | b[o + 3] << 24) >>> 0;
    const v9 = (b[o + 4] | b[o + 5] << 8 | b[o + 6] << 16 | b[o + 7] << 24) >>> 0;
    const v10 = b[o + 8] | b[o + 9] << 8;
    const h12 = (b[o + 14] | b[o + 15] << 8 | b[o + 16] << 16 | b[o + 17] << 24) >>> 0;
    if (h12 >= 0x200000) fail('activeGame above 2^53');
    const v11 = h12 * 4294967296 + ((b[o + 10] | b[o + 11] << 8 | b[o + 12] << 16 | b[o + 13] << 24) >>> 0);
    const v13 = b[o + 18] | b[o + 19] << 8;
    if (v13 > 60) fail('gestureRate above max');
    const v14 = b[o + 20] | b[o + 21] << 8;
    if (v14 > 120) fail('gestureBurst above max');
    if (o + 22 !== n) fail('trailing bytes');
    return { type: 0x80, proto: v1, serverTime: v2, userId: v3, username: v5, serverName: v7, heartbeatMs: v8, clientPingMs: v9, maxMsgPerSec: v10, activeGame: v11, gestureRate: v13, gestureBurst: v14 };
}

// 0x81 Error (s2c)
function d_Error(b, n) {
    if (n !== 15) fail(n < 15 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = b[5];
    if (EN_ErrorCode[v2] === 0) fail('code not a ErrorCode');
    const v3 = b[6];
    if (v3 > 1) fail('fatal not a bool');
    const h5 = (b[11] | b[12] << 8 | b[13] << 16 | b[14] << 24) >>> 0;
    if (h5 >= 0x200000) fail('game above 2^53');
    const v4 = h5 * 4294967296 + ((b[7] | b[8] << 8 | b[9] << 16 | b[10] << 24) >>> 0);
    return { type: 0x81, ref: v1, code: v2, fatal: v3 === 1, game: v4 };
}

// 0x82 S_Ping (s2c)
function d_S_Ping(b, n) {
    if (n !== 13) fail(n < 13 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = rf64(b, 5);
    if (v2 - v2 !== 0) fail('serverTime not finite');
    return { type: 0x82, nonce: v1, serverTime: v2 };
}

// 0x83 S_Pong (s2c)
function d_S_Pong(b, n) {
    if (n !== 13) fail(n < 13 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = rf64(b, 5);
    if (v2 - v2 !== 0) fail('serverTime not finite');
    return { type: 0x83, nonce: v1, serverTime: v2 };
}

// 0x84 Ack (s2c)
function d_Ack(b, n) {
    if (n !== 5) fail(n < 5 ? 'truncated' : 'trailing bytes');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    return { type: 0x84, ref: v1 };
}

// 0x85 Notice (s2c)
function d_Notice(b, n) {
    if (n !== 10) fail(n < 10 ? 'truncated' : 'trailing bytes');
    const v1 = b[1];
    if (v1 < 1 || v1 > 7) fail('code not a NoticeCode');
    const v2 = rf64(b, 2);
    if (v2 - v2 !== 0) fail('arg not finite');
    return { type: 0x85, code: v1, arg: v2 };
}

// 0x90 QueueStatus (s2c)
function d_QueueStatus(b, n) {
    let o = 0;
    if (2 > n) fail('truncated');
    const l1 = b[1];
    if (l1 > 7) fail('category bad length');
    o = 2;
    if (o + l1 > n) fail('truncated');
    const v2 = l1 === 0 ? '' : rstr(b, o, o + l1, 'category');
    o += l1;
    if (o + 12 > n) fail('truncated');
    const v3 = b[o];
    if (v3 > 1) fail('rated not a bool');
    const v4 = b[o + 1];
    if (v4 > 2) fail('state not a QueueState');
    const v5 = (b[o + 2] | b[o + 3] << 8 | b[o + 4] << 16 | b[o + 5] << 24) >>> 0;
    const v6 = b[o + 6] | b[o + 7] << 8;
    const v7 = (b[o + 8] | b[o + 9] << 8 | b[o + 10] << 16 | b[o + 11] << 24) >>> 0;
    if (o + 12 !== n) fail('trailing bytes');
    return { type: 0x90, category: v2, rated: v3 === 1, state: v4, waitMs: v5, window: v6, queued: v7 };
}

// 0x91 ChallengeReceived (s2c)
function d_ChallengeReceived(b, n) {
    let o = 0;
    if (10 > n) fail('truncated');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    const l3 = b[9];
    if (l3 > 24 || l3 < 1) fail('from.name bad length');
    o = 10;
    if (o + l3 > n) fail('truncated');
    const v4 = l3 === 0 ? '' : rstr(b, o, o + l3, 'from.name');
    o += l3;
    if (o + 12 > n) fail('truncated');
    const v5 = b[o] | b[o + 1] << 8;
    const v6 = b[o + 2];
    if (v6 > 1) fail('from.provisional not a bool');
    const v7 = b[o + 3] | b[o + 4] << 8;
    const v8 = b[o + 5];
    const v9 = b[o + 6];
    if (v9 > 1) fail('rated not a bool');
    const v10 = b[o + 7];
    if (v10 > 2) fail('yourColor not a ColorPref');
    const v11 = (b[o + 8] | b[o + 9] << 8 | b[o + 10] << 16 | b[o + 11] << 24) >>> 0;
    if (o + 12 !== n) fail('trailing bytes');
    return { type: 0x91, id: v1, from: { userId: v2, name: v4, rating: v5, provisional: v6 === 1 }, baseSec: v7, incSec: v8, rated: v9 === 1, yourColor: v10, expiresMs: v11 };
}

// 0x92 ChallengeStatus (s2c)
function d_ChallengeStatus(b, n) {
    let o = 0;
    if (7 > n) fail('truncated');
    const v1 = (b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0;
    const v2 = b[5];
    if (v2 > 5) fail('state not a ChallengeState');
    const l3 = b[6];
    if (l3 > 24) fail('target bad length');
    o = 7;
    if (o + l3 > n) fail('truncated');
    const v4 = l3 === 0 ? '' : rstr(b, o, o + l3, 'target');
    o += l3;
    if (o + 1 > n) fail('truncated');
    const l5 = b[o];
    if (l5 > 12) fail('code bad length');
    o += 1;
    if (o + l5 > n) fail('truncated');
    const v6 = l5 === 0 ? '' : rstr(b, o, o + l5, 'code');
    o += l5;
    if (o + 4 > n) fail('truncated');
    const v7 = b[o] | b[o + 1] << 8;
    const v8 = b[o + 2];
    const v9 = b[o + 3];
    if (v9 > 1) fail('rated not a bool');
    if (o + 4 !== n) fail('trailing bytes');
    return { type: 0x92, id: v1, state: v2, target: v4, code: v6, baseSec: v7, incSec: v8, rated: v9 === 1 };
}

// 0xA0 GameSnapshot (s2c)
function d_GameSnapshot(b, n) {
    let o = 0;
    if (14 > n) fail('truncated');
    const h2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    if (h2 >= 0x200000) fail('game above 2^53');
    const v1 = h2 * 4294967296 + ((b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0);
    const v3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    const l4 = b[13];
    if (l4 > 7) fail('category bad length');
    o = 14;
    if (o + l4 > n) fail('truncated');
    const v5 = l4 === 0 ? '' : rstr(b, o, o + l4, 'category');
    o += l4;
    if (o + 14 > n) fail('truncated');
    const v6 = (b[o] | b[o + 1] << 8 | b[o + 2] << 16 | b[o + 3] << 24) >>> 0;
    const v7 = (b[o + 4] | b[o + 5] << 8 | b[o + 6] << 16 | b[o + 7] << 24) >>> 0;
    const v8 = b[o + 8];
    if (v8 > 1) fail('rated not a bool');
    const v9 = (b[o + 9] | b[o + 10] << 8 | b[o + 11] << 16 | b[o + 12] << 24) >>> 0;
    const l10 = b[o + 13];
    if (l10 > 24 || l10 < 1) fail('white.name bad length');
    o += 14;
    if (o + l10 > n) fail('truncated');
    const v11 = l10 === 0 ? '' : rstr(b, o, o + l10, 'white.name');
    o += l10;
    if (o + 8 > n) fail('truncated');
    const v12 = b[o] | b[o + 1] << 8;
    const v13 = b[o + 2];
    if (v13 > 1) fail('white.provisional not a bool');
    const v14 = (b[o + 3] | b[o + 4] << 8 | b[o + 5] << 16 | b[o + 6] << 24) >>> 0;
    const l15 = b[o + 7];
    if (l15 > 24 || l15 < 1) fail('black.name bad length');
    o += 8;
    if (o + l15 > n) fail('truncated');
    const v16 = l15 === 0 ? '' : rstr(b, o, o + l15, 'black.name');
    o += l15;
    if (o + 6 > n) fail('truncated');
    const v17 = b[o] | b[o + 1] << 8;
    const v18 = b[o + 2];
    if (v18 > 1) fail('black.provisional not a bool');
    const v19 = b[o + 3];
    if (v19 > 2) fail('you not a Color');
    const c20 = b[o + 4] | b[o + 5] << 8;
    if (c20 > 1200) fail('moves too long');
    o += 6;
    const a21 = [];
    if (o + c20 * 10 > n) fail('truncated');
    for (let i22 = 0; i22 < c20; i22++, o += 10) {
        const v23 = b[o] | b[o + 1] << 8;
        if (v23 > 32767) fail('moves.move above max');
        const v24 = (b[o + 2] | b[o + 3] << 8 | b[o + 4] << 16 | b[o + 5] << 24) >>> 0;
        const v25 = (b[o + 6] | b[o + 7] << 8 | b[o + 8] << 16 | b[o + 9] << 24) >>> 0;
        a21.push({ move: v23, spentMs: v24, clockMs: v25 });
    }
    if (o + 40 > n) fail('truncated');
    const v26 = b[o];
    if (v26 > 2) fail('running not a Color');
    const v27 = (b[o + 1] | b[o + 2] << 8 | b[o + 3] << 16 | b[o + 4] << 24) >>> 0;
    const v28 = (b[o + 5] | b[o + 6] << 8 | b[o + 7] << 16 | b[o + 8] << 24) >>> 0;
    const v29 = rf64(b, o + 9);
    if (v29 - v29 !== 0) fail('serverTime not finite');
    const v30 = b[o + 17];
    if (v30 > 2) fail('drawOffer not a Color');
    const v31 = b[o + 18];
    if (v31 > 4) fail('status not a GameStatus');
    const v32 = b[o + 19];
    if (EN_EndReason[v32] === 0) fail('reason not a EndReason');
    const v33 = b[o + 20];
    if (v33 > 1) fail('whiteConnected not a bool');
    const v34 = b[o + 21];
    if (v34 > 1) fail('blackConnected not a bool');
    const v35 = (b[o + 22] | b[o + 23] << 8 | b[o + 24] << 16 | b[o + 25] << 24) >>> 0;
    const v36 = (b[o + 26] | b[o + 27] << 8 | b[o + 28] << 16 | b[o + 29] << 24) >>> 0;
    const v37 = rf64(b, o + 30);
    if (v37 - v37 !== 0) fail('startedAt not finite');
    const v38 = b[o + 38];
    if (v38 > 2) fail('rematch not a Color');
    const v39 = b[o + 39];
    if (v39 > 1) fail('autoPress not a bool');
    if (o + 40 !== n) fail('trailing bytes');
    return { type: 0xA0, game: v1, gseq: v3, category: v5, baseMs: v6, incMs: v7, rated: v8 === 1, white: { userId: v9, name: v11, rating: v12, provisional: v13 === 1 }, black: { userId: v14, name: v16, rating: v17, provisional: v18 === 1 }, you: v19, moves: a21, running: v26, whiteMs: v27, blackMs: v28, serverTime: v29, drawOffer: v30, status: v31, reason: v32, whiteConnected: v33 === 1, blackConnected: v34 === 1, graceMs: v35, firstMoveMs: v36, startedAt: v37, rematch: v38, autoPress: v39 === 1 };
}

// 0xA1 MoveMade (s2c)
function d_MoveMade(b, n) {
    if (n !== 43) fail(n < 43 ? 'truncated' : 'trailing bytes');
    const h2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    if (h2 >= 0x200000) fail('game above 2^53');
    const v1 = h2 * 4294967296 + ((b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0);
    const v3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    const v4 = b[13] | b[14] << 8;
    const v5 = b[15] | b[16] << 8;
    const v6 = b[17];
    const v7 = (b[18] | b[19] << 8 | b[20] << 16 | b[21] << 24) >>> 0;
    const v8 = (b[22] | b[23] << 8 | b[24] << 16 | b[25] << 24) >>> 0;
    const v9 = (b[26] | b[27] << 8 | b[28] << 16 | b[29] << 24) >>> 0;
    const v10 = rf64(b, 30);
    if (v10 - v10 !== 0) fail('serverTime not finite');
    const v11 = b[38];
    if (v11 > 1) fail('drawOffer not a bool');
    const v12 = (b[39] | b[40] << 8 | b[41] << 16 | b[42] << 24) >>> 0;
    return { type: 0xA1, game: v1, gseq: v3, ply: v4, move: v5, flags: v6, spentMs: v7, whiteMs: v8, blackMs: v9, serverTime: v10, drawOffer: v11 === 1, firstMoveMs: v12 };
}

// 0xA2 MoveRejected (s2c)
function d_MoveRejected(b, n) {
    if (n !== 14) fail(n < 14 ? 'truncated' : 'trailing bytes');
    const h2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    if (h2 >= 0x200000) fail('game above 2^53');
    const v1 = h2 * 4294967296 + ((b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0);
    const v3 = b[9] | b[10] << 8;
    const v4 = b[11] | b[12] << 8;
    const v5 = b[13];
    if (EN_ErrorCode[v5] === 0) fail('code not a ErrorCode');
    return { type: 0xA2, game: v1, ply: v3, move: v4, code: v5 };
}

// 0xA3 GameEvent (s2c)
function d_GameEvent(b, n) {
    if (n !== 19) fail(n < 19 ? 'truncated' : 'trailing bytes');
    const h2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    if (h2 >= 0x200000) fail('game above 2^53');
    const v1 = h2 * 4294967296 + ((b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0);
    const v3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    const v4 = b[13];
    if (v4 < 1 || v4 > 7) fail('kind not a GameEventKind');
    const v5 = b[14];
    if (v5 > 2) fail('color not a Color');
    const v6 = (b[15] | b[16] << 8 | b[17] << 16 | b[18] << 24) >>> 0;
    return { type: 0xA3, game: v1, gseq: v3, kind: v4, color: v5, arg: v6 };
}

// 0xA4 GameEnd (s2c)
function d_GameEnd(b, n) {
    if (n !== 31) fail(n < 31 ? 'truncated' : 'trailing bytes');
    const h2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    if (h2 >= 0x200000) fail('game above 2^53');
    const v1 = h2 * 4294967296 + ((b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0);
    const v3 = (b[9] | b[10] << 8 | b[11] << 16 | b[12] << 24) >>> 0;
    const v4 = b[13];
    if (v4 > 4) fail('status not a GameStatus');
    const v5 = b[14];
    if (EN_EndReason[v5] === 0) fail('reason not a EndReason');
    const v6 = (b[15] | b[16] << 8 | b[17] << 16 | b[18] << 24) >>> 0;
    const v7 = (b[19] | b[20] << 8 | b[21] << 16 | b[22] << 24) >>> 0;
    const v8 = rf64(b, 23);
    if (v8 - v8 !== 0) fail('serverTime not finite');
    return { type: 0xA4, game: v1, gseq: v3, status: v4, reason: v5, whiteMs: v6, blackMs: v7, serverTime: v8 };
}

// 0xA5 RatingUpdate (s2c)
function d_RatingUpdate(b, n) {
    let o = 0;
    if (10 > n) fail('truncated');
    const h2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    if (h2 >= 0x200000) fail('game above 2^53');
    const v1 = h2 * 4294967296 + ((b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0);
    const l3 = b[9];
    if (l3 > 7) fail('category bad length');
    o = 10;
    if (o + l3 > n) fail('truncated');
    const v4 = l3 === 0 ? '' : rstr(b, o, o + l3, 'category');
    o += l3;
    if (o + 18 > n) fail('truncated');
    const v5 = b[o] | b[o + 1] << 8;
    const v6 = b[o + 2] | b[o + 3] << 8;
    const v7 = (b[o + 4] | b[o + 5] << 8 | b[o + 6] << 16 | b[o + 7] << 24) >>> 0;
    const v8 = b[o + 8];
    if (v8 > 1) fail('white.provisional not a bool');
    const v9 = b[o + 9] | b[o + 10] << 8;
    const v10 = b[o + 11] | b[o + 12] << 8;
    const v11 = (b[o + 13] | b[o + 14] << 8 | b[o + 15] << 16 | b[o + 16] << 24) >>> 0;
    const v12 = b[o + 17];
    if (v12 > 1) fail('black.provisional not a bool');
    if (o + 18 !== n) fail('trailing bytes');
    return { type: 0xA5, game: v1, category: v4, white: { before: v5, after: v6, games: v7, provisional: v8 === 1 }, black: { before: v9, after: v10, games: v11, provisional: v12 === 1 } };
}

// 0xA6 S_Gesture (s2c)
function d_S_Gesture(b, n) {
    if (n !== 25) fail(n < 25 ? 'truncated' : 'trailing bytes');
    const h2 = (b[5] | b[6] << 8 | b[7] << 16 | b[8] << 24) >>> 0;
    if (h2 >= 0x200000) fail('game above 2^53');
    const v1 = h2 * 4294967296 + ((b[1] | b[2] << 8 | b[3] << 16 | b[4] << 24) >>> 0);
    const v3 = b[9] | b[10] << 8;
    if (v3 > 1199) fail('ply above max');
    const v4 = b[11];
    if (v4 > 64) fail('touch above max');
    const v5 = b[12];
    if (v5 > 64) fail('aim above max');
    const v6 = b[13] | b[14] << 8;
    if (v6 > 32767) fail('placed above max');
    const v7 = b[15];
    if (v7 > 7) fail('flags above max');
    const v8 = b[16] | b[17] << 8 | b[18] << 16 | b[19] << 24;
    if (v8 < -3142) fail('yaw below min');
    if (v8 > 3142) fail('yaw above max');
    const v9 = b[20] | b[21] << 8 | b[22] << 16 | b[23] << 24;
    if (v9 < -1571) fail('pitch below min');
    if (v9 > 1571) fail('pitch above max');
    const v10 = b[24];
    if (v10 > 100) fail('lean above max');
    return { type: 0xA6, game: v1, ply: v3, touch: v4, aim: v5, placed: v6, flags: v7, yaw: v8, pitch: v9, lean: v10 };
}

/**
 * Decodes one message: { type, ...fields }. opts.dir ('c2s' | 's2c') refuses the other
 * direction's types. Throws ProtocolError (and nothing else) on any malformed input.
 * @param {Buffer|Uint8Array} buf
 * @param {{ dir?: 'c2s' | 's2c' }} [opts]
 */
export function decode(buf, opts) {
    const b = buf instanceof Buffer ? buf : toBuffer(buf);
    const n = b.length;
    if (n === 0) fail('empty');
    const t = b[0];
    const d = DIR[t];
    if (d === 0) fail('unknown type');
    if (opts !== undefined && opts !== null) {
        const w = opts.dir;
        if (w && (w === 'c2s' ? 1 : w === 's2c' ? 2 : 0) !== d) fail('wrong direction');
    }
    switch (t) {
        case 0x01: return d_Hello(b, n);
        case 0x02: return d_C_Ping(b, n);
        case 0x03: return d_C_Pong(b, n);
        case 0x10: return d_QueueJoin(b, n);
        case 0x11: return d_QueueLeave(b, n);
        case 0x12: return d_ChallengeCreate(b, n);
        case 0x13: return d_ChallengeAccept(b, n);
        case 0x14: return d_ChallengeDecline(b, n);
        case 0x15: return d_ChallengeCancel(b, n);
        case 0x16: return d_ChallengeJoinCode(b, n);
        case 0x20: return d_Move(b, n);
        case 0x21: return d_Resign(b, n);
        case 0x22: return d_DrawOffer(b, n);
        case 0x23: return d_DrawAnswer(b, n);
        case 0x24: return d_DrawClaim(b, n);
        case 0x25: return d_Abort(b, n);
        case 0x26: return d_Resync(b, n);
        case 0x27: return d_Rematch(b, n);
        case 0x28: return d_C_Gesture(b, n);
        case 0x80: return d_Welcome(b, n);
        case 0x81: return d_Error(b, n);
        case 0x82: return d_S_Ping(b, n);
        case 0x83: return d_S_Pong(b, n);
        case 0x84: return d_Ack(b, n);
        case 0x85: return d_Notice(b, n);
        case 0x90: return d_QueueStatus(b, n);
        case 0x91: return d_ChallengeReceived(b, n);
        case 0x92: return d_ChallengeStatus(b, n);
        case 0xA0: return d_GameSnapshot(b, n);
        case 0xA1: return d_MoveMade(b, n);
        case 0xA2: return d_MoveRejected(b, n);
        case 0xA3: return d_GameEvent(b, n);
        case 0xA4: return d_GameEnd(b, n);
        case 0xA5: return d_RatingUpdate(b, n);
        case 0xA6: return d_S_Gesture(b, n);
        default: return fail('unknown type');
    }
}
