//! End-to-end validation of the engine analysis, the scoring model and the analysis pool with a
//! real UCI engine (Stockfish), ported from anticheat.engine. Each test returns at once, saying so
//! on stderr, when no engine is installed; `SCACELITH_TEST_ENGINE` names another binary. Small
//! depths keep them within a few minutes on 4 cores. The games are generated by the engine:
//!
//! - an assisted player plays the engine's best move at depth 12 every time, relayed with a think
//!   time unrelated to the position, against a decent human stand-in;
//! - weak human stand-ins pick uniformly among the top-4 moves at depth 5 (within 200 cp),
//!   thinking longer when there are several good moves.

use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::Duration;

use serde_json::json;

use super::POOLS;
use crate::anticheat::analysis::analyzer::{
    Depths, GameFeatures, GameRecord as AnalysedGame, SideContext, SideFeatures, analyse_game, line_cp,
};
use crate::anticheat::analysis::engine::{EngineError, EngineOptions, SearchOptions, UciEngine};
use crate::anticheat::analysis::moves::uci_to_move;
use crate::anticheat::analysis::stats::mean;
use crate::anticheat::integrity::IntegrityLevel;
use crate::anticheat::scoring::{
    Population, PriorsOnly, SideRecord, model, score_player, side_of, update_population_from_game,
};
use crate::anticheat::synthetic::{Rng, gauss};
use crate::anticheat::testing::*;
use crate::anticheat::worker::AnalysisPool;
use crate::clock::{Clock, ManualClock};
use crate::ids::{GameId, UserId};
use crate::store::status::WHITE_WINS;
use crate::store::{IntegrityLevel as StoredLevel, JobStatus, StoreError};

/// The engine of the tests: `SCACELITH_TEST_ENGINE`, else Stockfish where distributions install it.
fn engine_path() -> Option<PathBuf> {
    if let Some(p) = std::env::var_os("SCACELITH_TEST_ENGINE").filter(|p| !p.is_empty()) {
        return Some(PathBuf::from(p));
    }
    ["/usr/games/stockfish", "/usr/bin/stockfish", "/usr/local/bin/stockfish"]
        .into_iter()
        .map(PathBuf::from)
        .find(|p| p.exists())
}

/// The engine, or `None` (said on stderr) when the test cannot run here.
fn engine_or_skip(test: &str) -> Option<PathBuf> {
    let path = engine_path();
    if path.is_none() {
        eprintln!("{test}: skipped, no UCI engine installed (set SCACELITH_TEST_ENGINE)");
    }
    path
}

// ---- engine-generated games (the former testing/engine-games) -----------------------------------

/// How a side of a generated game chooses its moves.
#[derive(Clone, Copy, Debug)]
enum Style {
    /// The engine's best move at `depth`, relayed in 2 to 5 s whatever the position: an engine
    /// user.
    Assisted { depth: u32 },
    /// A uniform pick among the engine's `top_n` lines at `depth` that lose at most `cp` against
    /// the best one (a human stand-in), thinking longer with several good candidates.
    Plausible { depth: u32, top_n: u32, cp: i64 },
}

const ASSISTED: Style = Style::Assisted { depth: 12 };
const DECENT: Style = Style::Plausible { depth: 8, top_n: 3, cp: 60 };
const WEAK: Style = Style::Plausible { depth: 5, top_n: 4, cp: 200 };
/// Plies of the random opening of a generated game.
const OPENING_PLIES: usize = 8;

fn search(depth: u32, multi_pv: u32) -> SearchOptions {
    SearchOptions { multi_pv, ..SearchOptions::depth(depth) }
}

/// The next move of a side after `uci` and its think time; `None` when the side has no move.
async fn choose_move(
    engine: &mut UciEngine,
    uci: &[String],
    style: Style,
    r: &mut Rng,
) -> Result<Option<(String, u32)>, EngineError> {
    match style {
        Style::Assisted { depth } => {
            let res = engine.analyse(uci, &search(depth, 1)).await?;
            Ok(res.bestmove.map(|m| (m, (2000.0 + 3000.0 * r.next()).round() as u32)))
        }
        Style::Plausible { depth, top_n, cp } => {
            let res = engine.analyse(uci, &search(depth, top_n)).await?;
            if res.bestmove.is_none() || res.lines.is_empty() {
                return Ok(None);
            }
            let best = line_cp(&res.lines[0]);
            let candidates: Vec<_> =
                res.lines.iter().filter(|l| l.mv.is_some() && best - line_cp(l) <= cp).collect();
            let pick = if candidates.is_empty() {
                &res.lines[0]
            } else {
                candidates[(r.next() * candidates.len() as f64) as usize]
            };
            let good = res.lines.iter().filter(|l| best - line_cp(l) <= 50).count();
            // Humans think longer with several good candidates; lognormal spread (CV about 0.8).
            let spent = 3000.0 * (0.6 + 0.7 * good as f64) * (0.7 * gauss(r)).exp();
            Ok(pick.mv.clone().map(|m| (m, spent.round() as u32)))
        }
    }
}

/// A generated game: its moves (u16 protocol moves) and think times.
struct Played {
    moves: Vec<u16>,
    spent_ms: Vec<u32>,
}

/// Plays a game from a random opening (uniform picks among the top 5 at depth 4), at most
/// `max_plies` plies.
async fn play_game(
    engine: &mut UciEngine,
    r: &mut Rng,
    white: Style,
    black: Style,
    max_plies: usize,
) -> Result<Played, EngineError> {
    engine.new_game().await?;
    let (mut uci, mut spent_ms): (Vec<String>, Vec<u32>) = (Vec::new(), Vec::new());
    for p in 0..max_plies {
        let (mv, spent) = if p < OPENING_PLIES {
            let res = engine.analyse(&uci, &search(4, 5)).await?;
            let options: Vec<&String> = res.lines.iter().filter_map(|l| l.mv.as_ref()).collect();
            if res.bestmove.is_none() || options.is_empty() {
                break;
            }
            let mv = options[(r.next() * options.len() as f64) as usize].clone();
            (mv, if p < 2 { 0 } else { (1500.0 * (0.5 * gauss(r)).exp()).round() as u32 })
        } else {
            match choose_move(engine, &uci, if p % 2 == 0 { white } else { black }, r).await? {
                Some(m) => m,
                None => break,
            }
        };
        uci.push(mv);
        spent_ms.push(spent);
    }
    let moves = uci.iter().map(|m| uci_to_move(m).expect("the engine plays UCI moves")).collect();
    Ok(Played { moves, spent_ms })
}

// ---- the features and the scoring ----------------------------------------------------------------

const DEPTH_FAST: u32 = 6;
const DEPTH_DEEP: u32 = 10;
const RATING: i64 = 1200;
const CATEGORY: &str = "15+10";
const CHEATER: UserId = 100;
const HONEST: [UserId; 4] = [201, 202, 203, 204];
const ASSISTED_GAMES: u32 = 18;
const HUMAN_GAMES: u32 = 20;
const PIPELINES: usize = 3;

/// A game to generate and analyse.
struct Job {
    id: GameId,
    seed: u32,
    white: Style,
    black: Style,
    white_id: UserId,
    black_id: UserId,
}

/// Generates a job's game with `generator`, then analyses it with `ana`.
async fn play_and_analyse(
    generator: &mut UciEngine,
    ana: &mut UciEngine,
    job: &Job,
    clock: &dyn Clock,
) -> Result<(AnalysedGame, GameFeatures), EngineError> {
    let played = play_game(generator, &mut Rng::new(job.seed), job.white, job.black, 90).await?;
    let record = AnalysedGame {
        id: job.id,
        category: CATEGORY.into(),
        rated: true,
        base_ms: 900_000,
        inc_ms: 10_000,
        white_id: job.white_id,
        black_id: job.black_id,
        white_rating: Some(RATING),
        black_rating: Some(RATING),
        ended_at: Some(1_800_000_000_000 + job.id as i64 * 60_000),
        moves: played.moves,
        spent_ms: played.spent_ms,
    };
    let depths = Depths { fast: DEPTH_FAST, deep: DEPTH_DEEP };
    let features =
        analyse_game(ana, &record, depths, [SideContext { rating_games: Some(100) }; 2], clock).await?;
    Ok((record, features))
}

/// Generates and analyses the jobs on [`PIPELINES`] pairs of engines (one plays, one analyses),
/// in job order.
async fn run_pool(path: &Path, jobs: Vec<Job>) -> Vec<(AnalysedGame, GameFeatures)> {
    let jobs = Arc::new(jobs);
    let next = Arc::new(AtomicUsize::new(0));
    let mut pipes = Vec::new();
    for _ in 0..PIPELINES {
        let (jobs, next, path) = (jobs.clone(), next.clone(), path.to_path_buf());
        pipes.push(tokio::spawn(async move {
            let mut generator = UciEngine::new(EngineOptions::new(&path));
            let mut ana = UciEngine::new(EngineOptions::new(&path));
            let clock = crate::clock::system();
            let (mut out, mut failure) = (Vec::new(), None);
            while let Some(job) = jobs.get(next.fetch_add(1, Ordering::Relaxed)) {
                match play_and_analyse(&mut generator, &mut ana, job, &*clock).await {
                    Ok(done) => out.push(done),
                    Err(e) => {
                        failure = Some(e);
                        break;
                    }
                }
            }
            generator.close().await;
            ana.close().await;
            if let Some(e) = failure {
                panic!("engine failure: {e}");
            }
            out
        }));
    }
    let mut results = Vec::new();
    for pipe in pipes {
        results.extend(pipe.await.expect("a pipeline"));
    }
    results.sort_by_key(|(record, _)| record.id);
    results
}

/// The mean of a feature over the sides with scored moves.
fn agg(sides: &[SideFeatures], feature: impl Fn(&SideFeatures) -> Option<f64>) -> f64 {
    let values: Vec<f64> = sides.iter().filter(|s| s.n > 0).filter_map(feature).collect();
    mean(&values)
}

fn summary(sides: &[SideFeatures]) -> String {
    let moves: u32 = sides.iter().map(|s| s.n).sum();
    format!(
        "games {}, moves {moves}, accuracy {:.1}, acpl {:.1}, t1Deep {:.2}, t1Fast {:.2}, t1Complex {:.2}, \
         timeCorr {:.2}, timeCv {:.2}",
        sides.len(),
        agg(sides, |s| s.accuracy),
        agg(sides, |s| s.acpl),
        agg(sides, |s| s.t1_deep),
        agg(sides, |s| s.t1_fast),
        agg(sides, |s| s.t1_complex),
        agg(sides, |s| s.time_corr),
        agg(sides, |s| s.time_cv)
    )
}

fn side(f: &GameFeatures, user: UserId) -> SideFeatures {
    if f.white.user_id == user { f.white.clone() } else { f.black.clone() }
}

fn record(f: &GameFeatures, user: UserId) -> SideRecord {
    side_of(&f.to_json(), user).expect("a side of the game")
}

#[tokio::test(flavor = "multi_thread", worker_threads = 3)]
async fn real_engine_features_separate_an_assisted_player_from_human_stand_ins_and_only_they_are_flagged() {
    let Some(path) = engine_or_skip("real engine: features and scoring") else { return };
    let mut jobs = Vec::new();
    for i in 0..ASSISTED_GAMES {
        let cheater_white = i % 2 == 0;
        let other = 300 + i;
        jobs.push(Job {
            id: 1 + u64::from(i),
            seed: 1000 + i,
            white: if cheater_white { ASSISTED } else { DECENT },
            black: if cheater_white { DECENT } else { ASSISTED },
            white_id: if cheater_white { CHEATER } else { other },
            black_id: if cheater_white { other } else { CHEATER },
        });
    }
    for i in 0..HUMAN_GAMES {
        let k = i as usize;
        jobs.push(Job {
            id: 100 + u64::from(i),
            seed: 2000 + i,
            white: WEAK,
            black: WEAK,
            white_id: HONEST[k % 4],
            black_id: HONEST[(k + 1) % 4],
        });
    }
    let n = jobs.len();
    let started = std::time::Instant::now();
    let results = run_pool(&path, jobs).await;
    eprintln!("generated and analysed {n} games in {} ms", started.elapsed().as_millis());
    // One engine, one set of depths: one analysis profile, the one the populations below hold.
    let profile = results[0].1.profile.clone();
    assert!(results.iter().all(|(_, f)| f.profile == profile), "{profile}");
    eprintln!("profile: {profile}");

    let assisted: Vec<&(AnalysedGame, GameFeatures)> =
        results.iter().filter(|(r, _)| r.white_id == CHEATER || r.black_id == CHEATER).collect();
    let humans: Vec<&(AnalysedGame, GameFeatures)> = results.iter().filter(|(r, _)| r.id >= 100).collect();
    let cheat: Vec<SideFeatures> = assisted.iter().map(|(_, f)| side(f, CHEATER)).collect();
    let human: Vec<SideFeatures> =
        humans.iter().flat_map(|(r, f)| [side(f, r.white_id), side(f, r.black_id)]).collect();
    eprintln!("assisted: {}", summary(&cheat));
    eprintln!("humans:   {}", summary(&human));

    // 1. The per-game features separate the two groups.
    assert!(
        cheat.iter().all(|s| f64::from(s.n) >= model::MIN_MOVES_PER_GAME),
        "every assisted game has scored moves"
    );
    assert!(agg(&cheat, |s| s.accuracy) > agg(&human, |s| s.accuracy) + 8.0);
    assert!(agg(&cheat, |s| s.acpl) < 0.4 * agg(&human, |s| s.acpl));
    assert!(agg(&cheat, |s| s.t1_deep) > agg(&human, |s| s.t1_deep) + 0.2);
    assert!(agg(&cheat, |s| s.time_cv) < agg(&human, |s| s.time_cv) - 0.3);
    assert!(agg(&cheat, |s| s.time_corr) < agg(&human, |s| s.time_corr));
    let worst_assisted = cheat.iter().map(|s| s.accuracy.unwrap_or(0.0)).fold(f64::INFINITY, f64::min);
    let mut human_accuracy: Vec<f64> = human.iter().map(|s| s.accuracy.unwrap_or(0.0)).collect();
    human_accuracy.sort_by(f64::total_cmp);
    let median_human = human_accuracy[human_accuracy.len() >> 1];
    assert!(
        worst_assisted > median_human,
        "worst assisted game {worst_assisted} vs median human {median_human}"
    );

    // 2. Scoring on a fresh server (priors only): the humans are never flagged. A fixed clock
    //    keeps what the populations learn in their caches.
    let clock = ManualClock::new(0.0, NOW);
    let cheat_records: Vec<SideRecord> = assisted.iter().map(|(_, f)| record(f, CHEATER)).collect();
    let history = |uid: UserId| -> Vec<SideRecord> {
        humans
            .iter()
            .flat_map(|(r, f)| [(r.white_id, f), (r.black_id, f)])
            .filter(|(u, _)| *u == uid)
            .map(|(u, f)| record(f, u))
            .collect()
    };
    let fresh = Population::new(Some(profile.clone()), clock.clone());
    for uid in HONEST {
        let hist = history(uid);
        for k in 1..=hist.len() {
            let level = score_player(&hist[..k], &fresh, &PriorsOnly).level;
            assert_eq!(level, IntegrityLevel::None, "human {uid} after {k} games");
        }
    }
    let day_one = score_player(&cheat_records, &fresh, &PriorsOnly);
    eprintln!(
        "assisted player on a fresh server after {} games: {:?} {:?}",
        cheat_records.len(),
        day_one.level,
        day_one.groups
    );

    // 3. With the server's own population (the human games at this rating), the assisted player
    //    is flagged, but only once enough games exist; the humans still are not. (Games are only
    //    played at one rating here; they stand for the neighbouring buckets too, since z-scores
    //    take the most favourable bucket of the rating band.)
    let pop = Population::new(Some(profile.clone()), clock.clone());
    let band = model::RATING_BAND_ESTABLISHED as i64;
    for (_, f) in &humans {
        for d in [-band, 0, band] {
            let mut features = f.to_json();
            features["white"]["rating"] = json!(RATING + d);
            features["black"]["rating"] = json!(RATING + d);
            update_population_from_game(&pop, &PriorsOnly, &features, |_| IntegrityLevel::None);
        }
    }
    for uid in HONEST {
        let hist = history(uid);
        for k in 1..=hist.len() {
            let level = score_player(&hist[..k], &pop, &PriorsOnly).level;
            assert_eq!(level, IntegrityLevel::None, "human {uid} after {k} games (learned)");
        }
    }
    let mut chrono = cheat_records;
    chrono.sort_by(|a, b| a.ended_at.total_cmp(&b.ended_at));
    let levels: Vec<_> = (1..=chrono.len()).map(|k| score_player(&chrono[..k], &pop, &PriorsOnly)).collect();
    let trace: Vec<String> = levels.iter().map(|l| format!("{:?} {:.1}", l.level, l.score)).collect();
    eprintln!("assisted player, learned population: {}", trace.join(", "));
    for (k, l) in levels.iter().take(model::suspected::MIN_GAMES - 1).enumerate() {
        assert_eq!(l.level, IntegrityLevel::None, "not flagged after {} games", k + 1);
    }
    let last = levels.last().expect("assisted games");
    assert_ne!(last.level, IntegrityLevel::None, "flagged after {} games: {:?}", chrono.len(), last.groups);
    assert!(last.reasons.len() >= 3, "{:?}", last.reasons);
}

// ---- the pool --------------------------------------------------------------------------------------

/// Whether an analysis profile names the engine's networks (`nn-<12 hex digits>.nnue`, several
/// joined by `+`) and the test configuration: depths 4/8, 32 MiB of hash, analysis version 2.
fn names_the_networks(profile: &str) -> bool {
    let Some(head) = profile.strip_suffix("; depth 4/8; hash 32; analysis 2") else { return false };
    let Some((_, nets)) = head.rsplit_once("; ") else { return false };
    nets.split('+').all(|net| {
        let hex = net.strip_prefix("nn-").and_then(|n| n.strip_suffix(".nnue"));
        hex.is_some_and(|h| h.len() == 12 && h.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f')))
    })
}

#[test]
fn the_profile_of_a_real_engine_names_its_networks() {
    assert!(names_the_networks("Stockfish 16.1; nn-baff1ede1f90.nnue; depth 4/8; hash 32; analysis 2"));
    assert!(names_the_networks(
        "Stockfish 17; nn-1111cefa1111.nnue+nn-37f18f62d772.nnue; depth 4/8; hash 32; analysis 2"
    ));
    assert!(!names_the_networks("Fake Engine 1; depth 4/8; hash 32; analysis 2"));
    assert!(!names_the_networks("Stockfish 16.1; nn-BAFF1EDE1F90.nnue; depth 4/8; hash 32; analysis 2"));
    assert!(!names_the_networks("Stockfish 16.1; nn-baff1ede1f90.nnue; depth 6/10; hash 32; analysis 2"));
}

#[tokio::test]
async fn real_engine_the_pool_analyses_a_queued_game_end_to_end() {
    let Some(path) = engine_or_skip("real engine: the pool") else { return };
    let _pools = POOLS.lock().await;
    let engine = path.display().to_string();
    let config = config(&[
        ("ANALYSIS_ENGINE_PATH", engine.as_str()),
        ("ANALYSIS_WORKERS", "1"),
        ("ANALYSIS_DEPTH_FAST", "4"),
        ("ANALYSIS_DEPTH_DEEP", "8"),
        ("ANALYSIS_POLL_MS", "100"),
    ]);
    // 80 plies: the weak stand-ins' games are often decided early, and the moves of a decided
    // position are not scored; at 40 plies (at most 12 scored moves per side) a lopsided game
    // could leave both sides under the population's 10 scored moves.
    let mut generator = UciEngine::new(EngineOptions::new(&path));
    let played = play_game(&mut generator, &mut Rng::new(5), WEAK, WEAK, 80).await;
    generator.close().await;
    let played = played.expect("a game played");

    let clock = ManualClock::new(0.0, NOW);
    let store = store(&config, &clock).await;
    let ids = users(&store, &["white", "black"]).await;
    let mut g = game(ids[0], ids[1], WHITE_WINS, NOW - HOUR);
    g.category = "5+0".into();
    g.base_ms = 300_000;
    g.inc_ms = 0;
    g.clock_ms = Some(vec![0; played.moves.len()]);
    g.spent_ms = Some(played.spent_ms.clone());
    g.moves = played.moves.clone();
    let id = g.id;
    store.finish_batch(vec![g]).await.expect("game stored");
    store.analysis().enqueue(id, NOW).await.expect("job queued");

    let mut pool = AnalysisPool::start(&config, store.clone(), clock.clone());
    let end = tokio::time::Instant::now() + Duration::from_secs(50);
    while pool.stats().analysed + pool.stats().failed < 1 && tokio::time::Instant::now() < end {
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    pool.stop().await;

    let job = store.analysis().job(id).await.unwrap().expect("a job");
    assert_eq!(job.status, JobStatus::Done, "{:?}", job.error);
    let analysed = store.analysis().for_user(ids[0], 1, true).await.unwrap();
    let features = analysed[0].features.clone().expect("features");
    assert_eq!(features["plies"], json!(played.moves.len()));
    assert!(features["white"]["n"].as_u64().is_some_and(|n| n > 0));
    assert!(
        features["engine"].as_str().is_some_and(|e| e.starts_with("Stockfish")),
        "{}",
        features["engine"]
    );
    let profile = features["profile"].as_str().unwrap_or("");
    assert!(names_the_networks(profile), "the profile names the network: {profile}");
    for user in ids {
        let integrity = store.integrity().get(user).await.unwrap();
        assert_eq!(integrity.level, StoredLevel::None);
        assert!(
            integrity.evidence.is_some_and(|e| e["statistics"].is_object()),
            "integrity computed for both players"
        );
    }
    let population: i64 = store
        .read(|db| {
            db.connection()
                .query_row("SELECT count(*) FROM population_stats", [], |r| r.get(0))
                .map_err(StoreError::from)
        })
        .await
        .unwrap();
    assert!(population >= 1, "population statistics updated");
}
