//! Chess rules for the Scacelith server: board, legal moves, SAN/UCI/FEN, the position digest of
//! the realtime protocol, draw rules, PGN writer and reader. Mirrors the game's C++ rules
//! (`src/chess/chess.h`) move for move: same legal moves, same FEN normalisation (castling rights
//! without king or rook on their squares dropped, en passant square kept only when a capture is
//! legal), same automatic endings (checkmate, stalemate, dead position, fivefold repetition,
//! 75-move rule), same claims (threefold, fifty moves), same flag-fall rule (draw when the
//! opponent cannot mate), same SAN/UCI/FEN text, same Zobrist keys. DESIGN.md section 5.2.
//! Owner: chess. GPL-3.0-or-later.
//!
//! `tests/crosscheck.rs` replays `test/fixtures/chess-crosscheck.json`, generated by the game's
//! own C++ code (`tools/gen-chess-crosscheck.sh`), and requires every FEN, digest, legal move
//! list, SAN, flag and result to match.
//!
//! # Moves
//!
//! A move is the protocol `u16`: `from | to << 6 | promotion << 12` (squares a1 = 0 .. h8 = 63;
//! promotion 0, or 2 knight, 3 bishop, 4 rook, 5 queen). Castling is the king's two-square move
//! (e1g1); king-takes-rook is not castling. Legality is strict: a promotion must carry 2..5 and
//! any other move 0, bit 15 must be clear.
//!
//! ```
//! use scacelith_chess::{ChessGame, EndReason, GameStatus, MoveFlags, Position, encode_move};
//!
//! let mut game = ChessGame::default();
//! for uci in ["f2f3", "e7e5", "g2g4"] {
//!     let m = game.position().parse_uci(uci).unwrap();
//!     game.play(m).unwrap();
//! }
//! let mate = game.play(encode_move(59, 31, 0)).unwrap(); // Qh4#
//! assert_eq!(mate.flags, MoveFlags::CHECK | MoveFlags::MATE);
//! assert_eq!((mate.status, mate.reason), (GameStatus::BlackWins, EndReason::Checkmate));
//! assert_eq!(game.san_moves(), ["f3", "e5", "g4", "Qh4#"]);
//!
//! let start = Position::start();
//! assert_eq!(start.digest(), 0x3706_291C); // the protocol posHash
//! assert_eq!(start.repetition_key(), "433b89fa981aaa3c");
//! ```
//!
//! # Performance
//!
//! A `Position` is a 168-byte `Copy` value (0x88 mailbox, incremental Zobrist key). Validation
//! and play allocate nothing; see `tests/perft.rs` for the perft timing test.

mod fen;
mod game;
mod notation;
mod pgn;
mod position;
mod tables;
mod types;

pub use game::{ChessGame, InvalidEnd, InvalidFen, PlayError, PlayResult};
pub use notation::parse_san;
pub use pgn::{
    PGN_LIMITS, PgnComment, PgnError, PgnGame, PgnLimits, PgnTags, normalize_result, read_pgn, read_pgn_bytes,
};
pub use position::{IllegalMove, MAX_PERFT_DEPTH, PerftDepthError, Position, START_FEN};
pub use types::{
    Color, EndReason, GameStatus, MoveFlags, Piece, PieceType, castling, encode_move, fnv1a32, move_from,
    move_promotion, move_to, move_uci, parse_square, square_name,
};
