//! C++17 emitter: the game client's codec `src/net/protocol_gen.h` / `protocol_gen.cpp`
//! (namespace `net::proto`), with the API the game has always used: `encode`, `decode`, `valid`,
//! `peekType`, `messageName`, `isValid`, `enumName`, `visitFields`, `withMessage`.

use super::model::{Dir, Field, Message, Schema, Type};
use super::text::Lines;

const BANNER: &str = "// Scacelith realtime protocol v1 codec (C++17): generated by protogen from\n\
// dedicated-server/protocol/scacelith-v1.json, do not edit. Regenerate with\n\
// `cargo run -p scacelith-protocol --features gen --bin protogen` in dedicated-server/.\n";

fn cpp_type(ty: &Type) -> String {
    match ty {
        Type::U8 => "uint8_t".into(),
        Type::U16 => "uint16_t".into(),
        Type::U32 => "uint32_t".into(),
        Type::U64 | Type::Id53 => "uint64_t".into(),
        Type::I32 => "int32_t".into(),
        Type::F64 => "double".into(),
        Type::Bool => "bool".into(),
        Type::Str8 => "std::string".into(),
        Type::Enum(name) | Type::Struct(name) => name.clone(),
        Type::List(item) => format!("std::vector<{}>", cpp_type(item)),
    }
}

fn cpp_default(schema: &Schema, ty: &Type) -> String {
    match ty {
        Type::U8 | Type::U16 | Type::U32 | Type::U64 | Type::Id53 | Type::I32 => " = 0".into(),
        Type::F64 => " = 0.0".into(),
        Type::Bool => " = false".into(),
        Type::Enum(name) => format!(" = {name}::{}", schema.enum_(name).values[0].name),
        _ => String::new(),
    }
}

fn int_lit(v: i64, ty: &Type) -> String {
    match ty {
        Type::I32 if v == i64::from(i32::MIN) => "-2147483647 - 1".into(),
        Type::I32 => v.to_string(),
        _ if v > 0xffff => format!("{v:#x}u"),
        _ => format!("{v}u"),
    }
}

fn trailing_comment(f: &Field) -> String {
    let mut parts = Vec::new();
    if let Some(min) = f.min {
        parts.push(format!("min {min}"));
    }
    if let Some(max) = f.max {
        parts.push(format!("max {max}"));
    }
    if parts.is_empty() { String::new() } else { format!("  // {}", parts.join(", ")) }
}

fn put(f: &Field, ty: &Type, v: &str, ind: &str) -> String {
    match ty {
        Type::U8 => format!("{ind}w.u8({v});"),
        Type::Bool => format!("{ind}w.u8({v} ? 1 : 0);"),
        Type::Enum(_) => format!("{ind}w.u8(uint8_t({v}));"),
        Type::U16 => format!("{ind}w.u16({v});"),
        Type::U32 => format!("{ind}w.u32({v});"),
        Type::I32 => format!("{ind}w.u32(uint32_t({v}));"),
        Type::U64 | Type::Id53 => format!("{ind}w.u64({v});"),
        Type::F64 => format!("{ind}w.f64({v});"),
        Type::Str8 => format!("{ind}w.str8({v}, {});", f.hi()),
        Type::Struct(_) => format!("{ind}put(w, {v});"),
        Type::List(item) => {
            let max = f.hi();
            let item_field = Field {
                name: f.name.clone(),
                ty: (**item).clone(),
                min: None,
                max: None,
                doc: String::new(),
            };
            [
                format!("{ind}{{"),
                format!("{ind}    const size_t count = {v}.size() < {max} ? {v}.size() : {max};"),
                format!("{ind}    w.u16(uint16_t(count));"),
                format!("{ind}    for (size_t i = 0; i < count; ++i) {{"),
                put(&item_field, item, &format!("{v}[i]"), &format!("{ind}        ")),
                format!("{ind}    }}"),
                format!("{ind}}}"),
            ]
            .join("\n")
        }
    }
}

fn get(schema: &Schema, f: &Field, ty: &Type, v: &str) -> String {
    match ty {
        Type::U8 | Type::U16 | Type::U32 | Type::I32 => {
            let name = match ty {
                Type::U8 => "u8",
                Type::U16 => "u16",
                Type::U32 => "u32",
                _ => "i32",
            };
            format!("r.{name}({v}, {}, {})", int_lit(f.lo(), ty), int_lit(f.hi(), ty))
        }
        Type::U64 => format!("r.u64({v})"),
        Type::Bool => format!("r.boolean({v})"),
        Type::Enum(name) => format!("r.enumeration({v}, {})", schema.enum_(name).open),
        Type::F64 => format!("r.f64({v})"),
        Type::Id53 => format!("r.id53({v})"),
        Type::Str8 => format!("r.str8({v}, {}, {})", f.lo(), f.hi()),
        Type::Struct(_) => format!("get(r, {v})"),
        Type::List(item) => {
            let item_field = Field {
                name: f.name.clone(),
                ty: (**item).clone(),
                min: None,
                max: None,
                doc: String::new(),
            };
            format!(
                "r.list({v}, {}, {}, [](Reader& r, {}& x) {{ return {}; }})",
                f.hi(),
                schema.item_min_size(item),
                cpp_type(item),
                get(schema, &item_field, item, "x")
            )
        }
    }
}

fn check(f: &Field, ty: &Type, v: &str) -> Option<String> {
    match ty {
        Type::U8 | Type::U16 | Type::U32 | Type::I32 => {
            let mut parts = Vec::new();
            if let Some(min) = f.min {
                parts.push(format!("{v} >= {}", int_lit(min, ty)));
            }
            if let Some(max) = f.max {
                parts.push(format!("{v} <= {}", int_lit(max, ty)));
            }
            if parts.is_empty() { None } else { Some(parts.join(" && ")) }
        }
        Type::U64 | Type::Bool => None,
        Type::Enum(_) => Some(format!("isValid({v})")),
        Type::F64 => Some(format!("std::isfinite({v})")),
        Type::Id53 => Some(format!("{v} < kId53Limit")),
        Type::Str8 => Some(format!("validStr({v}, {}, {})", f.lo(), f.hi())),
        Type::Struct(_) => Some(format!("valid({v})")),
        Type::List(item) => {
            let item_field = Field {
                name: f.name.clone(),
                ty: (**item).clone(),
                min: None,
                max: None,
                doc: String::new(),
            };
            let size = format!("{v}.size() <= {}", f.hi());
            match check(&item_field, item, "x") {
                None => Some(size),
                Some(c) => {
                    Some(format!("{size} && allOf({v}, [](const {}& x) {{ return {c}; }})", cpp_type(item)))
                }
            }
        }
    }
}

/// Writes `protocol_gen.h`.
pub fn header(schema: &Schema) -> String {
    let mut o = Lines::new();
    o.raw(BANNER);
    o.line("//");
    o.line("// Wire format and semantics: dedicated-server/docs/PROTOCOL.md.");
    o.line(
        "//   encode(m, out)        appends the message (type byte + fields, little-endian) to out. Strings",
    );
    o.line("//                         longer than their bound are cut and lists longer than theirs are");
    o.line(
        "//                         shortened so the frame stays well formed; check valid(m) first when the",
    );
    o.line("//                         values come from user input.");
    o.line(
        "//   decode(p, n, out)     false on a malformed message; out may be partly written. Client messages",
    );
    o.line(
        "//                         (received by a server or a direct-match host) decode strictly. Server",
    );
    o.line(
        "//                         messages decode leniently, as a client must: trailing bytes (fields of",
    );
    o.line("//                         a later minor) are ignored and open enums keep the values this codec");
    o.line("//                         does not know (isValid() is false for them).");
    o.line("//   decodeHello(p, n, h)  a Hello as a server reads it: strict, except that a Hello of a later");
    o.line("//                         minor may carry fields this codec does not know.");
    o.line("//   valid(m)              true when m holds only values a sender may send (decode(encode(m))");
    o.line("//                         then gives m back).");
    o.line("//   peekType(p, n, t)     type of a message (false when empty or unknown).");
    o.line("//   peekSeq(p, n, seq)    seq of a client message (bytes 1..4) without decoding it.");
    o.line("#pragma once");
    o.line("#include <cstddef>");
    o.line("#include <cstdint>");
    o.line("#include <string>");
    o.line("#include <vector>");
    o.line("");
    o.line("// X11 defines None as a macro; enum values below are called None.");
    o.line("#pragma push_macro(\"None\")");
    o.line("#undef None");
    o.line("");
    o.line("namespace net {");
    o.line("namespace proto {");
    o.line("");
    let caps: u64 = schema.caps.iter().map(|c| 1u64 << c.bit).sum();
    o.line(&format!(
        "constexpr uint16_t kProtocolVersion = {};   // Hello.proto, Welcome.proto",
        schema.protocol
    ));
    o.line(&format!(
        "constexpr uint16_t kMinor = {};             // the minor this codec speaks",
        schema.minor
    ));
    o.line(&format!(
        "constexpr uint64_t kCaps = {caps:#x}ull;           // capability bits this codec knows"
    ));
    o.line(&format!(
        "constexpr uint32_t kFingerprint = {:#010x}u;   // schema fingerprint (informational)",
        schema.fingerprint
    ));
    o.line(&format!("constexpr const char* kWsSubprotocol = {:?};", schema.subprotocol));
    o.line("constexpr uint64_t kId53Limit = 1ull << 53;   // id53 values are below 2^53");
    for c in &schema.constants {
        o.comment(&c.doc, "");
        o.line(&format!("constexpr size_t k{} = {};", c.name, c.value));
    }
    o.line("// Size of the Hello prefix (type, seq, proto, minor, caps), frozen for every version.");
    o.line("constexpr size_t kHelloPrefixSize = 17;");
    o.line("");
    if !schema.caps.is_empty() {
        o.line("// Capability bits.");
        o.line("namespace Cap {");
        for c in &schema.caps {
            o.line(&format!("constexpr uint64_t {} = 1ull << {};", c.name, c.bit));
        }
        o.line("}  // namespace Cap");
        o.line("");
    }
    o.line("// ---- enums (u8 on the wire) ----");
    o.line("// Open enums (EndReason, GameEventKind...) may gain values in a later minor: a server message");
    o.line(
        "// keeps such a value (isValid() false) and the receiver applies the fallback of docs/PROTOCOL.md.",
    );
    for e in &schema.enums {
        let items: Vec<String> = e.values.iter().map(|v| format!("{} = {}", v.name, v.value)).collect();
        let kind = if e.open { "open" } else { "closed" };
        let one = format!("enum class {} : uint8_t {{ {} }};   // {kind}", e.name, items.join(", "));
        if one.len() <= 110 {
            o.line(&one);
        } else {
            o.line(&format!("enum class {} : uint8_t {{   // {kind}", e.name));
            let mut line = String::from("   ");
            for it in &items {
                if line.len() + it.len() + 2 > 104 {
                    o.line(&line);
                    line = String::from("   ");
                }
                line.push(' ');
                line.push_str(it);
                line.push(',');
            }
            o.line(&line);
            o.line("};");
        }
    }
    o.line("");
    o.line("// Membership of the schema enums, and their value names (\"?\" when not a member).");
    for e in &schema.enums {
        o.line(&format!("bool isValid({} v);", e.name));
    }
    for e in &schema.enums {
        o.line(&format!("const char* enumName({} v);", e.name));
    }
    o.line("");
    for f in &schema.flags {
        o.comment(&f.doc, "");
        o.line(&format!("namespace {} {{", f.name));
        for b in &f.bits {
            o.line(&format!("constexpr uint8_t {} = {};", b.name, b.value));
        }
        o.line(&format!("}}  // namespace {}", f.name));
        o.line("");
    }
    o.line(
        "// WebSocket close codes. A fatal Error with code c is followed by close 4000 + c (c in 1..99) or",
    );
    o.line("// 4300 + (c - 240) (c in 240..255); 4303 (SlowConsumer) comes without an Error.");
    o.line("namespace CloseCode {");
    for c in &schema.close_codes {
        o.line(&format!("constexpr uint16_t {} = {};", c.name, c.code));
    }
    o.line("}  // namespace CloseCode");
    o.line("// Close code that follows a fatal Error with this code (0 when this code is never fatal).");
    o.line("uint16_t closeCodeFor(ErrorCode code);");
    o.line("");
    o.line("// ---- message types (0x01-0x7F client -> server, 0x80-0xFF server -> client) ----");
    o.line("enum class MsgType : uint8_t {");
    for m in &schema.messages {
        o.line(&format!("    {} = {:#04X},", m.key, m.id).replace("0X", "0x"));
    }
    o.line("};");
    o.line("const char* messageName(MsgType t);     // \"Move\", \"S_Ping\"...; nullptr when unknown");
    o.line("inline bool isClientType(uint8_t t) { return t >= 0x01 && t <= 0x7F; }");
    o.line("bool peekType(const uint8_t* p, size_t n, MsgType& t);");
    o.line("bool peekSeq(const uint8_t* p, size_t n, uint32_t& seq);");
    o.line("");
    o.line("// The frozen start of every Hello, readable whatever the rest of the message.");
    o.line("struct HelloPrefix {");
    o.line("    uint32_t seq = 0;");
    o.line("    uint16_t proto = 0;");
    o.line("    uint16_t minor = 0;");
    o.line("    uint64_t caps = 0;");
    o.line("};");
    o.line("bool readHelloPrefix(const uint8_t* p, size_t n, HelloPrefix& out);");
    o.line("");
    o.line("// ---- structs ----");
    for s in &schema.structs {
        o.comment(&s.doc, "");
        o.line(&format!("struct {} {{", s.name));
        for f in &s.fields {
            o.line(&format!(
                "    {} {}{};{}",
                cpp_type(&f.ty),
                f.name,
                cpp_default(schema, &f.ty),
                trailing_comment(f)
            ));
        }
        o.line("};");
    }
    o.line("");
    o.line("// ---- messages ----");
    for m in &schema.messages {
        o.comment(&m.doc, "");
        o.line(&format!("struct {} {{", m.key));
        o.line(&format!("    static constexpr MsgType kType = MsgType::{};", m.key));
        o.line(&format!("    static constexpr bool kClientToServer = {};", m.dir == Dir::C2s));
        for f in &m.fields {
            o.line(&format!(
                "    {} {}{};{}",
                cpp_type(&f.ty),
                f.name,
                cpp_default(schema, &f.ty),
                trailing_comment(f)
            ));
        }
        o.line("};");
    }
    o.line("");
    o.line("// ---- codec ----");
    for s in &schema.structs {
        o.line(&format!("bool valid(const {}& s);", s.name));
    }
    for m in &schema.messages {
        o.line(&format!("void encode(const {}& m, std::vector<uint8_t>& out);", m.key));
        o.line(&format!("bool decode(const uint8_t* p, size_t n, {}& out);", m.key));
        o.line(&format!("bool valid(const {}& m);", m.key));
    }
    o.line("bool decodeHello(const uint8_t* p, size_t n, Hello& out);");
    o.line("");
    o.line("// ---- reflection (tests, logs): v(name, field) for every field, in wire order ----");
    let visit = |o: &mut Lines, name: &str, fields: &[Field]| {
        for cq in ["", "const "] {
            o.line(&format!("template <class V> void visitFields({cq}{name}& m, V&& v) {{"));
            for f in fields {
                o.line(&format!("    v(\"{}\", m.{});", f.name, f.name));
            }
            o.line("}");
        }
    };
    for s in &schema.structs {
        visit(&mut o, &s.name, &s.fields);
    }
    for m in &schema.messages {
        visit(&mut o, &m.key, &m.fields);
    }
    o.line("");
    o.line("// Calls f(msg) with a default-constructed message of type t; false when t is unknown.");
    o.line("template <class F> bool withMessage(MsgType t, F&& f) {");
    o.line("    switch (t) {");
    for m in &schema.messages {
        o.line(&format!("    case MsgType::{0}: {{ {0} m; f(m); return true; }}", m.key));
    }
    o.line("    }");
    o.line("    return false;");
    o.line("}");
    o.line("");
    o.line("}  // namespace proto");
    o.line("}  // namespace net");
    o.line("");
    o.line("#pragma pop_macro(\"None\")");
    o.finish()
}

const RUNTIME: &str = r#"namespace {

// Appends little-endian values.
class Writer {
public:
    explicit Writer(std::vector<uint8_t>& out) : o_(out) {}
    void u8(uint8_t v) { o_.push_back(v); }
    void u16(uint16_t v) { o_.push_back(uint8_t(v)); o_.push_back(uint8_t(v >> 8)); }
    void u32(uint32_t v) { for (int i = 0; i < 4; ++i) o_.push_back(uint8_t(v >> (8 * i))); }
    void u64(uint64_t v) { for (int i = 0; i < 8; ++i) o_.push_back(uint8_t(v >> (8 * i))); }
    // -0 is written as +0 (encodings are canonical).
    void f64(double v) {
        if (v == 0.0) v = 0.0;
        uint64_t bits;
        std::memcpy(&bits, &v, 8);
        u64(bits);
    }
    // Cut to 'max' bytes without splitting a UTF-8 sequence (only reached with invalid input).
    void str8(const std::string& s, size_t max) {
        size_t n = s.size();
        if (n > max) {
            n = max;
            while (n > 0 && (uint8_t(s[n]) & 0xC0) == 0x80) --n;
        }
        u8(uint8_t(n));
        o_.insert(o_.end(), s.begin(), s.begin() + std::ptrdiff_t(n));
    }

private:
    std::vector<uint8_t>& o_;
};

// Strict UTF-8 (no overlong forms, no surrogates, <= U+10FFFF), and no NUL byte.
bool utf8NoNul(const uint8_t* s, size_t n) {
    size_t i = 0;
    while (i < n) {
        uint8_t c = s[i];
        if (c == 0) return false;
        if (c < 0x80) { ++i; continue; }
        size_t len;
        uint32_t cp, min;
        if ((c & 0xE0) == 0xC0) { len = 2; cp = c & 0x1F; min = 0x80; }
        else if ((c & 0xF0) == 0xE0) { len = 3; cp = c & 0x0F; min = 0x800; }
        else if ((c & 0xF8) == 0xF0) { len = 4; cp = c & 0x07; min = 0x10000; }
        else return false;
        if (i + len > n) return false;
        for (size_t k = 1; k < len; ++k) {
            uint8_t cc = s[i + k];
            if ((cc & 0xC0) != 0x80) return false;
            cp = (cp << 6) | (cc & 0x3F);
        }
        if (cp < min || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += len;
    }
    return true;
}

bool validStr(const std::string& s, size_t min, size_t max) {
    return s.size() >= min && s.size() <= max && utf8NoNul(reinterpret_cast<const uint8_t*>(s.data()), s.size());
}

template <class T, class P> bool allOf(const std::vector<T>& v, P pred) {
    for (const T& x : v)
        if (!pred(x)) return false;
    return true;
}

// Bounds-checked little-endian reader; every accessor fails on truncation or a bad value. A
// lenient reader (server messages) accepts trailing bytes and unknown values of open enums.
class Reader {
public:
    Reader(const uint8_t* p, size_t n, bool lenient) : p_(p), n_(p ? n : 0), lenient_(lenient) {}
    bool type(MsgType t) {
        if (n_ < 1 || p_[0] != uint8_t(t)) return false;
        o_ = 1;
        return true;
    }
    bool end() const { return lenient_ || o_ == n_; }
    bool u8(uint8_t& v, uint32_t lo, uint32_t hi) {
        if (n_ - o_ < 1) return false;
        v = p_[o_++];
        return v >= lo && v <= hi;
    }
    bool u16(uint16_t& v, uint32_t lo, uint32_t hi) {
        if (n_ - o_ < 2) return false;
        v = uint16_t(p_[o_] | (p_[o_ + 1] << 8));
        o_ += 2;
        return v >= lo && v <= hi;
    }
    bool u32(uint32_t& v, uint32_t lo, uint32_t hi) {
        if (!raw32(v)) return false;
        return v >= lo && v <= hi;
    }
    bool i32(int32_t& v, int32_t lo, int32_t hi) {
        uint32_t u;
        if (!raw32(u)) return false;
        v = int32_t(u);
        return v >= lo && v <= hi;
    }
    bool u64(uint64_t& v) { return raw64(v); }
    bool id53(uint64_t& v) {
        if (!raw64(v)) return false;
        return v < kId53Limit;
    }
    bool f64(double& v) {
        uint64_t bits;
        if (!raw64(bits)) return false;
        std::memcpy(&v, &bits, 8);
        return std::isfinite(v);
    }
    bool boolean(bool& v) {
        if (n_ - o_ < 1) return false;
        uint8_t b = p_[o_++];
        v = b == 1;
        return b <= 1;
    }
    template <class E> bool enumeration(E& v, bool open) {
        if (n_ - o_ < 1) return false;
        v = E(p_[o_++]);
        return isValid(v) || (open && lenient_);
    }
    bool str8(std::string& v, size_t min, size_t max) {
        if (n_ - o_ < 1) return false;
        size_t len = p_[o_++];
        if (len < min || len > max || n_ - o_ < len) return false;
        if (!utf8NoNul(p_ + o_, len)) return false;
        v.assign(reinterpret_cast<const char*>(p_ + o_), len);
        o_ += len;
        return true;
    }
    // The count is checked against max and against the bytes left before anything is allocated.
    template <class T, class F> bool list(std::vector<T>& v, size_t max, size_t itemSize, F item) {
        uint16_t count;
        if (!u16(count, 0, 0xFFFF) || count > max || size_t(count) * itemSize > n_ - o_) return false;
        v.clear();
        v.resize(count);
        for (T& x : v)
            if (!item(*this, x)) return false;
        return true;
    }

private:
    bool raw32(uint32_t& v) {
        if (n_ - o_ < 4) return false;
        v = uint32_t(p_[o_]) | uint32_t(p_[o_ + 1]) << 8 | uint32_t(p_[o_ + 2]) << 16 | uint32_t(p_[o_ + 3]) << 24;
        o_ += 4;
        return true;
    }
    bool raw64(uint64_t& v) {
        uint32_t lo, hi;
        if (!raw32(lo) || !raw32(hi)) return false;
        v = uint64_t(hi) << 32 | lo;
        return true;
    }
    const uint8_t* p_;
    size_t n_, o_ = 0;
    bool lenient_;
};

}  // namespace"#;

/// Writes `protocol_gen.cpp`.
pub fn source(schema: &Schema) -> String {
    let mut o = Lines::new();
    o.raw(BANNER);
    o.line("#include \"protocol_gen.h\"");
    o.line("#include <cmath>");
    o.line("#include <cstring>");
    o.line("");
    o.line("#pragma push_macro(\"None\")");
    o.line("#undef None");
    o.line("");
    o.line("namespace net {");
    o.line("namespace proto {");
    o.line("");
    o.line("// ---- enums ----");
    for e in &schema.enums {
        o.line(&format!("bool isValid({} v) {{", e.name));
        o.line("    switch (v) {");
        for v in &e.values {
            o.line(&format!("    case {}::{}:", e.name, v.name));
        }
        o.line("        return true;");
        o.line("    }");
        o.line("    return false;");
        o.line("}");
        o.line(&format!("const char* enumName({} v) {{", e.name));
        o.line("    switch (v) {");
        for v in &e.values {
            o.line(&format!("    case {0}::{1}: return \"{1}\";", e.name, v.name));
        }
        o.line("    }");
        o.line("    return \"?\";");
        o.line("}");
    }
    o.line("");
    o.line("uint16_t closeCodeFor(ErrorCode code) {");
    o.line("    const unsigned c = unsigned(code);");
    o.line("    if (c >= 1 && c <= 99) return uint16_t(4000 + c);");
    o.line("    if (c >= 240) return uint16_t(4300 + (c - 240));");
    o.line("    return 0;");
    o.line("}");
    o.line("");
    o.line("const char* messageName(MsgType t) {");
    o.line("    switch (t) {");
    for m in &schema.messages {
        o.line(&format!("    case MsgType::{0}: return \"{0}\";", m.key));
    }
    o.line("    }");
    o.line("    return nullptr;");
    o.line("}");
    o.line("");
    o.line("bool peekType(const uint8_t* p, size_t n, MsgType& t) {");
    o.line("    if (!p || n < 1 || !messageName(MsgType(p[0]))) return false;");
    o.line("    t = MsgType(p[0]);");
    o.line("    return true;");
    o.line("}");
    o.line("");
    o.line("bool peekSeq(const uint8_t* p, size_t n, uint32_t& seq) {");
    o.line("    if (!p || n < 5 || !isClientType(p[0])) return false;");
    o.line("    seq = uint32_t(p[1]) | uint32_t(p[2]) << 8 | uint32_t(p[3]) << 16 | uint32_t(p[4]) << 24;");
    o.line("    return true;");
    o.line("}");
    o.line("");
    o.line("bool readHelloPrefix(const uint8_t* p, size_t n, HelloPrefix& out) {");
    o.line("    if (!p || n < kHelloPrefixSize || p[0] != uint8_t(MsgType::Hello)) return false;");
    o.line("    auto le = [p](size_t at, size_t len) {");
    o.line("        uint64_t v = 0;");
    o.line("        for (size_t i = 0; i < len; ++i) v |= uint64_t(p[at + i]) << (8 * i);");
    o.line("        return v;");
    o.line("    };");
    o.line("    out.seq = uint32_t(le(1, 4));");
    o.line("    out.proto = uint16_t(le(5, 2));");
    o.line("    out.minor = uint16_t(le(7, 2));");
    o.line("    out.caps = le(9, 8);");
    o.line("    return true;");
    o.line("}");
    o.line("");
    o.line(RUNTIME);
    o.line("");
    o.line("// ---- structs and message fields ----");
    o.line("namespace {");
    for s in &schema.structs {
        o.line(&format!("void put(Writer& w, const {}& s);", s.name));
        o.line(&format!("bool get(Reader& r, {}& s);", s.name));
    }
    o.line("");
    for s in &schema.structs {
        o.line(&format!("void put(Writer& w, const {}& s) {{", s.name));
        for f in &s.fields {
            o.line(&put(f, &f.ty, &format!("s.{}", f.name), "    "));
        }
        o.line("}");
        o.line(&format!("bool get(Reader& r, {}& s) {{", s.name));
        let gets: Vec<String> =
            s.fields.iter().map(|f| get(schema, f, &f.ty, &format!("s.{}", f.name))).collect();
        o.line(&format!("    return {};", gets.join(" &&\n           ")));
        o.line("}");
    }
    for m in &schema.messages {
        o.line(&format!("bool getFields(Reader& r, {}& out) {{", m.key));
        let gets: Vec<String> =
            m.fields.iter().map(|f| get(schema, f, &f.ty, &format!("out.{}", f.name))).collect();
        o.line(&format!("    return {};", gets.join(" &&\n           ")));
        o.line("}");
    }
    o.line("}  // namespace");
    o.line("");
    for s in &schema.structs {
        let checks: Vec<String> =
            s.fields.iter().filter_map(|f| check(f, &f.ty, &format!("s.{}", f.name))).collect();
        o.line(&format!("bool valid(const {}& s) {{", s.name));
        if checks.is_empty() {
            o.line("    (void)s;");
            o.line("    return true;");
        } else {
            o.line(&format!("    return {};", checks.join(" &&\n           ")));
        }
        o.line("}");
    }
    o.line("");
    o.line("// ---- messages ----");
    for m in &schema.messages {
        message(m, &mut o);
    }
    o.line("bool decodeHello(const uint8_t* p, size_t n, Hello& out) {");
    o.line("    HelloPrefix prefix;");
    o.line("    if (!readHelloPrefix(p, n, prefix)) return false;");
    o.line("    if (prefix.minor <= kMinor) return decode(p, n, out);   // no field of a later minor");
    o.line("    Reader r(p, n, false);");
    o.line("    return r.type(MsgType::Hello) && getFields(r, out);   // fields of a later minor follow");
    o.line("}");
    o.line("");
    o.line("}  // namespace proto");
    o.line("}  // namespace net");
    o.line("");
    o.line("#pragma pop_macro(\"None\")");
    o.finish()
}

fn message(m: &Message, o: &mut Lines) {
    let n = &m.key;
    o.line(&format!("void encode(const {n}& m, std::vector<uint8_t>& out) {{"));
    o.line("    Writer w(out);");
    o.line(&format!("    w.u8(uint8_t(MsgType::{n}));"));
    for f in &m.fields {
        o.line(&put(f, &f.ty, &format!("m.{}", f.name), "    "));
    }
    o.line("}");
    o.line(&format!("bool decode(const uint8_t* p, size_t n, {n}& out) {{"));
    o.line(&format!("    Reader r(p, n, {});", m.dir == Dir::S2c));
    o.line(&format!("    return r.type(MsgType::{n}) && getFields(r, out) && r.end();"));
    o.line("}");
    let checks: Vec<String> =
        m.fields.iter().filter_map(|f| check(f, &f.ty, &format!("m.{}", f.name))).collect();
    o.line(&format!("bool valid(const {n}& m) {{"));
    if checks.is_empty() {
        o.line("    (void)m;");
        o.line("    return true;");
    } else {
        o.line(&format!("    return {};", checks.join(" &&\n           ")));
    }
    o.line("}");
}
