//! Rust emitter: `src/gen.rs` (the codec) and `src/gen_json.rs` (the JSON form of the messages,
//! for the crate's tests).

use std::fmt::Write as _;

use super::model::{Dir, Enum, Field, Message, Schema, Struct, Type};
use super::text::{Lines, screaming, snake};

const HEADER: &str = "// @generated by protogen from protocol/scacelith-v1.json: do not edit. Regenerate with\n\
// `cargo run -p scacelith-protocol --features gen --bin protogen`.\n";

const KEYWORDS: &[&str] = &[
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false",
    "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where", "while", "gen",
    "box", "try", "yield",
];

/// Rust identifier of a field.
fn ident(name: &str) -> String {
    let s = snake(name);
    if KEYWORDS.contains(&s.as_str()) { format!("r#{s}") } else { s }
}

/// Rust type name of a message: `ClientPing` / `ServerPing` when both directions use the name.
pub fn type_name(m: &Message) -> String {
    match (m.shared, m.dir) {
        (false, _) => m.name.clone(),
        (true, Dir::C2s) => format!("Client{}", m.name),
        (true, Dir::S2c) => format!("Server{}", m.name),
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::U8 => "u8".into(),
        Type::U16 => "u16".into(),
        Type::U32 => "u32".into(),
        Type::U64 | Type::Id53 => "u64".into(),
        Type::I32 => "i32".into(),
        Type::F64 => "f64".into(),
        Type::Bool => "bool".into(),
        Type::Str8 => "String".into(),
        Type::Enum(name) | Type::Struct(name) => name.clone(),
        Type::List(item) => format!("Vec<{}>", rust_type(item)),
    }
}

/// Bounds of a field, as documentation.
fn bounds_doc(f: &Field) -> Option<String> {
    match &f.ty {
        Type::Str8 => Some(format!("{}..={} bytes of UTF-8 without NUL", f.lo(), f.hi())),
        Type::List(_) => Some(format!("at most {} items", f.hi())),
        Type::Id53 => Some("below 2^53".into()),
        Type::F64 => Some("finite".into()),
        _ if f.is_bounded() => Some(format!("{}..={}", f.lo(), f.hi())),
        _ => None,
    }
}

fn field_doc(f: &Field) -> String {
    let mut doc = match f.description() {
        "" => format!("`{}`", f.name),
        text => capitalize(text),
    };
    if let Some(b) = bounds_doc(f) {
        let _ = write!(doc, " ({b})");
    }
    if !doc.ends_with('.') {
        doc.push('.');
    }
    doc
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    c.next().map_or_else(String::new, |first| first.to_uppercase().collect::<String>() + c.as_str())
}

fn sentence(s: &str) -> String {
    let s = capitalize(s);
    if s.ends_with('.') { s } else { format!("{s}.") }
}

/// Writes `gen.rs`.
pub fn codec(schema: &Schema) -> String {
    let mut o = Lines::new();
    o.raw(HEADER);
    o.line("");
    o.line("//! Generated codec of protocol v1: constants, enums, structs, messages, and their encoders and");
    o.line("//! decoders. See the crate documentation for the API and `docs/PROTOCOL.md` for the semantics.");
    o.line("");
    o.line("use bytes::BufMut;");
    o.line("");
    o.line("use crate::Message;");
    o.line("use crate::wire::{self, DecodeError, Defect, EncodeError, Reader};");
    o.line("");
    constants(schema, &mut o);
    for e in &schema.enums {
        enum_(e, &mut o);
    }
    for s in &schema.structs {
        struct_(s, &mut o);
    }
    msg_type(schema, &mut o);
    for m in &schema.messages {
        message(schema, m, &mut o);
    }
    msg_enum(schema, Dir::C2s, &mut o);
    msg_enum(schema, Dir::S2c, &mut o);
    o.finish()
}

fn constants(schema: &Schema, o: &mut Lines) {
    o.line("/// Major protocol version (`Hello.proto`, `Welcome.proto`).");
    o.line(&format!("pub const PROTOCOL_VERSION: u16 = {};", schema.protocol));
    o.line("/// Minor version of this codec: the `Hello.minor` it sends, the highest minor it decodes.");
    o.line(&format!("pub const MINOR: u16 = {};", schema.minor));
    o.line("/// WebSocket subprotocol token (`Sec-WebSocket-Protocol`).");
    o.line(&format!("pub const SUBPROTOCOL: &str = {:?};", schema.subprotocol));
    o.line("/// Fingerprint of the schema (first 4 bytes of SHA-256 of its canonical form): informational.");
    o.line(&format!("pub const FINGERPRINT: u32 = {:#010x};", schema.fingerprint));
    o.line("/// Capability bits this codec knows (`Hello.caps`, `Welcome.caps`).");
    let caps: u64 = schema.caps.iter().map(|c| 1u64 << c.bit).sum();
    o.line(&format!("pub const CAPS: u64 = {caps:#x};"));
    for c in &schema.constants {
        o.doc(&sentence(&c.doc), "");
        o.line(&format!("pub const {}: usize = {};", screaming(&c.name), c.value));
    }
    o.line("");
    if !schema.caps.is_empty() {
        o.line("/// Capability bits.");
        o.line("pub mod caps {");
        for c in &schema.caps {
            o.doc(&sentence(&c.doc), "    ");
            o.line(&format!("    pub const {}: u64 = 1 << {};", screaming(&c.name), c.bit));
        }
        o.line("}");
        o.line("");
    }
    for f in &schema.flags {
        o.doc(&sentence(&f.doc), "");
        o.line(&format!("pub mod {} {{", snake(&f.name)));
        for b in &f.bits {
            o.doc(&if b.doc.is_empty() { format!("`{}`.", b.name) } else { sentence(&b.doc) }, "    ");
            o.line(&format!("    pub const {}: u8 = {:#04x};", screaming(&b.name), b.value));
        }
        o.line("}");
        o.line("");
    }
    o.line("/// WebSocket close codes. A fatal `Error` with code `c` is followed by close `4000 + c` (c in 1..=99)");
    o.line("/// or `4300 + (c - 240)` (c in 240..=255): see [`crate::close_code_for`].");
    o.line("pub mod close {");
    for c in &schema.close_codes {
        let doc = match (&c.error, c.doc.is_empty()) {
            (Some(e), true) => format!("After a fatal `Error` {e}."),
            (Some(e), false) => format!("After a fatal `Error` {e}: {}", sentence(&c.doc)),
            (None, _) => sentence(&c.doc),
        };
        o.doc(&doc, "    ");
        o.line(&format!("    pub const {}: u16 = {};", screaming(&c.name), c.code));
    }
    o.line("}");
    o.line("");
}

fn enum_(e: &Enum, o: &mut Lines) {
    let mut doc = sentence(&e.doc);
    if e.open {
        let _ = write!(
            doc,
            "\n\nOpen enum: a later minor may add values, which decode as `Unknown` (a receiver should {}).",
            e.unknown_doc
        );
    } else {
        doc.push_str("\n\nClosed enum: any other value is malformed.");
    }
    if !e.reserved.is_empty() {
        let list: Vec<String> = e.reserved.iter().map(|v| format!("{} ({})", v.value, v.name)).collect();
        let _ = write!(doc, " Retired values, never reused: {}.", list.join(", "));
    }
    o.doc(&doc, "");
    o.line("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]");
    if !e.open {
        o.line("#[repr(u8)]");
    }
    o.line(&format!("pub enum {} {{", e.name));
    for (i, v) in e.values.iter().enumerate() {
        o.doc(
            &if v.doc.is_empty() { format!("`{}` ({}).", v.name, v.value) } else { sentence(&v.doc) },
            "    ",
        );
        if i == 0 {
            o.line("    #[default]");
        }
        if e.open {
            o.line(&format!("    {},", v.name));
        } else {
            o.line(&format!("    {} = {},", v.name, v.value));
        }
    }
    if e.open {
        o.line("    /// A value this codec does not know (sent by a later minor).");
        o.line("    Unknown(u8),");
    }
    o.line("}");
    o.line("");
    let n = e.values.len();
    let all: Vec<String> = e.values.iter().map(|v| format!("Self::{}", v.name)).collect();
    o.line(&format!("impl {} {{", e.name));
    o.line("    /// Every member, in schema order.");
    o.line(&format!("    pub const ALL: [Self; {n}] = [{}];", all.join(", ")));
    o.line("");
    if e.open {
        o.line("    /// The member of a wire value (`Unknown` when it is not a member).");
        o.line("    pub const fn from_u8(value: u8) -> Self {");
        o.line("        match value {");
        for v in &e.values {
            o.line(&format!("            {} => Self::{},", v.value, v.name));
        }
        o.line("            other => Self::Unknown(other),");
        o.line("        }");
        o.line("    }");
        o.line("");
        o.line("    /// The wire value.");
        o.line("    pub const fn to_u8(self) -> u8 {");
        o.line("        match self {");
        for v in &e.values {
            o.line(&format!("            Self::{} => {},", v.name, v.value));
        }
        o.line("            Self::Unknown(value) => value,");
        o.line("        }");
        o.line("    }");
        o.line("");
        o.line("    /// Whether this is a member (not `Unknown`).");
        o.line("    pub const fn is_known(self) -> bool {");
        o.line("        !matches!(self, Self::Unknown(_))");
        o.line("    }");
    } else {
        o.line("    /// The member of a wire value.");
        o.line("    pub const fn from_u8(value: u8) -> Option<Self> {");
        o.line("        match value {");
        for v in &e.values {
            o.line(&format!("            {} => Some(Self::{}),", v.value, v.name));
        }
        o.line("            _ => None,");
        o.line("        }");
        o.line("    }");
        o.line("");
        o.line("    /// The wire value.");
        o.line("    pub const fn to_u8(self) -> u8 {");
        o.line("        self as u8");
        o.line("    }");
    }
    o.line("");
    o.line("    /// The schema name of the value.");
    o.line("    pub const fn name(self) -> &'static str {");
    o.line("        match self {");
    for v in &e.values {
        o.line(&format!("            Self::{} => {:?},", v.name, v.name));
    }
    if e.open {
        o.line("            Self::Unknown(_) => \"Unknown\",");
    }
    o.line("        }");
    o.line("    }");
    o.line("");
    o.line("    fn read(r: &mut Reader<'_>, field: &'static str) -> Result<Self, DecodeError> {");
    if e.open {
        o.line("        let value = Self::from_u8(r.u8()?);");
        o.line("        if r.is_strict() && !value.is_known() {");
        o.line(&format!("            return Err(DecodeError::new(Defect::NotInEnum({:?}), field));", e.name));
        o.line("        }");
        o.line("        Ok(value)");
    } else {
        o.line(&format!(
            "        Self::from_u8(r.u8()?).ok_or(DecodeError::new(Defect::NotInEnum({:?}), field))",
            e.name
        ));
    }
    o.line("    }");
    o.line("}");
    o.line("");
}

fn struct_(s: &Struct, o: &mut Lines) {
    o.doc(&sentence(&s.doc), "");
    o.line("#[derive(Clone, Debug, Default, PartialEq)]");
    o.line(&format!("pub struct {} {{", s.name));
    for f in &s.fields {
        o.doc(&field_doc(f), "    ");
        o.line(&format!("    pub {}: {},", ident(&f.name), rust_type(&f.ty)));
    }
    o.line("}");
    o.line("");
    o.line(&format!("impl {} {{", s.name));
    o.line("    fn encoded_len(&self) -> usize {");
    o.line(&format!("        {}", len_expr(&s.fields, "self")));
    o.line("    }");
    o.line("");
    o.line("    fn write<B: BufMut>(&self, out: &mut B) {");
    for f in &s.fields {
        write_stmt(f, &format!("self.{}", ident(&f.name)), "        ", o);
    }
    o.line("    }");
    o.line("}");
    o.line("");
}

/// Expression of the encoded length of a field list (`base` names the value).
fn len_expr(fields: &[Field], base: &str) -> String {
    let fixed: usize = fields.iter().filter_map(|f| f.ty.scalar_size()).sum();
    let mut parts = Vec::new();
    for f in fields {
        let v = format!("{base}.{}", ident(&f.name));
        match &f.ty {
            Type::Str8 => parts.push(format!("1 + {v}.len()")),
            Type::Struct(_) => parts.push(format!("{v}.encoded_len()")),
            Type::List(item) => match item.scalar_size() {
                Some(n) => parts.push(format!("2 + {n} * {v}.len()")),
                None => parts.push(format!("2 + {v}.iter().map(|x| x.encoded_len()).sum::<usize>()")),
            },
            _ => {}
        }
    }
    let mut expr = fixed.to_string();
    for p in parts {
        expr = format!("{expr} + {p}");
    }
    expr
}

fn write_stmt(f: &Field, v: &str, ind: &str, o: &mut Lines) {
    let line = match &f.ty {
        Type::U8 => format!("out.put_u8({v});"),
        Type::U16 => format!("out.put_u16_le({v});"),
        Type::U32 => format!("out.put_u32_le({v});"),
        Type::U64 | Type::Id53 => format!("out.put_u64_le({v});"),
        Type::I32 => format!("out.put_i32_le({v});"),
        Type::F64 => format!("wire::put_f64(out, {v});"),
        Type::Bool => format!("out.put_u8(u8::from({v}));"),
        Type::Str8 => format!("wire::put_str8(out, &{v});"),
        Type::Enum(_) => format!("out.put_u8({v}.to_u8());"),
        Type::Struct(_) => format!("{v}.write(out);"),
        Type::List(item) => {
            o.line(&format!("{ind}wire::put_count16(out, {v}.len());"));
            o.line(&format!("{ind}for item in &{v} {{"));
            let item_field = Field {
                name: f.name.clone(),
                ty: (**item).clone(),
                min: None,
                max: None,
                doc: String::new(),
            };
            let deref = match **item {
                Type::Str8 | Type::Struct(_) => "item".to_owned(),
                _ => "*item".to_owned(),
            };
            write_stmt(&item_field, &deref, &format!("{ind}    "), o);
            o.line(&format!("{ind}}}"));
            return;
        }
    };
    o.line(&format!("{ind}{line}"));
}

/// Validation statements of the fields of `fields` reached through `base` (encoding).
fn check_stmts(
    schema: &Schema,
    msg: &str,
    fields: &[Field],
    base: &str,
    path: &str,
    ind: &str,
    o: &mut Lines,
) {
    for f in fields {
        let v = format!("{base}.{}", ident(&f.name));
        let p = format!("{path}{}", f.name);
        check_value(schema, msg, f, &f.ty, &v, &p, ind, o);
    }
}

#[allow(clippy::too_many_arguments)]
fn check_value(schema: &Schema, msg: &str, f: &Field, ty: &Type, v: &str, p: &str, ind: &str, o: &mut Lines) {
    match ty {
        Type::U8 | Type::U16 | Type::U32 | Type::I32 if f.is_bounded() => {
            o.line(&format!("{ind}wire::check_bounds({msg:?}, {p:?}, {v}, {}, {})?;", f.lo(), f.hi()));
        }
        Type::F64 => o.line(&format!("{ind}wire::check_f64({msg:?}, {p:?}, {v})?;")),
        Type::Id53 => o.line(&format!("{ind}wire::check_id53({msg:?}, {p:?}, {v})?;")),
        Type::Str8 => {
            o.line(&format!("{ind}wire::check_str8({msg:?}, {p:?}, &{v}, {}, {})?;", f.lo(), f.hi()))
        }
        Type::Enum(name) if schema.enum_(name).open => {
            o.line(&format!("{ind}wire::check_known({msg:?}, {p:?}, {v}.is_known(), {name:?})?;"));
        }
        Type::Struct(name) => {
            let fields = &schema.struct_(name).fields;
            if fields.iter().any(|f| needs_check(schema, f)) {
                check_stmts(schema, msg, fields, v, &format!("{p}."), ind, o);
            }
        }
        Type::List(item) => {
            o.line(&format!("{ind}wire::check_count16({msg:?}, {p:?}, {v}.len(), {})?;", f.hi()));
            let item_field = Field {
                name: f.name.clone(),
                ty: (**item).clone(),
                min: None,
                max: None,
                doc: String::new(),
            };
            if needs_check(schema, &item_field) {
                o.line(&format!("{ind}for item in &{v} {{"));
                let target = if item.scalar_size().is_some() { "*item" } else { "item" };
                check_value(schema, msg, &item_field, item, target, p, &format!("{ind}    "), o);
                o.line(&format!("{ind}}}"));
            }
        }
        _ => {}
    }
}

/// Whether a field needs an encoding check.
fn needs_check(schema: &Schema, f: &Field) -> bool {
    match &f.ty {
        Type::U8 | Type::U16 | Type::U32 | Type::I32 => f.is_bounded(),
        Type::F64 | Type::Id53 | Type::Str8 | Type::List(_) => true,
        Type::Struct(name) => schema.struct_(name).fields.iter().any(|f| needs_check(schema, f)),
        Type::Enum(name) => schema.enum_(name).open,
        Type::U64 | Type::Bool => false,
    }
}

/// Decoding expression of a value of a field (`path` = its dotted schema path).
fn read_expr(schema: &Schema, f: &Field, ty: &Type, path: &str, ind: &str) -> String {
    let bounded = |raw: &str| {
        if f.is_bounded() {
            format!("Reader::bounded(r.{raw}()?, {path:?}, {}, {})?", f.lo(), f.hi())
        } else {
            format!("r.{raw}()?")
        }
    };
    match ty {
        Type::U8 => bounded("u8"),
        Type::U16 => bounded("u16"),
        Type::U32 => bounded("u32"),
        Type::I32 => bounded("i32"),
        Type::U64 => "r.u64()?".into(),
        Type::Id53 => format!("r.id53({path:?})?"),
        Type::F64 => format!("r.f64({path:?})?"),
        Type::Bool => format!("r.bool({path:?})?"),
        Type::Str8 => format!("r.str8({path:?}, {}, {})?", f.lo(), f.hi()),
        Type::Enum(name) => format!("{name}::read(r, {path:?})?"),
        Type::Struct(name) => {
            let s = schema.struct_(name);
            let inner = format!("{ind}    ");
            let mut out = format!("{name} {{\n");
            for sf in &s.fields {
                let e = read_expr(schema, sf, &sf.ty, &format!("{path}.{}", sf.name), &inner);
                let _ = writeln!(out, "{inner}{}: {e},", ident(&sf.name));
            }
            out.push_str(ind);
            out.push('}');
            out
        }
        Type::List(item) => {
            let item_field = Field {
                name: f.name.clone(),
                ty: (**item).clone(),
                min: None,
                max: None,
                doc: String::new(),
            };
            let i1 = format!("{ind}    ");
            let i2 = format!("{ind}        ");
            let item_expr = read_expr(schema, &item_field, item, path, &i2);
            format!(
                "{{\n{i1}let count = r.count16({path:?}, {}, {})?;\n{i1}let mut items = Vec::with_capacity(count);\n\
                 {i1}for _ in 0..count {{\n{i2}items.push({item_expr});\n{i1}}}\n{i1}items\n{ind}}}",
                f.hi(),
                schema.item_min_size(item),
            )
        }
    }
}

fn msg_type(schema: &Schema, o: &mut Lines) {
    o.line("/// Type byte of every message (0x01-0x7F client to server, 0x80-0xFF server to client).");
    o.line("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]");
    o.line("#[repr(u8)]");
    o.line("pub enum MsgType {");
    for m in &schema.messages {
        o.line(&format!("    /// [`{}`].", type_name(m)));
        o.line(&format!("    {} = {:#04x},", type_name(m), m.id));
    }
    o.line("}");
    o.line("");
    let all: Vec<String> = schema.messages.iter().map(|m| format!("Self::{}", type_name(m))).collect();
    o.line("impl MsgType {");
    o.line("    /// Every message type, in schema order.");
    o.line(&format!("    pub const ALL: [Self; {}] = [", all.len()));
    for chunk in all.chunks(6) {
        o.line(&format!("        {},", chunk.join(", ")));
    }
    o.line("    ];");
    o.line("");
    o.line("    /// The message type of a type byte.");
    o.line("    pub const fn from_u8(value: u8) -> Option<Self> {");
    o.line("        match value {");
    for m in &schema.messages {
        o.line(&format!("            {:#04x} => Some(Self::{}),", m.id, type_name(m)));
    }
    o.line("            _ => None,");
    o.line("        }");
    o.line("    }");
    o.line("");
    o.line("    /// The type byte.");
    o.line("    pub const fn to_u8(self) -> u8 {");
    o.line("        self as u8");
    o.line("    }");
    o.line("");
    o.line("    /// Whether this is a client to server message.");
    o.line("    pub const fn is_client(self) -> bool {");
    o.line("        (self as u8) < 0x80");
    o.line("    }");
    o.line("");
    o.line("    /// Name of the message in the vectors and the C++ codec (`\"Move\"`, `\"C_Ping\"`, `\"S_Ping\"`).");
    o.line("    pub const fn name(self) -> &'static str {");
    o.line("        match self {");
    for m in &schema.messages {
        o.line(&format!("            Self::{} => {:?},", type_name(m), m.key));
    }
    o.line("        }");
    o.line("    }");
    o.line("");
    for (what, pick) in [("min_len", 0usize), ("max_len", 1usize)] {
        let doc = if pick == 0 { "Smallest" } else { "Largest" };
        o.line(&format!("    /// {doc} encoded size of the message, type byte included."));
        o.line(&format!("    pub const fn {what}(self) -> usize {{"));
        o.line("        match self {");
        for m in &schema.messages {
            let (min, max) = schema.message_size(m);
            o.line(&format!("            Self::{} => {},", type_name(m), if pick == 0 { min } else { max }));
        }
        o.line("        }");
        o.line("    }");
        if pick == 0 {
            o.line("");
        }
    }
    o.line("}");
    o.line("");
    o.line(
        "/// The defect of a frame whose type byte is not the one expected (`client`: the direction of the",
    );
    o.line("/// expected message).");
    o.line("pub(crate) fn type_defect(first: Option<u8>, client: bool) -> Defect {");
    o.line("    match first.map(MsgType::from_u8) {");
    o.line("        None => Defect::Empty,");
    o.line("        Some(None) => Defect::UnknownType,");
    o.line("        Some(Some(t)) if t.is_client() != client => Defect::WrongDirection,");
    o.line("        Some(Some(_)) => Defect::WrongType,");
    o.line("    }");
    o.line("}");
    o.line("");
}

fn message(schema: &Schema, m: &Message, o: &mut Lines) {
    let name = type_name(m);
    let dir = match m.dir {
        Dir::C2s => "Client to server",
        Dir::S2c => "Server to client",
    };
    o.doc(&format!("`{}` ({:#04x}, {}). {}", m.key, m.id, dir.to_lowercase(), sentence(&m.doc)), "");
    o.line("#[derive(Clone, Debug, Default, PartialEq)]");
    o.line(&format!("pub struct {name} {{"));
    let relayed =
        m.relay_of.as_ref().and_then(|r| schema.messages.iter().find(|c| c.dir == Dir::C2s && &c.name == r));
    for (i, f) in m.fields.iter().enumerate() {
        let f = match relayed {
            Some(c) if f.doc.is_empty() => &c.fields[i + 1],
            _ => f,
        };
        o.doc(&field_doc(f), "    ");
        o.line(&format!("    pub {}: {},", ident(&f.name), rust_type(&f.ty)));
    }
    o.line("}");
    o.line("");
    let (min, max) = schema.message_size(m);
    o.line(&format!("impl Message for {name} {{"));
    o.line(&format!("    const TYPE: MsgType = MsgType::{name};"));
    o.line(&format!("    const MIN_LEN: usize = {min};"));
    o.line(&format!("    const MAX_LEN: usize = {max};"));
    o.line("");
    o.line("    fn encoded_len(&self) -> usize {");
    o.line(&format!("        1 + {}", len_expr(&m.fields, "self")));
    o.line("    }");
    o.line("");
    o.line("    fn validate(&self) -> Result<(), EncodeError> {");
    check_stmts(schema, &m.key, &m.fields, "self", "", "        ", o);
    o.line("        Ok(())");
    o.line("    }");
    o.line("");
    o.line("    fn write_fields<B: BufMut>(&self, out: &mut B) {");
    for f in &m.fields {
        write_stmt(f, &format!("self.{}", ident(&f.name)), "        ", o);
    }
    o.line("    }");
    o.line("");
    o.line("    fn read_fields(r: &mut Reader<'_>) -> Result<Self, DecodeError> {");
    o.line("        Ok(Self {");
    for f in &m.fields {
        let e = read_expr(schema, f, &f.ty, &f.name, "            ");
        o.line(&format!("            {}: {e},", ident(&f.name)));
    }
    o.line("        })");
    o.line("    }");
    o.line("}");
    o.line("");
    if let Some(c) = relayed {
        let client = type_name(c);
        o.line(&format!("impl {client} {{"));
        o.doc(
            &format!(
                "The server `{}` frame that relays the client frame `frame`: `frame` is validated (it must be a \
                 whole client `{}`), then copied without its seq.",
                m.name, c.name
            ),
            "    ",
        );
        o.line(&format!(
            "    pub fn relay_frame(frame: &[u8]) -> Result<[u8; {name}::MAX_LEN], DecodeError> {{"
        ));
        o.line("        Self::decode(frame)?;");
        o.line(&format!("        let mut out = [0; {name}::MAX_LEN];"));
        o.line(&format!("        out[0] = MsgType::{name}.to_u8();"));
        o.line("        out[1..].copy_from_slice(&frame[5..]);");
        o.line("        Ok(out)");
        o.line("    }");
        o.line("}");
        o.line("");
    }
}

fn msg_enum(schema: &Schema, dir: Dir, o: &mut Lines) {
    let (name, what) = match dir {
        Dir::C2s => ("ClientMsg", "client to server"),
        Dir::S2c => ("ServerMsg", "server to client"),
    };
    let msgs: Vec<&Message> = schema.messages.iter().filter(|m| m.dir == dir).collect();
    o.line(&format!("/// A {what} message."));
    o.line("#[derive(Clone, Debug, PartialEq)]");
    o.line(&format!("pub enum {name} {{"));
    for m in &msgs {
        o.line(&format!("    /// [`{}`].", type_name(m)));
        o.line(&format!("    {}({}),", m.name, type_name(m)));
    }
    o.line("}");
    o.line("");
    o.line(&format!("impl {name} {{"));
    match dir {
        Dir::C2s => {
            o.line("    /// Strict decoding (the server's): unknown types, server types, truncation, trailing bytes and");
            o.line("    /// every value outside its bounds are refused.");
            o.line("    pub fn decode(buf: &[u8]) -> Result<Self, DecodeError> {");
            o.line("        let mut r = Reader::new(buf, true);");
            o.line("        let msg = match buf.first().copied() {");
            for m in &msgs {
                o.line(&format!(
                    "            Some({:#04x}) => Self::{}({}::read_fields(&mut r)?),",
                    m.id,
                    m.name,
                    type_name(m)
                ));
            }
            o.line("            first => return Err(DecodeError::new(type_defect(first, true), \"\")),");
            o.line("        };");
            o.line("        r.finish()?;");
            o.line("        Ok(msg)");
            o.line("    }");
        }
        Dir::S2c => {
            o.line("    /// Lenient decoding (the clients'): `Ok(None)` for a message to ignore (a type this codec does");
            o.line("    /// not know as a server message), trailing bytes ignored (fields of a later minor), unknown");
            o.line(
                "    /// values of open enums kept as `Unknown`. Anything else outside the rules is refused.",
            );
            o.line("    pub fn decode(buf: &[u8]) -> Result<Option<Self>, DecodeError> {");
            o.line("        Self::decode_with(buf, false)");
            o.line("    }");
            o.line("");
            o.line(
                "    /// Strict decoding: the message must be exactly one of this minor (tests of a server).",
            );
            o.line("    pub fn decode_exact(buf: &[u8]) -> Result<Self, DecodeError> {");
            o.line(
                "        Self::decode_with(buf, true)?.ok_or(DecodeError::new(Defect::UnknownType, \"\"))",
            );
            o.line("    }");
            o.line("");
            o.line("    fn decode_with(buf: &[u8], strict: bool) -> Result<Option<Self>, DecodeError> {");
            o.line("        let mut r = Reader::new(buf, strict);");
            o.line("        let msg = match buf.first().copied() {");
            for m in &msgs {
                o.line(&format!(
                    "            Some({:#04x}) => Self::{}({}::read_fields(&mut r)?),",
                    m.id,
                    m.name,
                    type_name(m)
                ));
            }
            o.line("            None => return Err(DecodeError::new(Defect::Empty, \"\")),");
            o.line("            Some(_) if !strict => return Ok(None),");
            o.line("            first => return Err(DecodeError::new(type_defect(first, false), \"\")),");
            o.line("        };");
            o.line("        r.finish()?;");
            o.line("        Ok(Some(msg))");
            o.line("    }");
        }
    }
    o.line("");
    o.line("    /// Type of the message.");
    o.line("    pub fn msg_type(&self) -> MsgType {");
    o.line("        match self {");
    for m in &msgs {
        o.line(&format!("            Self::{}(_) => MsgType::{},", m.name, type_name(m)));
    }
    o.line("        }");
    o.line("    }");
    o.line("");
    if dir == Dir::C2s {
        o.line("    /// `seq` of the message.");
        o.line("    pub fn seq(&self) -> u32 {");
        o.line("        match self {");
        for m in &msgs {
            o.line(&format!("            Self::{}(m) => m.seq,", m.name));
        }
        o.line("        }");
        o.line("    }");
        o.line("");
    }
    o.line("    /// Encoded size, type byte included.");
    o.line("    pub fn encoded_len(&self) -> usize {");
    o.line("        match self {");
    for m in &msgs {
        o.line(&format!("            Self::{}(m) => m.encoded_len(),", m.name));
    }
    o.line("        }");
    o.line("    }");
    o.line("");
    o.line("    /// Encodes the message (see [`Message::encode`]).");
    o.line("    pub fn encode<B: BufMut>(&self, out: &mut B) -> Result<(), EncodeError> {");
    o.line("        match self {");
    for m in &msgs {
        o.line(&format!("            Self::{}(m) => m.encode(out),", m.name));
    }
    o.line("        }");
    o.line("    }");
    o.line("");
    o.line("    /// The encoded message in a buffer of the exact size.");
    o.line("    pub fn to_bytes(&self) -> Result<bytes::Bytes, EncodeError> {");
    o.line("        let mut out = bytes::BytesMut::with_capacity(self.encoded_len());");
    o.line("        self.encode(&mut out)?;");
    o.line("        Ok(out.freeze())");
    o.line("    }");
    o.line("}");
    o.line("");
    for m in &msgs {
        o.line(&format!("impl From<{}> for {name} {{", type_name(m)));
        o.line(&format!("    fn from(m: {}) -> Self {{", type_name(m)));
        o.line(&format!("        Self::{}(m)", m.name));
        o.line("    }");
        o.line("}");
        o.line("");
    }
}

/// Writes `gen_json.rs`: conversions between the messages and their JSON form in the vectors
/// (schema field names, enums as numbers, structs as objects, lists as arrays).
pub fn json_bridge(schema: &Schema) -> String {
    let mut o = Lines::new();
    o.raw(HEADER);
    o.line("");
    o.line("//! JSON form of the messages, as in the golden vectors (tests only).");
    o.line("");
    o.line("use serde_json::{Map, Value};");
    o.line("");
    o.line("use crate::r#gen::*;");
    o.line("");
    o.line("fn int<T: TryFrom<i64>>(v: &Value, key: &str) -> Option<T> {");
    o.line("    T::try_from(v.get(key)?.as_i64()?).ok()");
    o.line("}");
    o.line("");
    o.line("fn uint<T: TryFrom<u64>>(v: &Value, key: &str) -> Option<T> {");
    o.line("    T::try_from(v.get(key)?.as_u64()?).ok()");
    o.line("}");
    o.line("");
    for e in &schema.enums {
        o.line(&format!("fn {}_from(v: &Value) -> Option<{}> {{", snake(&e.name), e.name));
        if e.open {
            o.line(&format!("    Some({}::from_u8(u8::try_from(v.as_u64()?).ok()?))", e.name));
        } else {
            o.line(&format!("    {}::from_u8(u8::try_from(v.as_u64()?).ok()?)", e.name));
        }
        o.line("}");
        o.line("");
    }
    let items: Vec<(String, &[Field])> = schema
        .structs
        .iter()
        .map(|s| (s.name.clone(), s.fields.as_slice()))
        .chain(schema.messages.iter().map(|m| (type_name(m), m.fields.as_slice())))
        .collect();
    for (name, fields) in &items {
        let fname = snake(name);
        o.line(&format!("fn {fname}_to_json(m: &{name}) -> Value {{"));
        o.line("    let mut o = Map::new();");
        for f in *fields {
            o.line(&format!(
                "    o.insert({:?}.into(), {});",
                f.name,
                to_json_expr(&f.ty, &format!("m.{}", ident(&f.name)))
            ));
        }
        o.line("    Value::Object(o)");
        o.line("}");
        o.line("");
        o.line(&format!("fn {fname}_from_json(v: &Value) -> Option<{name}> {{"));
        o.line(&format!("    Some({name} {{"));
        for f in *fields {
            o.line(&format!("        {}: {},", ident(&f.name), from_json_expr(&f.ty, &f.name)));
        }
        o.line("    })");
        o.line("}");
        o.line("");
    }
    for dir in [Dir::C2s, Dir::S2c] {
        let (en, fname) = match dir {
            Dir::C2s => ("ClientMsg", "client"),
            Dir::S2c => ("ServerMsg", "server"),
        };
        o.line(&format!("/// The vector name and the JSON fields of a {fname} message."));
        o.line(&format!("pub fn {fname}_to_json(m: &{en}) -> (&'static str, Value) {{"));
        o.line("    match m {");
        for m in schema.messages.iter().filter(|m| m.dir == dir) {
            o.line(&format!(
                "        {en}::{}(m) => ({:?}, {}_to_json(m)),",
                m.name,
                m.key,
                snake(&type_name(m))
            ));
        }
        o.line("    }");
        o.line("}");
        o.line("");
        o.line(&format!("/// The {fname} message of a vector name and JSON fields."));
        o.line(&format!("pub fn {fname}_from_json(key: &str, v: &Value) -> Option<{en}> {{"));
        o.line("    Some(match key {");
        for m in schema.messages.iter().filter(|m| m.dir == dir) {
            o.line(&format!(
                "        {:?} => {en}::{}({}_from_json(v)?),",
                m.key,
                m.name,
                snake(&type_name(m))
            ));
        }
        o.line("        _ => return None,");
        o.line("    })");
        o.line("}");
        o.line("");
    }
    o.finish()
}

fn to_json_expr(ty: &Type, v: &str) -> String {
    match ty {
        Type::Str8 => format!("{v}.clone().into()"),
        Type::Enum(_) => format!("{v}.to_u8().into()"),
        Type::Struct(name) => format!("{}_to_json(&{v})", snake(name)),
        Type::List(item) => match &**item {
            Type::Struct(name) => format!("Value::Array({v}.iter().map({}_to_json).collect())", snake(name)),
            Type::Enum(_) => format!("Value::Array({v}.iter().map(|x| x.to_u8().into()).collect())"),
            _ => format!("Value::Array({v}.iter().map(|&x| Value::from(x)).collect())"),
        },
        _ => format!("{v}.into()"),
    }
}

fn from_json_expr(ty: &Type, key: &str) -> String {
    match ty {
        Type::U8 | Type::U16 | Type::U32 | Type::U64 | Type::Id53 => format!("uint(v, {key:?})?"),
        Type::I32 => format!("int(v, {key:?})?"),
        Type::F64 => format!("v.get({key:?})?.as_f64()?"),
        Type::Bool => format!("v.get({key:?})?.as_bool()?"),
        Type::Str8 => format!("v.get({key:?})?.as_str()?.to_owned()"),
        Type::Enum(name) => format!("{}_from(v.get({key:?})?)?", snake(name)),
        Type::Struct(name) => format!("{}_from_json(v.get({key:?})?)?", snake(name)),
        Type::List(item) => {
            let item_fn = match &**item {
                Type::Struct(name) => format!("{}_from_json", snake(name)),
                Type::Enum(name) => format!("{}_from", snake(name)),
                Type::F64 => "Value::as_f64".into(),
                Type::Bool => "Value::as_bool".into(),
                Type::I32 => "|x| x.as_i64().and_then(|n| i32::try_from(n).ok())".into(),
                other => format!("|x| x.as_u64().and_then(|n| {}::try_from(n).ok())", rust_type(other)),
            };
            format!("v.get({key:?})?.as_array()?.iter().map({item_fn}).collect::<Option<Vec<_>>>()?")
        }
    }
}
